import { defineAdminCopy } from "../i18n/copy";
import { formatAdminDateTime } from "../i18n/format";

/** Copy for the access management screen. */
export const accessCopy = defineAdminCopy({
  zh: {
    title: "權限管理",
    subtitle: "管理後台使用者、邀請及最近權限變更紀錄。",
    invite: "邀請使用者",
    inviteDescription: "Supabase 會向此電郵發送管理後台邀請。",
    email: "電郵",
    role: "角色",
    status: "狀態",
    invited: "邀請時間",
    updated: "更新時間",
    actions: "操作",
    active: "啟用",
    pending: "待接受邀請",
    disabled: "已停用",
    activeAdmins: "啟用使用者",
    pendingInvites: "待接受邀請",
    disabledUsers: "已停用使用者",
    audit: "最近紀錄",
    noAudit: "未有權限管理紀錄。",
    noUsers: "沒有管理員紀錄",
    submitInvite: "發送邀請",
    sending: "發送中...",
    resend: "重發",
    disable: "停用",
    reactivate: "重新啟用",
    currentUser: "你",
    genericError: "操作失敗，請稍後再試。",
    auditLoadError: "未能載入紀錄。",
    retry: "重試",
    auditPagerLabel: "權限紀錄分頁",
    previous: "上一頁",
    next: "下一頁",
    auditPage: (page: number) => `第 ${page} 頁`,
    // Kept as the legacy zh-HK date and time, so the Chinese screen is unchanged.
    dateTime: (value: string | null) =>
      value
        ? new Intl.DateTimeFormat("zh-HK", {
            dateStyle: "medium",
            timeStyle: "short",
            timeZone: "Asia/Hong_Kong",
          }).format(new Date(value))
        : "—",
    roles: {
      staff: "職員",
      treasurer: "司庫",
      admin: "管理員",
    },
    actionLabels: {
      "admin_user.invite": "邀請",
      "admin_user.invite_resend": "重發邀請",
      "admin_user.role_update": "更新角色",
      "admin_user.disable": "停用",
      "admin_user.reactivate": "重新啟用",
      "admin_user.activate_from_invite": "接受邀請",
      "admin_user.update": "更新",
    },
  },
  en: {
    title: "Access management",
    subtitle: "Manage admin users, invitations and recent access changes.",
    invite: "Invite user",
    inviteDescription: "Supabase will send an admin invitation to this email.",
    email: "Email",
    role: "Role",
    status: "Status",
    invited: "Invited",
    updated: "Updated",
    actions: "Actions",
    active: "Active",
    pending: "Invite pending",
    disabled: "Disabled",
    activeAdmins: "Active users",
    pendingInvites: "Pending invites",
    disabledUsers: "Disabled users",
    audit: "Recent history",
    noAudit: "No access management history yet.",
    noUsers: "No admin users found",
    submitInvite: "Send invite",
    sending: "Sending...",
    resend: "Resend",
    disable: "Disable",
    reactivate: "Reactivate",
    currentUser: "You",
    genericError: "The action failed. Try again later.",
    auditLoadError: "Could not load the history.",
    retry: "Retry",
    auditPagerLabel: "Access history pagination",
    previous: "Previous",
    next: "Next",
    auditPage: (page: number) => `Page ${page}`,
    dateTime: (value: string | null) => (value ? formatAdminDateTime(value, "en") : "—"),
    roles: {
      staff: "Staff",
      treasurer: "Treasurer",
      admin: "Admin",
    },
    actionLabels: {
      "admin_user.invite": "Invited",
      "admin_user.invite_resend": "Resent invite",
      "admin_user.role_update": "Changed role",
      "admin_user.disable": "Disabled",
      "admin_user.reactivate": "Reactivated",
      "admin_user.activate_from_invite": "Accepted invite",
      "admin_user.update": "Updated",
    },
  },
});
