/** Exact Task8 scope; no fixture/provider/native admission changes. */
export const tables = [
  "admin_user",
  "supporter",
  "volunteer_activity",
  "volunteer_registration",
  "supporter_consent_intent",
  "audit_log",
];
export const fixtureScope = ["auth.users", ...tables];
export const targets = [
  "create_volunteer_registration_idempotent",
  "clone_volunteer_activity_with_audit",
];
const tableList = tables.map((n) => "'public." + n + "'::regclass").join(",");
/** Relation rules/inheritance and persistence are independent of column/index tuples. */
export const shapeQuery = `select jsonb_agg(jsonb_build_object('table',c.oid::regclass::text,'persistence',c.relpersistence,'hasRules',c.relhasrules,'hasSubclass',c.relhassubclass,'rules',(select coalesce(jsonb_agg(jsonb_build_object('name',r.rulename,'type',r.ev_type,'enabled',r.ev_enabled,'instead',r.is_instead,'definition',pg_get_ruledef(r.oid)) order by r.rulename),'[]'::jsonb) from pg_rewrite r where r.ev_class=c.oid),'parents',(select coalesce(jsonb_agg(jsonb_build_object('table',i.inhparent::regclass::text,'sequence',i.inhseqno,'detachPending',i.inhdetachpending) order by i.inhparent::regclass::text,i.inhseqno),'[]'::jsonb) from pg_inherits i where i.inhrelid=c.oid),'children',(select coalesce(jsonb_agg(jsonb_build_object('table',i.inhrelid::regclass::text,'sequence',i.inhseqno,'detachPending',i.inhdetachpending) order by i.inhrelid::regclass::text,i.inhseqno),'[]'::jsonb) from pg_inherits i where i.inhparent=c.oid)) order by c.oid::regclass::text) value from pg_class c where c.oid in (${tableList},'auth.users'::regclass)`;
export const functionsQuery = `select coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'allargs',pg_get_function_arguments(p.oid),'result',pg_get_function_result(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'effectiveAcl',(select jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(a.grantor),'grantee',case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end,'privilege',a.privilege_type,'grantable',a.is_grantable) order by pg_get_userbyid(a.grantor),a.grantee,a.privilege_type) from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a),'config',p.proconfig,'definer',p.prosecdef,'language',l.lanname,'defaults',p.pronargdefaults,'defaultExpression',pg_get_expr(p.proargdefaults,0),'cost',p.procost,'rows',p.prorows,'strict',p.proisstrict,'leakproof',p.proleakproof,'parallel',p.proparallel,'volatility',p.provolatile,'returnsSet',p.proretset,'variadic',p.provariadic,'support',p.prosupport::regproc::text,'transforms',p.protrftypes,'modes',p.proargmodes,'body',md5(p.prosrc),'definition',md5(pg_get_functiondef(p.oid))) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),'[]'::jsonb) value from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where p.prokind='f' and (p.oid in(select tgfoid from pg_trigger where tgrelid in(${tableList}) and not tgisinternal) or (n.nspname='public' and (p.proname like 'volunteer_%' or p.proname in ('create_volunteer_registration','record_public_consent_intents','enforce_public_submission_identity'))) or (n.nspname='private' and p.proname in ('lock_admin_user_mutation','require_active_admin_user')) or (n.nspname='auth' and p.proname='uid'))`;
export const targetQuery = functionsQuery.replace(
  functionsQuery.slice(functionsQuery.indexOf("where p.prokind='f'")),
  "where n.nspname='public' and p.proname in ('create_volunteer_registration_idempotent','clone_volunteer_activity_with_audit')",
);
export const authQuery = `select jsonb_build_object('owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'serviceSelect',has_any_column_privilege('service_role',c.oid,'SELECT'),'serviceUpdate',has_any_column_privilege('service_role',c.oid,'UPDATE'),'postgresSelect',has_table_privilege('postgres',c.oid,'SELECT'),'postgresUpdate',has_table_privilege('postgres',c.oid,'UPDATE'),'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'acl',a.attacl::text,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull) order by a.attnum) from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)) value from pg_class c where c.oid='auth.users'::regclass`;
export const indexDetailsQuery = `select coalesce(jsonb_agg(jsonb_build_object('table',i.indrelid::regclass::text,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'kind',c.relkind,'persistence',c.relpersistence,'options',c.reloptions,'access',am.amname,'definition',pg_get_indexdef(i.indexrelid),'nkeys',i.indnkeyatts,'natts',i.indnatts,'unique',i.indisunique,'nullsNotDistinct',i.indnullsnotdistinct,'primary',i.indisprimary,'exclusion',i.indisexclusion,'immediate',i.indimmediate,'clustered',i.indisclustered,'valid',i.indisvalid,'ready',i.indisready,'live',i.indislive,'replicaIdentity',i.indisreplident,'keys',i.indkey::text,'flags',i.indoption::text,'predicate',pg_get_expr(i.indpred,i.indrelid),'expressions',pg_get_expr(i.indexprs,i.indrelid)) order by i.indrelid::regclass::text,c.relname),'[]'::jsonb) value from pg_index i join pg_class c on c.oid=i.indexrelid join pg_am am on am.oid=c.relam where i.indrelid in (${tableList})`;
export const nativeQuery = `select coalesce(jsonb_agg(jsonb_build_object('constraint',c.conname,'own',c.conrelid::regclass::text,'referenced',c.confrelid::regclass::text,'type',t.tgtype,'function',t.tgfoid::regprocedure::text,'table',t.tgrelid::regclass::text,'other',t.tgconstrrelid::regclass::text,'index',t.tgconstrindid::regclass::text,'enabled',t.tgenabled,'internal',t.tgisinternal,'parent',t.tgparentid,'deferrable',t.tgdeferrable,'deferred',t.tginitdeferred,'nargs',t.tgnargs,'attr',t.tgattr::text,'args',encode(t.tgargs,'hex'),'qual',pg_get_expr(t.tgqual,t.tgrelid),'oldtable',t.tgoldtable,'newtable',t.tgnewtable,'dependencies',(select jsonb_agg(jsonb_build_object('class',d.classid::regclass::text,'subid',d.objsubid,'refclass',d.refclassid::regclass::text,'refconstraint',case when d.refclassid='pg_constraint'::regclass then (select q.conname from pg_constraint q where q.oid=d.refobjid) end,'sameconstraint',d.refobjid=c.oid,'refsubid',d.refobjsubid,'deptype',d.deptype) order by d.classid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid,d.deptype) from pg_depend d where d.classid='pg_trigger'::regclass and d.objid=t.oid)) order by c.conrelid::regclass::text,c.conname,t.tgtype,t.tgrelid::regclass::text),'[]'::jsonb) value from pg_constraint c join pg_trigger t on t.tgconstraint=c.oid where (c.conrelid in (${tableList}) or c.confrelid in (${tableList})) and c.contype='f'`;
