/** Own source-component diagnostic. Unknown Auth tuple must fail before writes. */
import { mkdir, readFile, writeFile, copyFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { captureModernLocalSchema, createProductionClone, assertSafeFixtureTables, snapshot, hash, localSourceState } from "../../../../supabase/rls-tests/helpers/productionSchemaClone";
import { fixtureScope, dependencies, functionsQuery, authQuery, nativeQuery, indexDetailsQuery, shapesQuery } from "./task-11-profile";
const root=process.cwd(),out=resolve(process.argv[2]??"");
if(process.env.R01_FINANCE_CALLBACK_ALLOW_LOCAL_FIXTURES!=="1"||!out.startsWith(resolve(".superpowers/sdd/r01-forward-schema-plan-20261001/task-11-component-red-")))throw Error("Exact own component opt-in/output required");
const source=".superpowers/sdd/r01-forward-schema-plan-20261001/task-9-fix-4-helper-comparison.json";
const vendor=".superpowers/sdd/r01-forward-schema-plan-20261001/task-9-fix-4-stageb-20261002T091944Z/after-auth-catalog.json";
const migration="supabase/migrations/20261002170945_r01_finance_callback_forward.sql";
const paths=[source,vendor,migration,"docs/evidence/audit-remediation-20260927/r01-forward/task-11-component-red.ts","docs/evidence/audit-remediation-20260927/r01-forward/task-11-profile.ts","docs/evidence/audit-remediation-20260927/r01-forward/task-10-profile.ts","docs/evidence/audit-remediation-20260927/r01-forward/task-9-profile.ts","supabase/rls-tests/helpers/productionSchemaClone.ts",...dependencies.map(([f])=>"supabase/migrations/"+f)];
await mkdir(out,{recursive:true});const sha=(b:Buffer)=>createHash("sha256").update(b).digest("hex");const bindings:Record<string,unknown>={};
for(const [i,p]of paths.entries()){const b=await readFile(p);const proc=Bun.spawn(["git","hash-object","--no-filters",p],{stdout:"pipe",stderr:"pipe"});const [blob,err,exit]=await Promise.all([new Response(proc.stdout).text(),new Response(proc.stderr).text(),proc.exited]);if(exit||err)throw Error("Binding failed "+p);bindings[p]={rawSha256:sha(b),canonicalSha256:hash(b.toString().replaceAll("\r\n","\n")),rawGitBlob:blob.trim(),rawBytes:b.length,archive:"s"+i+".source"};await copyFile(p,resolve(out,"s"+i+".source"));}
const actualSource=await readFile(source,"utf8");if(hash(actualSource)!=="b1afa5d56a9a5793ae7dc618479fd997b74d635093dd3f5eb2a7ea2b3af7ab77")throw Error("Independently captured official source provenance differs");
const sourceObject=JSON.parse(actualSource),vendorObject=JSON.parse(await readFile(vendor,"utf8"));
if(!vendorObject.functions.some((f:Record<string,unknown>)=>f.schema==="auth"&&f.name==="uid"&&f.definition===sourceObject.finalHelper.definition))throw Error("Actual vendor rendered source binding differs");
const requiredFinalFlags=["schemaParity","fullScannerPassed","dependenciesBound","baselineAccepted","expected55000","candidateRollbackPreserved","onlyAuthDefinitionChanged","supplementalPreserved","normalDrop","templatePreserved","modernPreserved","frozenInputsPreserved"];
const r:Record<string,unknown>={receiptType:"component-red",mode:"component",out,at:new Date().toISOString(),bindings,sourceBase:"d45b849d300f76700efcf5450a9b426e32cc372f",qualification:"Own PG17.6 component uses independently bound actual17.11/Auth LF SQL; not full17.11 CI bootstrap",requiredFinalFlags,error:null,failedFinalFlags:[],task1Applied:false,task8Applied:false};
let c:Awaited<ReturnType<typeof createProductionClone>>|undefined;let modernBefore:string|undefined;const modern="postgresql://postgres:postgres@127.0.0.1:57322/postgres";
try{modernBefore=await localSourceState(modern);const cap=await captureModernLocalSchema();c=await createProductionClone(cap);const db=c.sql;r.clone=c.name;r.schemaParity=true;r.zeroApplicationTables=c.tableCount;await assertSafeFixtureTables(db,fixtureScope);r.fullScannerPassed=true;
for(const [f,h]of dependencies){const b=await readFile(resolve("supabase/migrations",f));if(sha(b)!==h)throw Error("Dependency bytes differ "+f);await db.begin(async tx=>{await tx`set local role postgres`;await tx.unsafe(b.toString());});}r.dependenciesBound=true;
const extra=async(sql:typeof db)=>({auth:(await sql.unsafe(authQuery))[0].value,native:(await sql.unsafe(nativeQuery))[0].value,indexes:(await sql.unsafe(indexDetailsQuery))[0].value,shapes:(await sql.unsafe(shapesQuery))[0].value});
const candidate=await readFile(migration,"utf8"),rollback=new Error("Own component rollback");
try{await db.begin(async tx=>{await tx`set local role postgres`;await tx.unsafe(candidate);r.baselineAccepted=true;throw rollback;});}catch(e){if(e!==rollback)throw e;}
const before=await snapshot(db),beforeFunctions=await db.unsafe(functionsQuery),beforeExtra=await extra(db);r.beforeCatalog=before;r.beforeFunctions=beforeFunctions;r.beforeExtra=beforeExtra;
try{await db.begin(async tx=>{await tx`set local role supabase_auth_admin`;await tx.unsafe(sourceObject.finalHelper.definition);await tx`set local role postgres`;
const afterFunctions=await tx.unsafe(functionsQuery),afterExtra=await extra(tx as typeof db);r.componentFunctions=afterFunctions;r.componentExtra=afterExtra;r.componentCatalog=await snapshot(tx as typeof db);
const strip=(fs:Record<string,unknown>[])=>fs.filter(f=>!(f.schema==="auth"&&f.name==="uid"));r.onlyAuthDefinitionChanged=hash(before)===hash(r.componentCatalog)&&hash(strip(beforeFunctions))===hash(strip(afterFunctions));r.supplementalPreserved=hash(beforeExtra)===hash(afterExtra);
const beforeCandidate=hash(await snapshot(tx as typeof db));await tx.unsafe("savepoint task11_component_candidate");let err:unknown;try{await tx.unsafe(candidate);}catch(e){err=e;}await tx.unsafe("rollback to savepoint task11_component_candidate");r.code=(err as {errno?:string}|undefined)?.errno;r.candidateError=String(err);r.expected55000=r.code==="55000";r.candidateRollbackPreserved=beforeCandidate===hash(await snapshot(tx as typeof db));throw rollback;});}catch(e){if(e!==rollback)throw e;}
}catch(e){r.error=String(e);}finally{if(c){try{await c.close();r.normalDrop=true;}catch(e){r.normalDrop=false;r.error=[r.error,String(e)].filter(Boolean).join("; ");}r.templatePreserved=c.templatePreserved;}if(modernBefore){try{r.modernPreserved=modernBefore===await localSourceState(modern);}catch(e){r.modernPreserved=false;r.error=[r.error,String(e)].filter(Boolean).join("; ");}}r.frozenInputsPreserved=true;for(const [p,entry]of Object.entries(bindings))if(sha(await readFile(p))!==(entry as {rawSha256:string}).rawSha256)r.frozenInputsPreserved=false;r.failedFinalFlags=requiredFinalFlags.filter(f=>r[f]!==true);r.eligible=!r.error&&!(r.failedFinalFlags as string[]).length;await writeFile(resolve(out,"receipt.json"),JSON.stringify(r,null,2)+"\n");console.log(JSON.stringify({out,eligible:r.eligible,code:r.code,candidateError:r.candidateError,error:r.error,failedFinalFlags:r.failedFinalFlags}));process.exitCode=r.eligible?0:1;}
