/** Task12 owns these actual runtime prerequisites; no profile copied by analogy. */
import { dependencies as preceding } from "./task-11-profile";
export const tables = ["admin_user", "group_enquiries", "audit_log"];
export const fixtureScope = ["auth.users", ...tables];
export const names = ["update_group_enquiry_with_audit"];
export const dependencies = [
  ...preceding,
  [
    "20261002170945_r01_finance_callback_forward.sql",
    "6bf3c277583ef5d792cd8b6c957fdf892354ca32f0d179cd2488252292d89889",
  ],
] as const;
const tableList = fixtureScope
  .map((n) => "'" + (n.includes(".") ? n : "public." + n) + "'::regclass")
  .join(",");
export const shapesQuery = `select coalesce(jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname,'persistence',c.relpersistence,'rules',c.relhasrules,'rewrites',(select count(*) from pg_rewrite r where r.ev_class=c.oid)) order by n.nspname,c.relname),'[]'::jsonb) value from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.oid in(${tableList})`;
export const functionsQuery = `select n.nspname schema,p.proname name,pg_get_function_identity_arguments(p.oid) args,pg_get_function_arguments(p.oid) allargs,p.pronargdefaults defaults,pg_get_expr(p.proargdefaults,0) default_expression,pg_get_function_result(p.oid) result,pg_get_userbyid(p.proowner) owner,p.proacl::text acl,(select jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(a.grantor),'grantee',case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end,'privilege',a.privilege_type,'grantable',a.is_grantable) order by pg_get_userbyid(a.grantor),case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end,a.privilege_type) from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a) full_acl,p.proconfig config,p.prosecdef definer,l.lanname language,p.prokind kind,p.procost cost,p.prorows rows,p.proisstrict strict,p.proleakproof leakproof,p.proparallel parallel,p.provolatile volatility,p.prosupport::text support,p.provariadic::regtype::text variadic,p.proargmodes modes,md5(p.prosrc) body,md5(pg_get_functiondef(p.oid)) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where p.oid in(select t.tgfoid from pg_trigger t where t.tgrelid in(${tableList}) and not t.tgisinternal) or (n.nspname='auth' and p.proname='uid') or(n.nspname='private' and p.proname in('has_admin_role','lock_admin_user_mutation','require_active_admin_user')) or(n.nspname='public' and p.proname in(${names.map((n) => "'" + n + "'").join(",")})) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)`;
export const authQuery = `select jsonb_build_object('owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'serviceSelect',has_table_privilege('service_role',c.oid,'SELECT'),'serviceUpdate',has_table_privilege('service_role',c.oid,'UPDATE'),'serviceColumnSelect',has_any_column_privilege('service_role',c.oid,'SELECT'),'serviceColumnUpdate',has_any_column_privilege('service_role',c.oid,'UPDATE'),'postgresSelect',has_table_privilege('postgres',c.oid,'SELECT'),'postgresUpdate',has_table_privilege('postgres',c.oid,'UPDATE'),'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'acl',a.attacl::text,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'serviceSelect',has_column_privilege('service_role',c.oid,a.attnum,'SELECT'),'serviceUpdate',has_column_privilege('service_role',c.oid,a.attnum,'UPDATE'),'postgresSelect',has_column_privilege('postgres',c.oid,a.attnum,'SELECT'),'postgresUpdate',has_column_privilege('postgres',c.oid,a.attnum,'UPDATE')) order by a.attnum) from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)) value from pg_class c where c.oid='auth.users'::regclass`;
export const nativeQuery = `select coalesce(jsonb_agg(jsonb_build_object('constraint',c.conname,'own',c.conrelid::regclass::text,'referenced',c.confrelid::regclass::text,'type',t.tgtype,'function',t.tgfoid::regprocedure::text,'table',t.tgrelid::regclass::text,'other',t.tgconstrrelid::regclass::text,'index',t.tgconstrindid::regclass::text,'enabled',t.tgenabled,'internal',t.tgisinternal,'parent',t.tgparentid,'deferrable',t.tgdeferrable,'deferred',t.tginitdeferred,'nargs',t.tgnargs,'attr',t.tgattr::text,'args',encode(t.tgargs,'hex'),'qual',pg_get_expr(t.tgqual,t.tgrelid),'oldtable',t.tgoldtable,'newtable',t.tgnewtable,'dependencies',(select jsonb_agg(jsonb_build_object('class',d.classid::regclass::text,'subid',d.objsubid,'refclass',d.refclassid::regclass::text,'refconstraint',case when d.refclassid='pg_constraint'::regclass then(select q.conname from pg_constraint q where q.oid=d.refobjid) end,'sameconstraint',d.refobjid=c.oid,'refsubid',d.refobjsubid,'deptype',d.deptype) order by d.classid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid,d.deptype) from pg_depend d where d.classid='pg_trigger'::regclass and d.objid=t.oid)) order by c.conrelid::regclass::text,c.conname,t.tgtype,t.tgrelid::regclass::text),'[]'::jsonb) value from pg_constraint c join pg_trigger t on t.tgconstraint=c.oid where(c.conrelid in(${tableList}) or c.confrelid in(${tableList})) and c.contype='f'`;
export const indexDetailsQuery = `select coalesce(jsonb_agg(jsonb_build_object('table',i.indrelid::regclass::text,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'kind',c.relkind,'persistence',c.relpersistence,'options',c.reloptions,'access',am.amname,'definition',pg_get_indexdef(i.indexrelid),'nkeys',i.indnkeyatts,'natts',i.indnatts,'unique',i.indisunique,'nullsNotDistinct',i.indnullsnotdistinct,'primary',i.indisprimary,'exclusion',i.indisexclusion,'immediate',i.indimmediate,'clustered',i.indisclustered,'valid',i.indisvalid,'ready',i.indisready,'live',i.indislive,'replicaIdentity',i.indisreplident,'keys',i.indkey::text,'flags',i.indoption::text,'predicate',pg_get_expr(i.indpred,i.indrelid),'expressions',pg_get_expr(i.indexprs,i.indrelid)) order by i.indrelid::regclass::text,c.relname),'[]'::jsonb) value from pg_index i join pg_class c on c.oid=i.indexrelid join pg_am am on am.oid=c.relam where i.indrelid in(${tableList})`;
