import csv,io,pathlib
p=pathlib.Path('docs/evidence/audit-remediation-20260927/tracker.csv');text=p.read_text(encoding='utf-8');lines=text.splitlines(keepends=True);header=next(csv.reader([lines[0]]));indices=[i for i,l in enumerate(lines) if l.startswith('R01,')];assert len(indices)==1;i=indices[0];row=dict(zip(header,next(csv.reader([lines[i]]))))
row['implementation_status']='partial overall; Task2/Task3/Task4/Task5 accepted source; Task6 CRM source complete and verified in isolation pending controller independent review/exact-head CI; Task1 partial'
row['code_complete']='partial overall; Task6 three missing CRM commands, explicitly ruled own actor bridge/version-wrapper fence/consent identity guard and generic42501 HTTP403; task-6-source-binding.json separate DB executed map/finalHTTP gate map; Task1 ACL/actor gate remains'
row['schema_ready']='partial overall; accepted Tasks2-5 plus Task6 hosted isolated44->22 (Task1 excluded); Task6 SQL2applies/both49x55000; modern existing1 stays1; complete rows/catalog/Auth/default/native/ledger preserved; production44gaps/ledger112 unchanged; Task6 not applied'
row['deployed']='partial; focused #182 source accepted; Task6 no production apply/deployment'
row['operationally_enabled']='partial (#182 readonly ACL clamp enforced); wider compatibility/UAT open; Task6 no activation/new checkout/delivery/media schedules'
row['current_sha']='592bcebda2dc0154d20684a1a2240cfbdd8ae3d1 (Task6 execution parent; final source candidate tree a352da2693ccdbce16e649872997da6307e2cf4b; packaging commit contains task-6-source-binding.json)'
row['pr_commit']+='; current closure supersedes historical pending: Task5 original/Fix1 review Approved, draftPR189 exact592 CI36928397189 attempt1 allfiveSUCCESS; Task6 controller independent review/PR/exact-head CI pending'
row['test_evidence']+='; Task5 accepted closure: draftPR189/head592/CI36928397189 verify,a11y-verify,brand-verify,rls-matrix,performance-verify allcompletedSUCCESS, explicit dependency hold released. Task6 task-6-crm-atomic.md/source-binding.json: actual hosted missing3x42883 RED, modern bannedwrapper/staffcreate/bannedconsent/identity/[] RED; source-only own bridge/guard ruling; original7b8 wrong JSON-string profile hashes/42704 fixture/22P02 receipts retained and invalid49 preliminary refused cases qualified. FinalSQLb3ef1a69e4d92362611ede79ba775b5b28904e4acaff166550859e9b57844bc2 hosted+modern25pass205assert each, SQL2x/49x55000 after validbaseline/fullrelated-unrelated rows/catalog/Authallcolumns/default/nativeRI16/ledger/source preservation; roles-version/auditrollback/identity/retry/temp-shadow/real concurrent ban-disable-role and versionrace. HTTP actual3path500 RED->generic403 GREEN7pass20assert; unchanged DB-runtime fivefile importclosure excludes HTTP, actual22 observed DBinputs vs29 finalgates qualified. Final fourgates0:3235pass292skip0fail10499assert, lint52baselinewarnings; gate modern2a008->04dda fixturetransition/templatec653 unchanged; production finalreadonly22:21:39Z ledger112 threecommands/helper absent oldwrapper unchanged; no Task1/prod/deploy/enable'
row['owner_blocker']='controller Task6 independent spec/security/quality review/draftPR/exact-head CI; production/release/enablement approval; Task1 payment source ACL human approval and real actor RED; hosted/PostgREST/JWT/provider/Authinternal/fullcheckout/recovery UAT not-run; deferred Task2 photo-fixture/title Minor and Task4 M1 baseline52warnings retained; analogous Task2/3 nativeFK whole-branch review outsideTask6; M1 router/expected-error output noise deferred'
b=io.StringIO(newline='');w=csv.DictWriter(b,fieldnames=header,lineterminator='\n');w.writerow(row);lines[i]=b.getvalue();p.write_text(''.join(lines),encoding='utf-8',newline='\n')
for q in [pathlib.Path('.superpowers/sdd/r01-forward-schema-plan-20261001/task-6-report.md'),pathlib.Path('docs/evidence/audit-remediation-20260927/r01-forward/task-6-crm-atomic.md')]:q.write_text(q.read_text(encoding='utf-8').replace('--timeout30000','--timeout 30000'),encoding='utf-8',newline='\n')
print('Only current R01 row updated; reports exact timeout spacing corrected.')