import type { AdminLanguage } from "./adminI18n";
import { useAdminLanguage } from "./adminI18n";

export const adminPageCopy = {
  zh: {
    common: {
      refresh: "重新整理",
      clear: "清除",
      loading: "載入中...",
      rows: "列數",
      records: "筆紀錄",
      total: "總數",
      page: "頁",
      of: "共",
      previous: "上一頁",
      next: "下一頁",
      action: "操作",
      actions: "操作",
      open: "開啟",
      edit: "編輯",
      delete: "刪除",
      deleting: "刪除中",
      save: "儲存",
      saving: "儲存中",
      optional: "選填",
      noChannel: "沒有渠道",
      inactive: "停用",
      exporting: "匯出中...",
      export: "匯出",
      exportCsv: "匯出 CSV",
      supportersCsv: "支持者 CSV",
      donationsCsv: "捐款 CSV",
      downloadAgain: "再次下載",
      downloading: "下載中...",
      downloadFailed: "下載失敗",
      exportFailed: "匯出失敗",
      notSignedIn: "未登入",
      noContact: "沒有聯絡資料",
      searchMatches: (count: number) => `${formatAdminNumber(count, "zh")} 個結果`,
      totalCount: (count: number) => `${formatAdminNumber(count, "zh")} 筆`,
      totalRecords: (count: number) => `${formatAdminNumber(count, "zh")} 筆紀錄`,
      totalSupporters: (count: number) => `共 ${formatAdminNumber(count, "zh")} 位支持者`,
      scheduledOrCompleted: (count: number) => `${formatAdminNumber(count, "zh")} 個已排程或已完成`,
      pageOf: (page: number, totalPages: number) =>
        `第 ${formatAdminNumber(page, "zh")} 頁，共 ${formatAdminNumber(totalPages, "zh")} 頁`,
      rowsCount: (count: number) => `${formatAdminNumber(count, "zh")} 列`,
    },
    animalTypes: {
      all: "所有動物",
      cat: "貓",
      dog: "狗",
      sponsor: "助養動物",
      unknown: "未知",
    },
    priority: {
      all: "所有優先次序",
      low: "低",
      normal: "普通",
      high: "高",
      urgent: "緊急",
    },
    contactChannel: {
      phone: "電話",
      whatsapp: "WhatsApp",
      email: "電郵",
      in_person: "面談",
      internal: "內部",
    },
    identityModes: {
      new_supporter: "新支持者",
      existing_supporter: "現有支持者",
      existing_adopter: "現有領養人",
    },
    caseList: {
      title: "領養個案",
      subtitle: "協調員個案隊列、配對、跟進及完成領養。",
      searchLabel: "搜尋個案",
      searchPlaceholder: "搜尋申請人、電話或電郵",
      statusLabel: "按個案狀態篩選",
      statusPlaceholder: "個案狀態",
      allStatuses: "所有狀態",
      animalTypeLabel: "按動物類別篩選",
      animalTypePlaceholder: "動物類別",
      openOnly: "只顯示未完成",
      openOnlyLabel: "只顯示未完成個案",
      filterError: "無法載入狀態篩選",
      tableTitle: "個案",
      empty: "沒有找到個案",
      columns: {
        applicant: "申請人",
        animal: "申請動物",
        phone: "電話",
        created: "建立日期",
        status: "狀態",
      },
    },
    pledgeReview: {
      title: "承諾審核",
      detailTitle: "承諾詳情",
      close: "關閉",
      searchLabel: "搜尋支持者姓名、電郵或編號",
      searchPlaceholder: "搜尋支持者姓名、電郵或編號",
      statusFilterLabel: "狀態",
      statusFilterPlaceholder: "狀態",
      allStatuses: "全部狀態",
      perPage: "每頁",
      empty: "沒有承諾",
      totalCount: (count: number) => `共 ${formatAdminNumber(count, "zh")} 項`,
      columns: {
        supporter: "支持者",
        amount: "承諾金額",
        created: "建立日期",
        status: "狀態",
      },
      statuses: {
        pending_payment: "待付款",
        provisional: "待審核",
        active: "已確認",
        needs_followup: "需要跟進",
        cancelled: "已取消",
      },
      paymentMethods: {
        fps: "轉數快 FPS",
        bank_transfer: "銀行轉帳",
        payme: "PayMe",
        paypal: "PayPal",
        give_asia: "Give.asia",
      },
      proofReviewStatuses: {
        pending: "待審核",
        approved: "已通過",
        rejected: "已拒絕",
      },
      proofSources: {
        public: "支持者提交",
        staff: "職員記錄",
      },
      customTier: "自訂",
      createdOn: (date: string) => `建立於 ${date}`,
      preferencesTitle: "動物排序",
      errors: {
        review: "審核失敗",
        cancel: "取消失敗",
        recordPayment: "記錄付款失敗",
      },
      recordPayment: {
        title: "記錄付款",
        methodLabel: "付款方式",
        referenceLabel: "參考編號",
        amountLabel: "金額 (HKD)",
        dateLabel: "付款日期",
        noteLabel: "備註",
        proofLabel: "付款證明（選填）",
        save: "儲存付款記錄",
      },
      reviewProof: {
        title: "審核付款證明",
        noteLabel: "備註",
        approve: "核實通過",
        reject: "拒絕",
      },
      proofPreview: {
        noFile: "未附上檔案",
        load: "載入付款證明",
        loading: "載入付款證明中...",
        loadError: (message: string) => `無法載入付款證明：${message}`,
        open: (fileName: string) => `開啟付款證明（${fileName}）`,
      },
      cancel: {
        noteLabel: "取消備註",
        action: "取消助養",
      },
      proofHistory: {
        title: "付款證明記錄",
        current: "（目前）",
        file: (fileName: string) => `檔案：${fileName}`,
        note: (note: string) => `備註：${note}`,
      },
      recentActivity: "近期活動",
      viewSupporterTimeline: "查看完整支持者時間軸",
    },
    intakeInbox: {
      title: "申請收件箱",
      subtitle: "集中檢查公開領養申請、相片及探訪跟進。",
      openOnly: "只顯示未處理",
      openOnlyLabel: "只顯示未處理收件箱項目",
      loadError: "無法載入收件箱",
      empty: "沒有符合篩選的收件箱項目",
      allLanes: "全部",
      viewCase: "查看個案",
      noCase: "未連結個案",
      due: "到期",
      created: "建立",
      resolved: "已處理",
      photos: "相片",
      rankedAnimals: "動物偏好",
      visit: "探訪",
      applicant: "申請人",
      lanes: {
        new_adoption_application: "新公開申請",
        visit_followup: "探訪跟進",
        photos_to_review: "相片待審",
        needs_followup: "需要跟進",
      },
      urgency: {
        normal: "普通",
        high: "高",
        overdue: "逾期",
      },
    },
    manualIntake: {
      title: "手動建案",
      subtitle: "為電話、WhatsApp 或親身查詢建立領養個案。",
      createCase: "建立個案",
      creating: "建立中...",
      loadCaseStatusesError: "無法載入領養個案狀態",
      loadFollowupStatusesError: "無法載入跟進工作狀態",
      identity: "身份",
      identitySubtitle: "建立新捐款人紀錄前，先搜尋現有領養人或捐款人。",
      identitySearch: "搜尋姓名、電話、電郵或地址",
      identityPlaceholder: "輸入資料搜尋現有紀錄",
      createNewSupporter: "建立新捐款人",
      searchIdentitiesError: "無法搜尋身份",
      searchResults: "搜尋結果",
      searching: "搜尋中...",
      noIdentityMatched: "沒有現有身份符合搜尋。",
      currentIdentity: "目前身份",
      newSupporter: "新捐款人",
      existingIdentity: "現有身份",
      adopterProfile: "領養人檔案",
      supporter: "捐款人",
      blacklisted: "黑名單",
      fields: {
        supporterName: "捐款人姓名",
        supporterPhone: "捐款人電話",
        supporterEmail: "捐款人電郵",
        language: "語言",
        chinese: "繁體中文",
        english: "English",
        adopterEnglishName: "領養人英文名",
        adopterChineseName: "領養人中文名",
        adopterAddress: "領養人地址",
        householdSize: "家庭人數",
        caseDetails: "個案資料",
        caseDetailsSubtitle: "必填欄位會對應公開申請紀錄。",
        initialStatus: "初始狀態",
        animalType: "動物類別",
        applicantName: "申請人姓名",
        applicantPhone: "申請人電話",
        applicantEmail: "申請人電郵",
        requestedAnimalId: "申請動物 ID",
        optionalUuid: "選填 UUID",
        housingType: "住所類別",
        familySize: "家庭人數",
        applicantAddress: "申請人地址",
        existingPets: "現有寵物",
        reason: "申請原因",
        preferenceNotes: "偏好備註",
      },
      optionalTask: "選填工作",
      optionalTaskSubtitle: "建立個案時一併建立第一個協調員跟進工作。",
      createInitialTask: "建立初始跟進工作",
      taskStatus: "工作狀態",
      taskTitle: "工作標題",
      priority: "優先次序",
      dueAt: "到期時間",
      assignedTo: "負責人",
      volunteer: "義工",
      contactChannel: "聯絡渠道",
      taskType: "工作類型",
      remarks: "備註",
      review: "檢查",
      caseStatus: "個案狀態",
      applicant: "申請人",
      initialTask: "初始工作",
      clearAlert: "清除提示",
      noTask: "沒有工作",
      notSelected: "未選擇",
      applicantMissing: "未填寫申請人姓名",
      chooseStatus: "選擇狀態",
      validations: {
        identity: "請搜尋並選擇現有身份，或建立新捐款人。",
        supporterName: "請輸入新捐款人姓名。",
        supporterPhone: "請輸入新捐款人電話。",
        initialStatus: "請選擇初始個案狀態。",
        animalType: "請選擇動物類別。",
        applicantName: "請輸入申請人姓名。",
        applicantPhone: "請輸入申請人電話。",
        taskStatus: "請選擇跟進工作狀態。",
        taskTitle: "請輸入跟進工作標題。",
      },
    },
    taskCenter: {
      title: "協調員工作中心",
      subtitle: "查看、篩選及更新領養個案和動物的跟進工作。",
      searchLabel: "搜尋工作",
      searchPlaceholder: "搜尋標題、結果或備註",
      dueLabel: "按到期日篩選",
      priorityLabel: "按優先次序篩選",
      assignedToLabel: "按負責人篩選",
      assignedToPlaceholder: "負責人",
      openOnly: "只顯示未完成",
      openOnlyLabel: "只顯示未完成工作",
      summaryLabel: "目前頁面的工作摘要",
      loadTasksError: "無法載入協調員工作",
      loadStatusesError: "無法載入工作狀態",
      tasks: "工作",
      empty: "沒有符合篩選的協調員工作",
      dueOptions: {
        all: "所有到期日",
        overdue: "已逾期",
        today: "今天",
        upcoming: "即將到期",
        none: "沒有到期日",
      },
      summary: {
        overdue: "已逾期",
        today: "今天",
        upcoming: "即將到期",
        none: "沒有到期日",
        done: "已完成",
        urgent: "緊急",
      },
    },
    taskPanel: {
      defaultTitle: "跟進工作",
      noFollowups: "未有跟進紀錄",
      addStatusFirst: "請先建立一個啟用中的跟進狀態，才可新增工作。",
      createValidation: "新增工作前，請先填寫標題及跟進狀態。",
      chooseStatus: "選擇狀態",
      saveTask: "儲存工作",
      addTask: "新增工作",
      labels: {
        title: "標題",
        status: "狀態",
        priority: "優先次序",
        channel: "渠道",
        due: "到期",
        scheduled: "已排程",
        completed: "已完成",
        nextStep: "下一步",
        volunteer: "義工",
        outcome: "結果",
        remarks: "備註",
      },
      display: {
        due: "到期",
        scheduled: "已排程",
        completed: "已完成",
        nextStep: "下一步",
        volunteer: "義工",
        channel: "渠道",
        outcome: "結果",
        remarks: "備註",
      },
      placeholders: {
        title: "領養後電話跟進",
        optional: "選填",
        remarks: "選填協調員備註",
      },
    },
    adopters: {
      title: "領養人",
      subtitle: "領養人檔案、領養紀錄、黑名單狀態及跟進工作量。",
      exportCsv: "匯出 CSV",
      searchLabel: "搜尋領養人",
      searchPlaceholder: "搜尋姓名、電話或電郵",
      blacklistLabel: "按黑名單狀態篩選",
      blacklistPlaceholder: "黑名單狀態",
      openCases: "未完成個案",
      openCasesLabel: "顯示有未完成個案的領養人",
      openTasks: "未完成工作",
      openTasksLabel: "顯示有未完成工作的領養人",
      tableTitle: "領養人檔案",
      empty: "沒有找到領養人",
      blacklisted: "黑名單",
      clear: "正常",
      allBlacklistStates: "所有黑名單狀態",
      notBlacklisted: "非黑名單",
      latestCase: "最新個案",
      columns: {
        nameArea: "姓名及地區",
        contact: "聯絡",
        history: "紀錄",
        latestCase: "最新個案",
        action: "操作",
      },
      badges: {
        openCases: "未完成個案",
        adoptions: "宗領養",
        openTasks: "未完成工作",
        open: "未完成",
        adopted: "已領養",
        tasks: "工作",
      },
    },
    reports: {
      title: "協調員報表",
      subtitle: "每月接收個案摘要及重新產生 CSV 匯出紀錄。",
      loadSummaryError: "無法載入每月摘要",
      loadHistoryError: "無法載入匯出紀錄",
      month: "月份",
      kind: "種類",
      actor: "操作者",
      actorPlaceholder: "按使用者 ID 篩選",
      summaryLabel: "每月協調員摘要",
      exportHistory: "匯出紀錄",
      empty: "沒有符合篩選的匯出紀錄。",
      kindOptions: {
        all: "所有匯出",
        cases: "個案",
        adopters: "領養人",
        "successful-adoptions": "成功領養",
        animals: "動物",
        tasks: "工作",
      },
      metrics: {
        publicIntakeCases: "公開申請",
        manualIntakeCases: "手動建案",
        successfulAdoptions: "成功領養",
        openCases: "未完成個案",
        overdueTasks: "逾期工作",
        exportsRun: "已匯出",
      },
      columns: {
        timestamp: "時間",
        actor: "操作者",
        kind: "種類",
        rows: "列數",
        filters: "篩選",
        sourceRoute: "來源路由",
        action: "操作",
      },
    },
    statuses: {
      title: "協調員狀態",
      subtitle: (statuses: number, categories: number) =>
        `${formatAdminNumber(statuses, "zh")} 個狀態，分布於 ${formatAdminNumber(categories, "zh")} 個分類`,
      newStatus: "新增狀態",
      editStatus: "編輯狀態",
      systemKeyLocked: "系統 key 已鎖定",
      tableEmpty: "沒有狀態",
      loadError: "無法載入狀態",
      deleteConfirm: (zh: string, en: string) => `刪除 ${zh} / ${en}？`,
      noChanges: "沒有需要儲存的變更。",
      flags: {
        active: "啟用",
        inactive: "停用",
        closing: "結束",
        final: "最終",
        system: "系統",
      },
      columns: {
        label: "標籤",
        order: "排序",
        flags: "標記",
        category: "分類",
        actions: "操作",
      },
      fields: {
        category: "分類",
        key: "Key",
        chineseLabel: "中文標籤",
        englishLabel: "English label",
        sortOrder: "排序",
        color: "顏色",
        active: "啟用",
        closing: "結束",
        final: "最終",
        saveStatus: "儲存狀態",
      },
      categories: {
        adoption_case: { label: "領養個案", shortLabel: "個案" },
        animal_lifecycle: { label: "動物流程", shortLabel: "動物" },
        match: { label: "配對", shortLabel: "配對" },
        followup: { label: "跟進", shortLabel: "跟進" },
        final_outcome: { label: "結果", shortLabel: "結果" },
      },
      colors: {
        blue: "藍色",
        amber: "琥珀",
        cyan: "青色",
        purple: "紫色",
        indigo: "靛藍",
        green: "綠色",
        red: "紅色",
        slate: "灰藍",
        coral: "珊瑚",
      },
    },
    supporters: {
      title: "支持者",
      subtitle: "捐款人、義工、暫托及領養人紀錄、收據、同意狀態及手動捐款。",
      searchLabel: "搜尋支持者",
      searchPlaceholder: "搜尋姓名、電郵、電話、參考編號或收據",
      roleFilterLabel: "按身份篩選",
      allRoles: "所有身份",
      loadError: "無法載入支持者",
      empty: "沒有找到支持者",
      newSupporter: "新增支持者",
      editSupporter: "編輯支持者",
      saveSupporter: "儲存支持者",
      needsReview: "需要檢查",
      clear: "正常",
      lastGift: "最近捐款",
      receipts: "收據",
      consent: "同意狀態",
      email: "電郵",
      whatsapp: "WhatsApp",
      lifetime: "累計",
      roleLabels: {
        donor: "捐款人",
        adopter: "領養人",
        volunteer: "義工",
        foster: "暫托",
      },
      columns: {
        supporter: "支持者",
        roles: "身份",
        consent: "同意狀態",
        lifetime: "累計",
        lastGift: "最近捐款",
        receipts: "收據",
      },
      form: {
        name: "姓名",
        email: "電郵",
        phone: "電話",
        language: "語言",
        tags: "標籤",
        roles: "身份",
      },
    },
  },
  en: {
    common: {
      refresh: "Refresh",
      clear: "Clear",
      loading: "Loading...",
      rows: "Rows",
      records: "records",
      total: "total",
      page: "Page",
      of: "of",
      previous: "Previous",
      next: "Next",
      action: "Action",
      actions: "Actions",
      open: "Open",
      edit: "Edit",
      delete: "Delete",
      deleting: "Deleting",
      save: "Save",
      saving: "Saving",
      optional: "Optional",
      noChannel: "No channel",
      inactive: "inactive",
      exporting: "Exporting...",
      export: "Export",
      exportCsv: "Export CSV",
      supportersCsv: "Supporters CSV",
      donationsCsv: "Donations CSV",
      downloadAgain: "Download again",
      downloading: "Downloading...",
      downloadFailed: "Download failed",
      exportFailed: "Export failed",
      notSignedIn: "Not signed in",
      noContact: "No contact on file",
      searchMatches: (count: number) => `${formatAdminNumber(count, "en")} matches`,
      totalCount: (count: number) => `${formatAdminNumber(count, "en")} total`,
      totalRecords: (count: number) => `${formatAdminNumber(count, "en")} records`,
      totalSupporters: (count: number) => `${formatAdminNumber(count, "en")} total supporters`,
      scheduledOrCompleted: (count: number) =>
        `${formatAdminNumber(count, "en")} scheduled or completed`,
      pageOf: (page: number, totalPages: number) =>
        `Page ${formatAdminNumber(page, "en")} of ${formatAdminNumber(totalPages, "en")}`,
      rowsCount: (count: number) => `${formatAdminNumber(count, "en")} rows`,
    },
    animalTypes: {
      all: "All animals",
      cat: "Cats",
      dog: "Dogs",
      sponsor: "Sponsor animals",
      unknown: "Unknown",
    },
    priority: {
      all: "All priorities",
      low: "Low",
      normal: "Normal",
      high: "High",
      urgent: "Urgent",
    },
    contactChannel: {
      phone: "Phone",
      whatsapp: "WhatsApp",
      email: "Email",
      in_person: "In person",
      internal: "Internal",
    },
    identityModes: {
      new_supporter: "New supporter",
      existing_supporter: "Existing supporter",
      existing_adopter: "Existing adopter",
    },
    caseList: {
      title: "Adoption cases",
      subtitle: "Coordinator queue, matching, follow-up, and finalization.",
      searchLabel: "Search cases",
      searchPlaceholder: "Search applicant, phone, or email",
      statusLabel: "Filter by case status",
      statusPlaceholder: "Case status",
      allStatuses: "All statuses",
      animalTypeLabel: "Filter by animal type",
      animalTypePlaceholder: "Animal type",
      openOnly: "Open only",
      openOnlyLabel: "Show open cases only",
      filterError: "Could not load status filters",
      tableTitle: "Cases",
      empty: "No cases found",
      columns: {
        applicant: "Applicant",
        animal: "Requested animal",
        phone: "Phone",
        created: "Created",
        status: "Status",
      },
    },
    pledgeReview: {
      title: "Pledge review",
      detailTitle: "Pledge details",
      close: "Close",
      searchLabel: "Search supporter name, email, or reference",
      searchPlaceholder: "Search supporter name, email, or reference",
      statusFilterLabel: "Status",
      statusFilterPlaceholder: "Status",
      allStatuses: "All statuses",
      perPage: "Per page",
      empty: "No pledges found",
      totalCount: (count: number) => `${formatAdminNumber(count, "en")} total`,
      columns: {
        supporter: "Supporter",
        amount: "Pledge amount",
        created: "Created",
        status: "Status",
      },
      statuses: {
        pending_payment: "Pending payment",
        provisional: "Pending review",
        active: "Active",
        needs_followup: "Needs follow-up",
        cancelled: "Cancelled",
      },
      paymentMethods: {
        fps: "FPS",
        bank_transfer: "Bank transfer",
        payme: "PayMe",
        paypal: "PayPal",
        give_asia: "Give.asia",
      },
      proofReviewStatuses: {
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
      },
      proofSources: {
        public: "Submitted by supporter",
        staff: "Recorded by staff",
      },
      customTier: "Custom",
      createdOn: (date: string) => `Created ${date}`,
      preferencesTitle: "Animal ranking",
      errors: {
        review: "Review failed",
        cancel: "Cancellation failed",
        recordPayment: "Failed to record payment",
      },
      recordPayment: {
        title: "Record payment",
        methodLabel: "Payment method",
        referenceLabel: "Reference",
        amountLabel: "Amount (HKD)",
        dateLabel: "Payment date",
        noteLabel: "Note",
        proofLabel: "Payment proof (optional)",
        save: "Save payment record",
      },
      reviewProof: {
        title: "Review payment proof",
        noteLabel: "Note",
        approve: "Approve",
        reject: "Reject",
      },
      proofPreview: {
        noFile: "No file attached",
        load: "Load payment proof",
        loading: "Loading payment proof...",
        loadError: (message: string) => `Could not load payment proof: ${message}`,
        open: (fileName: string) => `Open payment proof (${fileName})`,
      },
      cancel: {
        noteLabel: "Cancellation note",
        action: "Cancel sponsorship",
      },
      proofHistory: {
        title: "Payment proof history",
        current: "(current)",
        file: (fileName: string) => `File: ${fileName}`,
        note: (note: string) => `Note: ${note}`,
      },
      recentActivity: "Recent activity",
      viewSupporterTimeline: "View full supporter timeline",
    },
    intakeInbox: {
      title: "Application inbox",
      subtitle: "Review public adoption applications, photos, and visit follow-ups.",
      openOnly: "Open only",
      openOnlyLabel: "Show unresolved inbox items only",
      loadError: "Could not load inbox",
      empty: "No inbox items match these filters",
      allLanes: "All",
      viewCase: "View case",
      noCase: "No case linked",
      due: "Due",
      created: "Created",
      resolved: "Resolved",
      photos: "Photos",
      rankedAnimals: "Animal preferences",
      visit: "Visit",
      applicant: "Applicant",
      lanes: {
        new_adoption_application: "New public application",
        visit_followup: "Visit follow-up",
        photos_to_review: "Photos to review",
        needs_followup: "Needs follow-up",
      },
      urgency: {
        normal: "Normal",
        high: "High",
        overdue: "Overdue",
      },
    },
    manualIntake: {
      title: "Manual case intake",
      subtitle: "Create adoption cases from phone, WhatsApp, or walk-in requests.",
      createCase: "Create case",
      creating: "Creating...",
      loadCaseStatusesError: "Could not load adoption case statuses",
      loadFollowupStatusesError: "Could not load follow-up task statuses",
      identity: "Identity",
      identitySubtitle:
        "Search existing adopters or supporters before creating a new supporter record.",
      identitySearch: "Search name, phone, email, or address",
      identityPlaceholder: "Type to search existing records",
      createNewSupporter: "Create new supporter",
      searchIdentitiesError: "Could not search identities",
      searchResults: "Search results",
      searching: "Searching...",
      noIdentityMatched: "No existing identity matched this search.",
      currentIdentity: "Current identity",
      newSupporter: "New supporter",
      existingIdentity: "Existing identity",
      adopterProfile: "Adopter profile",
      supporter: "Supporter",
      blacklisted: "Blacklisted",
      fields: {
        supporterName: "Supporter name",
        supporterPhone: "Supporter phone",
        supporterEmail: "Supporter email",
        language: "Language",
        chinese: "繁體中文",
        english: "English",
        adopterEnglishName: "Adopter English name",
        adopterChineseName: "Adopter Chinese name",
        adopterAddress: "Adopter address",
        householdSize: "Household size",
        caseDetails: "Case details",
        caseDetailsSubtitle: "Required fields mirror the public application record.",
        initialStatus: "Initial status",
        animalType: "Animal type",
        applicantName: "Applicant name",
        applicantPhone: "Applicant phone",
        applicantEmail: "Applicant email",
        requestedAnimalId: "Requested animal ID",
        optionalUuid: "Optional UUID",
        housingType: "Housing type",
        familySize: "Family size",
        applicantAddress: "Applicant address",
        existingPets: "Existing pets",
        reason: "Reason",
        preferenceNotes: "Preference notes",
      },
      optionalTask: "Optional task",
      optionalTaskSubtitle: "Create the first coordinator follow-up together with the case.",
      createInitialTask: "Create initial follow-up task",
      taskStatus: "Task status",
      taskTitle: "Task title",
      priority: "Priority",
      dueAt: "Due at",
      assignedTo: "Assigned to",
      volunteer: "Volunteer",
      contactChannel: "Contact channel",
      taskType: "Task type",
      remarks: "Remarks",
      review: "Review",
      caseStatus: "Case status",
      applicant: "Applicant",
      initialTask: "Initial task",
      clearAlert: "Clear alert",
      noTask: "No task",
      notSelected: "Not selected",
      applicantMissing: "Applicant name missing",
      chooseStatus: "Choose status",
      validations: {
        identity: "Search and select an existing identity, or create a new supporter.",
        supporterName: "Enter the new supporter's name.",
        supporterPhone: "Enter the new supporter's phone number.",
        initialStatus: "Choose an initial case status.",
        animalType: "Choose an animal type.",
        applicantName: "Enter the applicant name.",
        applicantPhone: "Enter the applicant phone number.",
        taskStatus: "Choose a follow-up task status.",
        taskTitle: "Enter the follow-up task title.",
      },
    },
    taskCenter: {
      title: "Coordinator task center",
      subtitle: "View, filter, and update follow-up work across adoption cases and animals.",
      searchLabel: "Search tasks",
      searchPlaceholder: "Search title, outcome, or remarks",
      dueLabel: "Filter by due date",
      priorityLabel: "Filter by priority",
      assignedToLabel: "Filter by assignee",
      assignedToPlaceholder: "Assigned to",
      openOnly: "Open only",
      openOnlyLabel: "Show open tasks only",
      summaryLabel: "Current page task summary",
      loadTasksError: "Could not load coordinator tasks",
      loadStatusesError: "Could not load task statuses",
      tasks: "Tasks",
      empty: "No coordinator tasks match these filters",
      dueOptions: {
        all: "All due dates",
        overdue: "Overdue",
        today: "Today",
        upcoming: "Upcoming",
        none: "No due date",
      },
      summary: {
        overdue: "Overdue",
        today: "Today",
        upcoming: "Upcoming",
        none: "No due date",
        done: "Done",
        urgent: "Urgent",
      },
    },
    taskPanel: {
      defaultTitle: "Follow-ups",
      noFollowups: "No follow-ups recorded",
      addStatusFirst: "Create an active follow-up status before adding tasks.",
      createValidation: "Add a title and follow-up status before creating a task.",
      chooseStatus: "Choose status",
      saveTask: "Save task",
      addTask: "Add task",
      labels: {
        title: "Title",
        status: "Status",
        priority: "Priority",
        channel: "Channel",
        due: "Due",
        scheduled: "Scheduled",
        completed: "Completed",
        nextStep: "Next step",
        volunteer: "Volunteer",
        outcome: "Outcome",
        remarks: "Remarks",
      },
      display: {
        due: "Due",
        scheduled: "Scheduled",
        completed: "Completed",
        nextStep: "Next step",
        volunteer: "Volunteer",
        channel: "Channel",
        outcome: "Outcome",
        remarks: "Remarks",
      },
      placeholders: {
        title: "Post-adoption call",
        optional: "Optional",
        remarks: "Optional coordinator note",
      },
    },
    adopters: {
      title: "Adopters",
      subtitle: "Profiles, adoption history, blacklist status, and follow-up workload.",
      exportCsv: "Export CSV",
      searchLabel: "Search adopters",
      searchPlaceholder: "Search name, phone, or email",
      blacklistLabel: "Filter by blacklist status",
      blacklistPlaceholder: "Blacklist status",
      openCases: "Open cases",
      openCasesLabel: "Show adopters with open cases",
      openTasks: "Open tasks",
      openTasksLabel: "Show adopters with open tasks",
      tableTitle: "Adopter profiles",
      empty: "No adopters found",
      blacklisted: "Blacklisted",
      clear: "Clear",
      allBlacklistStates: "All blacklist states",
      notBlacklisted: "Not blacklisted",
      latestCase: "Latest case",
      columns: {
        nameArea: "Name and area",
        contact: "Contact",
        history: "History",
        latestCase: "Latest case",
        action: "Action",
      },
      badges: {
        openCases: "open cases",
        adoptions: "adoptions",
        openTasks: "open tasks",
        open: "open",
        adopted: "adopted",
        tasks: "tasks",
      },
    },
    reports: {
      title: "Coordinator reports",
      subtitle: "Monthly intake summary and regenerated CSV export history.",
      loadSummaryError: "Could not load monthly summary",
      loadHistoryError: "Could not load export history",
      month: "Month",
      kind: "Kind",
      actor: "Actor",
      actorPlaceholder: "Filter by actor user ID",
      summaryLabel: "Monthly coordinator summary",
      exportHistory: "Export history",
      empty: "No exports match these filters.",
      kindOptions: {
        all: "All exports",
        cases: "Cases",
        adopters: "Adopters",
        "successful-adoptions": "Successful adoptions",
        animals: "Animals",
        tasks: "Tasks",
      },
      metrics: {
        publicIntakeCases: "Public intake",
        manualIntakeCases: "Manual intake",
        successfulAdoptions: "Successful",
        openCases: "Open cases",
        overdueTasks: "Overdue tasks",
        exportsRun: "Exports run",
      },
      columns: {
        timestamp: "Timestamp",
        actor: "Actor",
        kind: "Kind",
        rows: "Rows",
        filters: "Filters",
        sourceRoute: "Source route",
        action: "Action",
      },
    },
    statuses: {
      title: "Coordinator statuses",
      subtitle: (statuses: number, categories: number) =>
        `${formatAdminNumber(statuses, "en")} statuses across ${formatAdminNumber(categories, "en")} categories`,
      newStatus: "New status",
      editStatus: "Edit status",
      systemKeyLocked: "System key locked",
      tableEmpty: "No statuses",
      loadError: "Could not load statuses",
      deleteConfirm: (zh: string, en: string) => `Delete ${zh} / ${en}?`,
      noChanges: "No changes to save.",
      flags: {
        active: "Active",
        inactive: "Inactive",
        closing: "Closing",
        final: "Final",
        system: "System",
      },
      columns: {
        label: "Label",
        order: "Order",
        flags: "Flags",
        category: "Category",
        actions: "Actions",
      },
      fields: {
        category: "Category",
        key: "Key",
        chineseLabel: "Chinese label",
        englishLabel: "English label",
        sortOrder: "Sort order",
        color: "Color",
        active: "Active",
        closing: "Closing",
        final: "Final",
        saveStatus: "Save status",
      },
      categories: {
        adoption_case: { label: "Adoption case", shortLabel: "Case" },
        animal_lifecycle: { label: "Animal lifecycle", shortLabel: "Animal" },
        match: { label: "Match", shortLabel: "Match" },
        followup: { label: "Follow-up", shortLabel: "Follow-up" },
        final_outcome: { label: "Outcome", shortLabel: "Outcome" },
      },
      colors: {
        blue: "Blue",
        amber: "Amber",
        cyan: "Cyan",
        purple: "Purple",
        indigo: "Indigo",
        green: "Green",
        red: "Red",
        slate: "Slate",
        coral: "Coral",
      },
    },
    supporters: {
      title: "Supporters",
      subtitle: "Donor records, receipts, consent, and manual gifts.",
      searchLabel: "Search supporters",
      searchPlaceholder: "Search name, email, phone, reference, or receipt",
      roleFilterLabel: "Filter by role",
      allRoles: "All roles",
      loadError: "Could not load supporters",
      empty: "No supporters found",
      newSupporter: "New supporter",
      editSupporter: "Edit supporter",
      saveSupporter: "Save supporter",
      needsReview: "Needs review",
      clear: "Clear",
      lastGift: "Last gift",
      receipts: "Receipts",
      consent: "Consent",
      email: "Email",
      whatsapp: "WhatsApp",
      lifetime: "Lifetime",
      roleLabels: {
        donor: "Donor",
        adopter: "Adopter",
        volunteer: "Volunteer",
        foster: "Foster",
      },
      columns: {
        supporter: "Supporter",
        roles: "Roles",
        consent: "Consent",
        lifetime: "Lifetime",
        lastGift: "Last gift",
        receipts: "Receipts",
      },
      form: {
        name: "Name",
        email: "Email",
        phone: "Phone",
        language: "Language",
        tags: "Tags",
        roles: "Roles",
      },
    },
  },
} as const;

export function useAdminPageCopy() {
  const { language } = useAdminLanguage();
  return { language, pageCopy: adminPageCopy[language] };
}

export function formatAdminNumber(value: number | null | undefined, language: AdminLanguage) {
  return (value ?? 0).toLocaleString(language === "zh" ? "zh-HK" : "en-US");
}

export function formatAdminDateTime(value: string | null | undefined, language: AdminLanguage) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return new Intl.DateTimeFormat(language === "zh" ? "zh-HK" : "en-HK", {
    dateStyle: "medium",
    timeStyle: "short",
    hour12: false,
    timeZone: "Asia/Hong_Kong",
  }).format(date);
}

export function statusDisplayName(
  status: { labelZh?: string | null; labelEn?: string | null; key?: string },
  language: AdminLanguage,
) {
  const primary = language === "zh" ? status.labelZh : status.labelEn;
  const fallback = language === "zh" ? status.labelEn : status.labelZh;
  return primary || fallback || status.key || "-";
}

export function bilingualStatusName(
  status: { labelZh?: string | null; labelEn?: string | null; key?: string },
  language: AdminLanguage,
) {
  const primary = statusDisplayName(status, language);
  const secondary = language === "zh" ? status.labelEn : status.labelZh;
  if (!secondary || secondary === primary) return primary;
  return `${primary} / ${secondary}`;
}
