import { defineAdminCopy } from "./i18n/copy";

/**
 * Copy for the animal form and its photo gallery editor. The labels the form shares with the
 * animal list (types, genders, statuses, the Chinese and English field names) are in
 * `i18n/adminCommonCopy.ts`.
 */
export const animalFormCopy = defineAdminCopy({
  zh: {
    leaveConfirm: "離開會捨棄未儲存的內容，確定離開？",
    draft: {
      loading: "正在載入已儲存草稿…",
      loadFailed: "未能載入已儲存草稿，請重試後編輯。",
      reload: "重新載入草稿",
      loadError: "未能載入已儲存草稿。",
      saved: "草稿已儲存。請在發布前先預覽；公開資料尚未改動。",
    },
    versions: {
      heading: "已發布版本",
      duplicate: (revision: number) => `版本 ${revision} · 複製為草稿`,
      copied: "已複製版本為新草稿，請檢查及重新預覽。",
      copyFailed: "未能複製版本。",
    },
    profileRejected: (...labels: string[]) =>
      `以下欄位不符合公開資料規則（不可包含網址、電郵、電話或 < > 符號）：${labels.join("、")}`,
    galleryUploadFailed: "相片集上載失敗。",
    publication: {
      label: "公開狀態",
      draft: "草稿（未曾公開）",
      published: "已公開",
      unpublished: "暫停公開",
      hint: "與上方的狀態（可領養／已領養／寄養中）獨立。暫停公開不會更改動物的照顧記錄。",
    },
    listing: {
      label: "刊登範圍",
      adoption: "可供領養（顯示於領養頁面）",
      sponsorship: "可供助養（顯示於助養區）",
    },
    profile: {
      heading: "公開資料",
      intro: "這些內容會直接在公開網站顯示。請勿填寫網址、電郵、電話或個人聯絡資料。",
      code: "編號",
      codePlaceholder: "例如 C3761",
      birthday: "出生日期",
      birthdayHint: "填寫後，公開頁面會以此推算年齡。",
      neutered: "絕育狀態",
      notRecorded: "未有記錄",
      neuteredYes: "已絕育",
      neuteredNo: "未絕育",
      suitability: "適合的領養者",
      suitabilityNewbie: "適合新手",
      suitabilityExperienced: "適合有經驗者",
      recordDate: "記錄日期",
      personality: "性格（最多 1000 字）",
      health: "照顧與健康需要（最多 2000 字）",
      healthHint: "申請人在提交申請前需要知道的照顧需要，請在此說明。",
      sponsorUse: "助養用途（經批准後公開）",
      recentProgress: "近況（經批准後公開）",
      story: "牠的故事（最多 8000 字）",
    },
    upload: {
      checkHeading: "上載前核對檔案 → 動物",
      newAnimalDraft: "新動物草稿",
      mainPhoto: (fileName: string) => `${fileName} → 主相片`,
      galleryPhoto: (fileName: string) => `${fileName} → 相片集`,
      hint: "先儲存草稿及預覽；只有已批准的相片在發布完成後公開。",
    },
    publish: {
      heading: "預覽及發布",
      dirty: "內容已變更，請先儲存，再重新預覽。",
      previewLabel: "已儲存版本預覽",
      savedVersion: (revision: number) => `已儲存版本 ${revision}`,
      profileLine: (label: string, value: string) => `${label}：${value}`,
      notApprovedSuffix: "（未核准，不會公開）",
      createPreview: "建立發布預覽",
      previewCreated: "預覽已建立；如再儲存草稿，必須重新預覽。",
      previewFailed: "未能建立預覽。",
      reason: "發布原因",
      publishVersion: "發布此版本",
      mediaPending: "動物資料已發布，圖片仍在處理中；請稍後重新整理。",
      conflict: "草稿已變更或發布失敗，請重新預覽。",
      unconfirmed: "未能確認發布結果。請重試發布；不會建立重複版本。",
    },
    gallery: {
      legend: "相片集及審核資料",
      hint: "只有已批准並已發布的相片會公開。請設定排序、焦點、雙語替代文字及來源。",
      addLabel: "新增相片集相片",
      photoNumber: (number: number) => `相片 ${number}`,
      moveUp: "上移",
      moveDown: "下移",
      remove: "移除",
      altZh: "中文替代文字",
      altEn: "英文替代文字",
      source: "相片來源",
      focalX: (percent: number) => `水平焦點 ${percent}%`,
      focalY: (percent: number) => `垂直焦點 ${percent}%`,
      reviewStatus: "審核狀態",
      pending: "待審核",
      approved: "已批准",
      rejected: "不採用",
    },
  },
  en: {
    leaveConfirm: "Leaving will discard your unsaved changes. Leave this page?",
    draft: {
      loading: "Loading the saved draft...",
      loadFailed: "Could not load the saved draft. Reload it before editing.",
      reload: "Reload draft",
      loadError: "Could not load the saved draft. Reload the page and try again.",
      saved: "Draft saved. Preview it before publishing; the public information has not changed.",
    },
    versions: {
      heading: "Published versions",
      duplicate: (revision: number) => `Version ${revision} · Duplicate as draft`,
      copied: "The version was duplicated as a new draft. Check it and preview it again.",
      copyFailed: "Could not duplicate the version. Try again.",
    },
    profileRejected: (...labels: string[]) =>
      `These fields break the public information rules (no web addresses, email addresses, phone numbers or < > symbols): ${labels.join(", ")}. Remove the rejected text and save again.`,
    galleryUploadFailed: "Could not upload the gallery photos. Try again.",
    publication: {
      label: "Publication status",
      draft: "Draft (never published)",
      published: "Published",
      unpublished: "Unpublished",
      hint: "Independent of the status above (available, adopted or fostered). Unpublishing does not change the animal's care record.",
    },
    listing: {
      label: "Listed on",
      adoption: "Available for adoption (shown on the adoption page)",
      sponsorship: "Available for sponsorship (shown in the sponsorship area)",
    },
    profile: {
      heading: "Public information",
      intro:
        "This text is shown on the public website as written. Do not enter web addresses, email addresses, phone numbers or personal contact details.",
      code: "Reference number",
      codePlaceholder: "e.g. C3761",
      birthday: "Date of birth",
      birthdayHint: "If you fill this in, the public page works out the age from it.",
      neutered: "Neutered status",
      notRecorded: "Not recorded",
      neuteredYes: "Neutered",
      neuteredNo: "Not neutered",
      suitability: "Suitable adopter",
      suitabilityNewbie: "Suits first-time adopters",
      suitabilityExperienced: "Suits experienced adopters",
      recordDate: "Record date",
      personality: "Personality (up to 1,000 characters)",
      health: "Care and health needs (up to 2,000 characters)",
      healthHint: "Describe here the care needs an applicant must know before applying.",
      sponsorUse: "Sponsorship use (public once approved)",
      recentProgress: "Recent progress (public once approved)",
      story: "Story (up to 8,000 characters)",
    },
    upload: {
      checkHeading: "Check the files before uploading → animal",
      newAnimalDraft: "New animal draft",
      mainPhoto: (fileName: string) => `${fileName} → main photo`,
      galleryPhoto: (fileName: string) => `${fileName} → gallery`,
      hint: "Save the draft and preview it first. Only approved photos become public after publishing.",
    },
    publish: {
      heading: "Preview and publish",
      dirty: "The content has changed. Save it, then preview again.",
      previewLabel: "Saved version preview",
      savedVersion: (revision: number) => `Saved version ${revision}`,
      profileLine: (label: string, value: string) => `${label}: ${value}`,
      notApprovedSuffix: " (not approved, so it will not be public)",
      createPreview: "Create publish preview",
      previewCreated: "Preview created. If you save the draft again, preview it again.",
      previewFailed: "Could not create the preview. Try again.",
      reason: "Reason for publishing",
      publishVersion: "Publish this version",
      mediaPending:
        "The animal was published but its images are still processing. Refresh in a few minutes.",
      conflict: "The draft has changed or publishing failed. Preview the draft again.",
      unconfirmed:
        "Could not confirm the publish result. Publish again; this will not create a duplicate version.",
    },
    gallery: {
      legend: "Photo gallery and review details",
      hint: "Only approved, published photos are shown to the public. Set the order, focal point, alt text in both languages and the source.",
      addLabel: "Add gallery photos",
      photoNumber: (number: number) => `Photo ${number}`,
      moveUp: "Move up",
      moveDown: "Move down",
      remove: "Remove",
      altZh: "Chinese alt text",
      altEn: "English alt text",
      source: "Photo source",
      focalX: (percent: number) => `Horizontal focal point ${percent}%`,
      focalY: (percent: number) => `Vertical focal point ${percent}%`,
      reviewStatus: "Review status",
      pending: "Pending review",
      approved: "Approved",
      rejected: "Not used",
    },
  },
});
