import { defineAdminCopy } from "../i18n/copy";

/**
 * Copy for the documents list (`DocumentManagement`), the annual reports list
 * (`AnnualReportManagement`) and the text of the errors that `documentUpload` and the two
 * screens throw (`DocumentAdminError`).
 */
export const documentsCopy = defineAdminCopy({
  zh: {
    eyebrow: "宣傳內容",
    /** The kind of a document asset. */
    kinds: {
      annual_report: "年度報告",
      wedding_form: "婚宴回禮表格",
      adoption_guide: "領養指南",
      sponsorship_terms: "助養條款",
    },
    /** The language of a document asset. */
    languages: {
      "zh-HK": "中文",
      en: "English",
      bilingual: "中英雙語",
    },
    /** The message of each error the document code throws, by its code. */
    errors: {
      not_pdf: "請選擇 PDF 檔案",
      too_large: "PDF 檔案不可超過 50 MiB",
      title_and_file_required: "請填寫標題並選擇 PDF 檔案",
      report_fields_required: "請填寫標題、年度並選擇 PDF",
      release_required: "請先選擇領養後指南",
    },
    documents: {
      title: "文件",
      intro: "管理公開 PDF、語言版本與發佈狀態。",
      upload: {
        title: "標題",
        kind: "類型",
        language: "語言",
        file: "PDF 檔案",
        submit: "上載",
      },
      filters: {
        searchLabel: "搜尋文件",
        searchPlaceholder: "搜尋標題或檔案路徑",
        kindLabel: "文件類型",
        allKinds: "全部類型",
        languageLabel: "文件語言",
        allLanguages: "全部語言",
      },
      table: {
        document: "文件",
        kindAndLanguage: "類型 / 語言",
        size: "大小",
        status: "狀態",
        actions: "操作",
        loading: "載入中...",
        empty: "沒有文件",
        managedByReleases: "由領養指南版本管理",
        published: "已發佈",
        notPublished: "未發佈",
        publish: "發佈",
        unpublish: "取消發佈",
        deleteLabel: (title: string) => `刪除 ${title}`,
        confirmDelete: (title: string) => `確定刪除「${title}」？此操作無法復原。`,
        pager: "文件",
      },
    },
    annualReports: {
      title: "年度報告",
      intro: "安排公開報告年度、次序及發佈狀態。",
      form: {
        title: "標題",
        year: "年度",
        yearPlaceholder: "2025/26",
        pdf: "PDF",
        choose: "選擇文件",
        assetOption: (title: string, published: boolean) =>
          `${title} · ${published ? "已發佈" : "草稿"}`,
        order: "次序",
        submit: "新增",
      },
      table: {
        report: "報告",
        pdf: "PDF",
        order: "次序",
        status: "狀態",
        actions: "操作",
        loading: "載入中...",
        empty: "尚未建立年度報告",
        publishPdfFirst: "請先發佈 PDF",
        orderLabel: (title: string) => `${title} 次序`,
        published: "已發佈",
        draft: "草稿",
        publish: "發佈",
        unpublish: "取消發佈",
        deleteLabel: (title: string) => `刪除 ${title}`,
        confirmDelete: (title: string) => `確定刪除「${title}」？此操作無法復原。`,
      },
    },
  },
  en: {
    eyebrow: "Website content",
    kinds: {
      annual_report: "Annual report",
      wedding_form: "Wedding favour form",
      adoption_guide: "Adoption guide",
      sponsorship_terms: "Sponsorship terms",
    },
    languages: {
      "zh-HK": "Chinese",
      en: "English",
      bilingual: "Chinese and English",
    },
    errors: {
      not_pdf: "Choose a PDF file.",
      too_large: "The PDF must be 50 MiB or smaller. Choose a smaller file.",
      title_and_file_required: "Enter a title and choose a PDF file.",
      report_fields_required: "Enter a title and a year, then choose a PDF.",
      release_required: "Choose a post-adoption guide first.",
    },
    documents: {
      title: "Documents",
      intro: "Manage public PDFs, language versions and publication status.",
      upload: {
        title: "Title",
        kind: "Type",
        language: "Language",
        file: "PDF file",
        submit: "Upload",
      },
      filters: {
        searchLabel: "Search documents",
        searchPlaceholder: "Search by title or file path",
        kindLabel: "Document type",
        allKinds: "All types",
        languageLabel: "Document language",
        allLanguages: "All languages",
      },
      table: {
        document: "Document",
        kindAndLanguage: "Type / language",
        size: "Size",
        status: "Status",
        actions: "Actions",
        loading: "Loading...",
        empty: "No documents",
        managedByReleases: "Managed in adoption guide releases",
        published: "Published",
        notPublished: "Not published",
        publish: "Publish",
        unpublish: "Unpublish",
        deleteLabel: (title: string) => `Delete ${title}`,
        confirmDelete: (title: string) => `Delete "${title}"? This cannot be undone.`,
        pager: "Documents",
      },
    },
    annualReports: {
      title: "Annual reports",
      intro: "Set the year, order and publication status of the public reports.",
      form: {
        title: "Title",
        year: "Year",
        yearPlaceholder: "2025/26",
        pdf: "PDF",
        choose: "Choose a document",
        assetOption: (title: string, published: boolean) =>
          `${title} · ${published ? "Published" : "Draft"}`,
        order: "Sort order",
        submit: "Add",
      },
      table: {
        report: "Report",
        pdf: "PDF",
        order: "Sort order",
        status: "Status",
        actions: "Actions",
        loading: "Loading...",
        empty: "No annual reports yet",
        publishPdfFirst: "Publish the PDF first",
        orderLabel: (title: string) => `${title} sort order`,
        published: "Published",
        draft: "Draft",
        publish: "Publish",
        unpublish: "Unpublish",
        deleteLabel: (title: string) => `Delete ${title}`,
        confirmDelete: (title: string) => `Delete "${title}"? This cannot be undone.`,
      },
    },
  },
});
