import { defineAdminCopy } from "../i18n/copy";
import { formatAdminNumber, pluralCount } from "../i18n/format";

/**
 * Copy for the content editor (`ContentEditor`): the page, its forms, the story wall settings, the
 * story updates, the media and the linked records. The timeline, the social copy, the
 * notification drafts, the record picker and the revision panel are in `editorPanelsCopy`; the
 * content types, statuses, update kinds and the text of the logic modules' errors are in
 * `contentCommonCopy`.
 */

/** The English name of each field a publish check can name (see `lib/content/rules.ts`). */
const PUBLISH_FIELD_NAMES: Record<string, string> = {
  publicMapLabel: "Map label",
  publicLat: "Public latitude",
  publicLng: "Public longitude",
  title: "Title",
  slug: "Slug",
  summary: "Summary",
  coverMediaId: "Cover image",
  storyProfile: "Story wall settings",
  animalType: "Animal",
  publicStatus: "Public status",
  rescueRegion: "Rescue region",
};

export const editorCopy = defineAdminCopy({
  zh: {
    back: "返回宣傳內容",
    loading: "載入宣傳內容...",
    notFound: "找不到宣傳內容。",
    refresh: "重新整理",
    publish: "發布",
    archive: "封存",
    archiveConfirm: (title: string) => `確定封存「${title}」？封存後將不再於公開頁面顯示。`,
    leaveConfirm: "離開會捨棄未儲存的內容，確定離開？",
    reloadConfirm: "重新載入會捨棄所有未儲存內容，確定繼續？",
    reloadFailed: "未能重新載入，未儲存內容已保留，請重試。",
    unsaved: "尚有未儲存變更，請先儲存各面板後發布。",
    saved: (version: number | undefined) => `已儲存草稿 · 版本 ${version ?? "—"}`,
    conflict: {
      message:
        "內容已有較新版本或發布網址衝突。你的輸入已保留，請比較最新內容；重新載入前請先複製要保留的文字。",
      compare: "比較最新內容",
      reload: "重新載入最新版本",
      latest: (version: number | undefined) =>
        `伺服器最新版本 ${version ?? ""}（本機輸入保留於下方）`,
    },
    history: {
      label: "內容歷史分頁",
      previous: "上一頁紀錄",
      page: (page: number) => `紀錄第 ${page} 頁 · 每類最多 20 筆`,
      next: "下一頁紀錄",
    },
    syncingMedia: (count: number) => `內容已發布，${count} 張圖片正在同步；系統會自動重試。`,
    publishIssues: {
      heading: "發布前需要修正",
      /** A publish check names a field; Chinese shows the field as the server named it. */
      field: (field: string) => field,
    },
    draftNotice: {
      created: (count: number) => `已建立 ${count} 份通知草稿`,
    },
    metadata: {
      heading: "發布資格與來源",
      intro:
        "既有未分類內容維持可讀並列入待審。標記為示範或設定生效日期會立即影響公開位置；請先核對批准清單。",
      classification: "內容分類",
      classes: {
        unreviewed: "待核實",
        verified: "已核實",
        demo: "示範（不公開）",
      },
      source: "資料來源／批准記錄",
      owner: "內容負責人",
      effectiveFrom: "生效時間",
      effectiveUntil: "結束時間",
      save: "儲存發布資格",
    },
    form: {
      heading: "基本內容",
      intro: "標題、摘要、SEO 與 CTA 設定。",
      save: "儲存草稿",
      saving: "儲存中",
      title: "標題",
      slug: "Slug",
      type: "類型",
      subtitle: "副標題",
      summary: "摘要",
      body: "內文",
      ctaLabel: "CTA 文字",
      ctaUrl: "CTA 連結",
      seoTitle: "SEO 標題",
      seoDescription: "SEO 描述",
      ogTitle: "OG 標題",
      ogDescription: "OG 描述",
    },
    links: {
      heading: "關聯紀錄",
      type: "類型",
      record: "關聯紀錄",
      relationship: "關係",
      add: "新增關聯紀錄",
      empty: "未連結任何紀錄。",
      types: {
        animal: "動物",
        adoption_case: "領養申請",
        successful_adoption: "成功領養",
        supporter: "支持者",
        volunteer_activity: "義工活動",
      },
      relationships: {
        primary_subject: "主要主角",
        related_case: "相關個案",
        adopter: "領養人",
        volunteer_context: "義工背景",
        other: "其他",
      },
    },
    wall: {
      heading: "故事牆設定",
      notNeeded: "只有救援故事需要故事牆設定。",
      animal: "動物",
      publicStatus: "公開狀態",
      region: "救援地區",
      date: "救援日期",
      mapLabel: "地圖標籤",
      latitude: "公開緯度",
      longitude: "公開經度",
      address: "內部地址",
      notes: "內部位置備註",
      showOnMap: "顯示於公開地圖",
      featured: "精選故事",
      save: "儲存故事設定",
      animalTypes: {
        cat: "貓",
        dog: "狗",
        mixed: "貓狗",
        unknown: "未分類",
      },
      publicStatuses: {
        rescued: "已救援",
        medical_care: "醫療照護",
        foster_recovery: "暫養康復",
        ready_for_adoption: "準備領養",
        adopted: "已領養",
        sponsor_needed: "需要助養",
        closed: "已完結",
      },
    },
    updates: {
      heading: "故事更新",
      type: "類型",
      title: "標題",
      occurredAt: "發生時間",
      visibility: "可見度",
      body: "內容",
      allowDrafts: "發佈後可產生領養人通知草稿",
      add: "新增故事更新",
    },
    media: {
      heading: "媒體與相片",
      intro1: "上傳圖片作為封面或故事更新相片（JPG、PNG 或 WEBP，8 MiB 以內）。",
      intro2: "圖片先儲存為私密媒體；內部更新的圖片不會公開。",
      file: "圖片檔案",
      update: "關聯更新",
      whole: "整篇內容",
      updateOption: (title: string, internal: boolean) => `${title}${internal ? "（內部）" : ""}`,
      altText: "Alt text",
      caption: "說明",
      sortOrder: "排序",
      cover: "設為封面",
      add: "新增媒體",
      empty: "尚未有媒體。",
      coverBadge: "封面",
    },
  },
  en: {
    back: "Back to content",
    loading: "Loading content...",
    notFound: "Content not found. Go back to the content list and choose another item.",
    refresh: "Refresh",
    publish: "Publish",
    archive: "Archive",
    archiveConfirm: (title: string) =>
      `Archive "${title}"? It will no longer appear on the public pages.`,
    leaveConfirm: "Leaving will discard your unsaved changes. Leave this page?",
    reloadConfirm: "Reloading will discard all unsaved changes. Continue?",
    reloadFailed: "Could not reload. Your unsaved changes are kept. Try again.",
    unsaved: "You have unsaved changes. Save each panel, then publish.",
    saved: (version: number | undefined) =>
      `Draft saved · version ${version === undefined ? "—" : formatAdminNumber(version, "en")}`,
    conflict: {
      message:
        "The content has a newer version, or its public URL clashes with another item. Your input is kept. Compare the latest content, and copy any text you want to keep before you reload.",
      compare: "Compare latest content",
      reload: "Reload latest version",
      latest: (version: number | undefined) =>
        `Latest server version ${version === undefined ? "" : formatAdminNumber(version, "en")} (your input is kept below)`,
    },
    history: {
      label: "Content history pages",
      previous: "Previous history page",
      page: (page: number) => `History page ${formatAdminNumber(page, "en")} · up to 20 per type`,
      next: "Next history page",
    },
    syncingMedia: (count: number) =>
      `The content is published. ${pluralCount(count, "image")} ${count === 1 ? "is" : "are"} still syncing; the system will retry automatically.`,
    publishIssues: {
      heading: "Fix these before publishing",
      field: (field: string) => PUBLISH_FIELD_NAMES[field] ?? field,
    },
    draftNotice: {
      created: (count: number) => `Created ${pluralCount(count, "notification draft")}`,
    },
    metadata: {
      heading: "Publication eligibility and source",
      intro:
        "Existing unclassified content stays readable and is listed for review. Marking content as demo or setting an effective date changes where it appears publicly straight away, so check the approval list first.",
      classification: "Content classification",
      classes: {
        unreviewed: "Awaiting verification",
        verified: "Verified",
        demo: "Demo (not public)",
      },
      source: "Data source / approval record",
      owner: "Content owner",
      effectiveFrom: "Effective from",
      effectiveUntil: "Effective until",
      save: "Save publication eligibility",
    },
    form: {
      heading: "Basic content",
      intro: "Title, summary, SEO and CTA settings.",
      save: "Save draft",
      saving: "Saving",
      title: "Title",
      slug: "Slug",
      type: "Type",
      subtitle: "Subtitle",
      summary: "Summary",
      body: "Body",
      ctaLabel: "CTA label",
      ctaUrl: "CTA link",
      seoTitle: "SEO title",
      seoDescription: "SEO description",
      ogTitle: "OG title",
      ogDescription: "OG description",
    },
    links: {
      heading: "Linked records",
      type: "Type",
      record: "Linked record",
      relationship: "Relationship",
      add: "Add linked record",
      empty: "No records are linked.",
      types: {
        animal: "Animal",
        adoption_case: "Adoption application",
        successful_adoption: "Successful adoption",
        supporter: "Supporter",
        volunteer_activity: "Volunteer activity",
      },
      relationships: {
        primary_subject: "Main subject",
        related_case: "Related case",
        adopter: "Adopter",
        volunteer_context: "Volunteer background",
        other: "Other",
      },
    },
    wall: {
      heading: "Story wall settings",
      notNeeded: "Only rescue stories need story wall settings.",
      animal: "Animal",
      publicStatus: "Public status",
      region: "Rescue region",
      date: "Rescue date",
      mapLabel: "Map label",
      latitude: "Public latitude",
      longitude: "Public longitude",
      address: "Internal address",
      notes: "Internal location notes",
      showOnMap: "Show on the public map",
      featured: "Featured story",
      save: "Save story wall settings",
      animalTypes: {
        cat: "Cat",
        dog: "Dog",
        mixed: "Cats and dogs",
        unknown: "Unclassified",
      },
      publicStatuses: {
        rescued: "Rescued",
        medical_care: "Medical care",
        foster_recovery: "Recovering in foster care",
        ready_for_adoption: "Ready for adoption",
        adopted: "Adopted",
        sponsor_needed: "Needs sponsorship",
        closed: "Closed",
      },
    },
    updates: {
      heading: "Story updates",
      type: "Type",
      title: "Title",
      occurredAt: "Happened at",
      visibility: "Visibility",
      body: "Details",
      allowDrafts: "Allow adopter notification drafts after publishing",
      add: "Add story update",
    },
    media: {
      heading: "Media and photos",
      intro1:
        "Upload an image as the cover or as a photo for a story update (JPG, PNG or WEBP, up to 8 MiB).",
      intro2:
        "Images are first saved as private media. Images on internal updates are never made public.",
      file: "Image file",
      update: "Linked update",
      whole: "Whole content item",
      updateOption: (title: string, internal: boolean) =>
        `${title}${internal ? " (internal)" : ""}`,
      altText: "Alt text",
      caption: "Caption",
      sortOrder: "Sort order",
      cover: "Set as cover",
      add: "Add media",
      empty: "No media yet.",
      coverBadge: "Cover",
    },
  },
});
