import { defineAdminCopy } from "../i18n/copy";
import { formatAdminDate, formatAdminDateOrNull, formatAdminNumber } from "../i18n/format";

/**
 * Copy for the FAQ screen: the list and the question form (`FaqManagement`), the answer tester
 * (`FaqAnswerTester`) and the search-gap report (`FaqSearchGapsReport`). The questions, answers and
 * keywords staff type, and the topics visitors searched for, are data and are not in here. The
 * label of each action button is `faqCtaOptionLabel` in `lib/faq/schemas`.
 */
export const faqCopy = defineAdminCopy({
  zh: {
    categories: {
      sponsorship: "助養",
      adoption: "領養",
      tax_receipt: "報稅收據",
      donation: "捐款",
      contact: "聯絡職員",
    },
    /** The name of a language that is a setting of the tester or a column of the report. */
    languages: { "zh-HK": "中文", en: "English" },
    list: {
      title: "常見問題",
      add: "新增問題",
      loading: "載入中…",
      loadFailed: "無法載入常見問題",
      category: "分類",
      question: "問題",
      sortOrder: "排序",
      status: "狀態",
      shown: "顯示中",
      disabled: "已停用",
      edit: "編輯",
      disable: "停用",
      disableFailed: "停用操作失敗，請再試一次。",
    },
    form: {
      category: "分類",
      questionZh: "問題（中文）",
      questionEn: "Question (English)",
      answerZh: "答案（中文）",
      answerEn: "Answer (English)",
      keywordsZh: "關鍵字（中文，以逗號分隔）",
      keywordsEn: "Keywords (English, comma-separated)",
      cta: "行動按鈕",
      noCta: "（沒有行動按鈕）",
      sensitive: "涉及個人資料／財務內容",
      isActive: "在 /help 頁面顯示",
      sortOrder: "排序",
      saveFailed: "儲存失敗，請檢查資料後再試一次。",
      save: "儲存",
      cancel: "取消",
    },
    tester: {
      heading: "測試答案",
      description: "輸入訪客的問法，查看公開搜尋會顯示甚麼。結果包括正在編輯、尚未儲存的草稿。",
      queryLabel: "訪客的問法",
      languageLegend: "語言",
      draftHidden: "此草稿目前設為不顯示，訪客在啟用前不會看到。",
      matchLevel: "配對程度：",
      confidence: { high: "高", medium: "中", low: "低", none: "沒有" },
      willSee: "訪客會看到：",
      direct: "直接答案",
      related: "相關答案",
      referToStaff: "轉介職員",
      matchedQuestions: "配對的問題：",
      advisedToContact: "此問題會建議訪客聯絡職員",
      cacheNote: "已發佈的修改最多需要 5 分鐘才會在訪客的頁面上出現。",
    },
    gaps: {
      heading: "搜尋未有答案的主題（過去 30 日）",
      loading: "載入中…",
      loadFailed: "無法載入搜尋主題報告",
      empty: "過去 30 日未有訪客搜尋找不到答案。",
      topic: "主題",
      language: "語言",
      result: "結果",
      searches: "搜尋次數",
      lastSeen: "最近一日",
      actions: "操作",
      confidence: { none: "沒有答案", low: "配對較弱" },
      /** The number of searches, as Chinese has always shown it. */
      count: (value: number) => String(value),
      /** The last day a topic was searched, a stored `YYYY-MM-DD` Hong Kong day. */
      day: (value: string) => formatAdminDateOrNull(value, "zh") ?? String(value),
      test: "測試",
      create: "以此新增問題",
      testLabel: (topic: string) => `測試「${topic}」`,
      createLabel: (topic: string) => `以此新增問題「${topic}」`,
    },
  },
  en: {
    categories: {
      sponsorship: "Sponsorship",
      adoption: "Adoption",
      tax_receipt: "Tax receipts",
      donation: "Donations",
      contact: "Contact staff",
    },
    languages: { "zh-HK": "Chinese", en: "English" },
    list: {
      title: "FAQ",
      add: "Add question",
      loading: "Loading…",
      loadFailed: "Could not load the FAQ",
      category: "Category",
      question: "Question",
      sortOrder: "Sort order",
      status: "Status",
      shown: "Shown",
      disabled: "Disabled",
      edit: "Edit",
      disable: "Disable",
      disableFailed: "Could not disable the question. Try again.",
    },
    form: {
      category: "Category",
      questionZh: "Question (Chinese)",
      questionEn: "Question (English)",
      answerZh: "Answer (Chinese)",
      answerEn: "Answer (English)",
      keywordsZh: "Keywords (Chinese, comma-separated)",
      keywordsEn: "Keywords (English, comma-separated)",
      cta: "Action button",
      noCta: "(No action button)",
      sensitive: "Involves personal or financial information",
      isActive: "Show on the /help page",
      sortOrder: "Sort order",
      saveFailed: "Could not save. Check the details and try again.",
      save: "Save",
      cancel: "Cancel",
    },
    tester: {
      heading: "Test answers",
      description:
        "Enter how a visitor might ask, to see what the public search would show. Results include the draft you are editing, even if it is not saved.",
      queryLabel: "How the visitor asks",
      languageLegend: "Language",
      draftHidden: "This draft is set to hidden, so visitors will not see it until it is enabled.",
      matchLevel: "Match level: ",
      confidence: { high: "High", medium: "Medium", low: "Low", none: "None" },
      willSee: "Visitors will see:",
      direct: "Direct answer",
      related: "Related answers",
      referToStaff: "Staff referral",
      matchedQuestions: "Matched questions:",
      advisedToContact: "Visitors will be advised to contact staff about this question",
      cacheNote: "Published changes can take up to 5 minutes to appear on the visitor's page.",
    },
    gaps: {
      heading: "Topics searched with no answer (last 30 days)",
      loading: "Loading…",
      loadFailed: "Could not load the search topics report",
      empty: "No searches went unanswered in the last 30 days.",
      topic: "Topic",
      language: "Language",
      result: "Result",
      searches: "Searches",
      lastSeen: "Last seen",
      actions: "Actions",
      confidence: { none: "No answer", low: "Weak match" },
      count: (value: number) => formatAdminNumber(value, "en"),
      day: (value: string) => formatAdminDate(value, "en"),
      test: "Test",
      create: "Add question from this",
      testLabel: (topic: string) => `Test "${topic}"`,
      createLabel: (topic: string) => `Add a question from "${topic}"`,
    },
  },
});
