import { defineAdminCopy } from "../i18n/copy";

/**
 * Copy for the knowledge base screen: the reference document picker, the article list and the
 * article editor. Many labels have always been English in the Chinese screen (Search, Title,
 * Topic, Source, Save, Delete and the publication names); they are kept as they were. The titles,
 * topics and introductions staff type are data.
 */
export const knowledgeCopy = defineAdminCopy({
  zh: {
    picker: {
      heading: "參考文件選擇",
      search: "搜尋文件",
      pager: "參考文件",
      note: "只可選擇已發布 PDF。切換文件頁面會保留目前所選文件。",
    },
    eyebrow: "Content",
    title: "知識專區",
    intro: "管理公開領養資訊、寵物照顧及參考連結。",
    filters: {
      search: "Search",
      publication: "Publication",
      all: "All",
      published: "Published",
      draft: "Draft",
    },
    loading: "Loading knowledge posts...",
    ownershipUnknown: "無法核實擁有權。",
    empty: "尚未有知識庫文章。",
    pager: "知識文章",
    managed: {
      byReleases: "由領養指南版本管理",
      readOnly: "This bilingual post is read-only here. Update it through the release workflow.",
      chineseAsset: "Chinese asset ID",
      englishAsset: "English asset ID",
    },
    editor: {
      addHeading: "新增知識文章",
      title: "Title",
      topic: "Topic",
      intro: "簡介",
      linkType: "連結方式",
      external: "外部網址",
      document: "PDF 文件",
      externalUrl: "外部網址",
      httpsOnly: "只接受 HTTPS 網址",
      documentLabel: "PDF 文件",
      choosePdf: "選擇已發布 PDF",
      currentChoice: "目前已選文件（其他頁面）",
      source: "Source",
      sortOrder: "排序",
      published: "Published",
      draft: "Draft",
      save: "Save",
      delete: "Delete",
      thisArticle: "此文章",
      confirmDelete: (title: string) => `確定刪除「${title}」？此操作無法復原。`,
    },
  },
  en: {
    picker: {
      heading: "Choose a reference document",
      search: "Search documents",
      pager: "Reference documents",
      note: "Only published PDFs can be chosen. Your current choice is kept when you switch document pages.",
    },
    eyebrow: "Website content",
    title: "Knowledge base",
    intro: "Manage the public adoption information, pet care and reference links.",
    filters: {
      search: "Search",
      publication: "Publication status",
      all: "All",
      published: "Published",
      draft: "Draft",
    },
    loading: "Loading knowledge posts...",
    ownershipUnknown: "Could not verify ownership. Refresh the page or try again later.",
    empty: "No knowledge base articles yet.",
    pager: "Knowledge articles",
    managed: {
      byReleases: "Managed in adoption guide releases",
      readOnly: "This bilingual post is read-only here. Update it through the release workflow.",
      chineseAsset: "Chinese asset ID",
      englishAsset: "English asset ID",
    },
    editor: {
      addHeading: "Add knowledge article",
      title: "Title",
      topic: "Topic",
      intro: "Short introduction",
      linkType: "Link type",
      external: "External URL",
      document: "PDF document",
      externalUrl: "External URL",
      httpsOnly: "HTTPS URLs only",
      documentLabel: "PDF document",
      choosePdf: "Choose a published PDF",
      currentChoice: "Current choice (on another page)",
      source: "Source",
      sortOrder: "Sort order",
      published: "Published",
      draft: "Draft",
      save: "Save",
      delete: "Delete",
      thisArticle: "this article",
      confirmDelete: (title: string) => `Delete "${title}"? This cannot be undone.`,
    },
  },
});
