import { defineAdminCopy } from "../i18n/copy";

/**
 * Copy for the content list (`ContentManagement`, with its quick "add content" form) and for the
 * full create form (`ContentCreateForm`). The content types, statuses and optional field labels
 * are in `contentCommonCopy`.
 */
export const managementCopy = defineAdminCopy({
  zh: {
    eyebrow: "宣傳",
    title: "宣傳內容",
    intro: "管理故事、活動、市集與報告頁面。",
    actions: {
      create: "建立內容",
      adoptionInformation: "領養資訊",
      guideReleases: "領養後指南版本",
      documents: "文件",
      annualReports: "年度報告",
      refresh: "重新整理",
    },
    cards: {
      all: "全部內容",
      published: "本頁已發布",
      drafts: "本頁草稿",
      rescueStories: "本頁救援故事",
    },
    eligibility: {
      heading: "本頁內容資格待核對",
      intro: "只讀清單；未分類內容保持現有公開狀態。正式下架或補上文案前，請逐項取得內容批准。",
      failed: "無法載入待核對清單。",
      demo: "示範",
      unverified: "待核實",
      detail: (id: string, slug: string, featured: boolean, onMap: boolean) =>
        `ID ${id} · 公開位置 /stories/${slug}${featured ? " · 精選候選" : ""}${onMap ? " · 地圖候選" : ""}`,
      suggestion: "建議：核對資料來源、負責人與生效日期，記錄批准後再更改分類。",
      view: "檢視",
      none: "本頁沒有待核對內容。",
    },
    filters: {
      search: "搜尋",
      searchPlaceholder: "標題、摘要或 slug",
      type: "類型",
      allTypes: "全部類型",
      status: "狀態",
      allStatuses: "全部狀態",
      rescueRegion: "救援地區",
      rescueRegionPlaceholder: "例如：灣仔",
      publishedFrom: "發布日期（起）",
      publishedTo: "發布日期（迄）",
      mapVisibility: "地圖顯示",
      all: "全部",
      mapOn: "顯示",
      mapOff: "不顯示",
      updates: "更新記錄",
      withUpdates: "有更新",
      withoutUpdates: "沒有更新",
      drafts: "通知草稿",
      draftStates: {
        draft: "草稿",
        copied: "已複製",
        sent_manually: "已手動發送",
        dismissed: "已略過",
      },
    },
    table: {
      title: "標題",
      type: "類型",
      status: "狀態",
      publishedAt: "發布日期",
      notPublished: "未發布",
      rescueRegion: "救援地區",
      notApplicable: "不適用",
      actions: "操作",
      edit: "編輯",
      empty: "沒有宣傳內容",
      pager: "內容",
    },
    /** The quick form above the list. */
    draftForm: {
      summary: "新增內容",
      type: "內容類型",
      title: "標題",
      summaryLabel: "摘要",
      note: "建立後會開啟草稿編輯器。請補齊相片、來源及類型所需資料，再檢查及發布。",
      failed: "未能建立草稿，請檢查資料後重試。",
      submit: "建立草稿",
      busy: "建立中…",
    },
    /** The full create form. */
    createForm: {
      eyebrow: "宣傳",
      title: "新增宣傳內容",
      type: "類型",
      titleLabel: "標題",
      slug: "網址 slug（小寫英數字與連字號）",
      summary: "摘要",
      body: "正文（可稍後填寫）",
      submit: "建立草稿",
      busy: "建立中",
      slugTaken: "此網址已被使用，請改用其他 slug。",
      failed: "建立失敗，請重試。",
    },
  },
  en: {
    eyebrow: "Content",
    title: "Content",
    intro: "Manage story, event, market and report pages.",
    actions: {
      create: "Create content",
      adoptionInformation: "Adoption information",
      guideReleases: "Post-adoption guide releases",
      documents: "Documents",
      annualReports: "Annual reports",
      refresh: "Refresh",
    },
    cards: {
      all: "All content",
      published: "Published on this page",
      drafts: "Drafts on this page",
      rescueStories: "Rescue stories on this page",
    },
    eligibility: {
      heading: "Content on this page that needs an eligibility check",
      intro:
        "This list is read-only. Unclassified content keeps its current public status. Before you take anything down or add missing wording, get approval for each item.",
      failed: "Could not load the list to check. Refresh the page or try again later.",
      demo: "Demo",
      unverified: "Awaiting verification",
      detail: (id: string, slug: string, featured: boolean, onMap: boolean) =>
        `ID ${id} · Public location /stories/${slug}${featured ? " · Featured candidate" : ""}${onMap ? " · Map candidate" : ""}`,
      suggestion:
        "Suggested: check the data source, owner and effective date, and change the classification only after the approval is recorded.",
      view: "View",
      none: "Nothing on this page needs checking.",
    },
    filters: {
      search: "Search",
      searchPlaceholder: "Title, summary or slug",
      type: "Type",
      allTypes: "All types",
      status: "Status",
      allStatuses: "All statuses",
      rescueRegion: "Rescue region",
      rescueRegionPlaceholder: "e.g. Wan Chai",
      publishedFrom: "Published from",
      publishedTo: "Published to",
      mapVisibility: "Map display",
      all: "All",
      mapOn: "Shown",
      mapOff: "Not shown",
      updates: "Update records",
      withUpdates: "Has updates",
      withoutUpdates: "No updates",
      drafts: "Notification drafts",
      draftStates: {
        draft: "Draft",
        copied: "Copied",
        sent_manually: "Sent manually",
        dismissed: "Dismissed",
      },
    },
    table: {
      title: "Title",
      type: "Type",
      status: "Status",
      publishedAt: "Publication date",
      notPublished: "Not published",
      rescueRegion: "Rescue region",
      notApplicable: "Not applicable",
      actions: "Actions",
      edit: "Edit",
      empty: "No content",
      pager: "Content",
    },
    draftForm: {
      summary: "Add content",
      type: "Content type",
      title: "Title",
      summaryLabel: "Summary",
      note: "The draft editor opens after you create it. Add the photos, sources and any details this type needs, then check and publish.",
      failed: "Could not create the draft. Check the details and try again.",
      submit: "Create draft",
      busy: "Creating…",
    },
    createForm: {
      eyebrow: "Content",
      title: "Add content",
      type: "Type",
      titleLabel: "Title",
      slug: "URL slug (lowercase letters, numbers and hyphens)",
      summary: "Summary",
      body: "Body (can be added later)",
      submit: "Create draft",
      busy: "Creating",
      slugTaken: "This URL is already in use. Use a different slug.",
      failed: "Could not create the content. Try again.",
    },
  },
});
