import { defineAdminCopy } from "../i18n/copy";

/**
 * Page copy for the coordinator case screens: the case list, the application inbox and manual
 * case intake.
 */
export const casePageCopy = defineAdminCopy({
  zh: {
    caseList: {
      title: "領養個案",
      subtitle: "協調員個案隊列、配對、跟進及完成領養。",
      searchLabel: "搜尋個案",
      searchPlaceholder: "搜尋申請人、電話或電郵",
      statusLabel: "按個案狀態篩選",
      statusPlaceholder: "個案狀態",
      allStatuses: "所有狀態",
      animalTypeLabel: "按動物類別篩選",
      animalTypePlaceholder: "動物類別",
      openOnly: "只顯示未完成",
      openOnlyLabel: "只顯示未完成個案",
      filterError: "無法載入狀態篩選",
      tableTitle: "個案",
      empty: "沒有找到個案",
      columns: {
        applicant: "申請人",
        animal: "申請動物",
        phone: "電話",
        created: "建立日期",
        status: "狀態",
      },
    },
    intakeInbox: {
      title: "申請收件箱",
      subtitle: "集中檢查公開領養申請、相片及探訪跟進。",
      openOnly: "只顯示未處理",
      openOnlyLabel: "只顯示未處理收件箱項目",
      loadError: "無法載入收件箱",
      empty: "沒有符合篩選的收件箱項目",
      allLanes: "全部",
      viewCase: "查看個案",
      noCase: "未連結個案",
      due: "到期",
      created: "建立",
      resolved: "已處理",
      photos: "相片",
      rankedAnimals: "動物偏好",
      visit: "探訪",
      applicant: "申請人",
      lanes: {
        new_adoption_application: "新公開申請",
        visit_followup: "探訪跟進",
        photos_to_review: "相片待審",
        needs_followup: "需要跟進",
      },
      urgency: {
        normal: "普通",
        high: "高",
        overdue: "逾期",
      },
    },
    manualIntake: {
      title: "手動建案",
      subtitle: "為電話、WhatsApp 或親身查詢建立領養個案。",
      createCase: "建立個案",
      creating: "建立中...",
      loadCaseStatusesError: "無法載入領養個案狀態",
      loadFollowupStatusesError: "無法載入跟進工作狀態",
      identity: "身份",
      identitySubtitle: "建立新捐款人紀錄前，先搜尋現有領養人或捐款人。",
      identitySearch: "搜尋姓名、電話、電郵或地址",
      identityPlaceholder: "輸入資料搜尋現有紀錄",
      createNewSupporter: "建立新捐款人",
      searchIdentitiesError: "無法搜尋身份",
      searchResults: "搜尋結果",
      searching: "搜尋中...",
      noIdentityMatched: "沒有現有身份符合搜尋。",
      currentIdentity: "目前身份",
      newSupporter: "新捐款人",
      existingIdentity: "現有身份",
      adopterProfile: "領養人檔案",
      supporter: "捐款人",
      blacklisted: "黑名單",
      fields: {
        supporterName: "捐款人姓名",
        supporterPhone: "捐款人電話",
        supporterEmail: "捐款人電郵",
        language: "語言",
        chinese: "繁體中文",
        english: "English",
        adopterEnglishName: "領養人英文名",
        adopterChineseName: "領養人中文名",
        adopterAddress: "領養人地址",
        householdSize: "家庭人數",
        caseDetails: "個案資料",
        caseDetailsSubtitle: "必填欄位會對應公開申請紀錄。",
        initialStatus: "初始狀態",
        animalType: "動物類別",
        applicantName: "申請人姓名",
        applicantPhone: "申請人電話",
        applicantEmail: "申請人電郵",
        requestedAnimalId: "申請動物 ID",
        optionalUuid: "選填 UUID",
        housingType: "住所類別",
        familySize: "家庭人數",
        applicantAddress: "申請人地址",
        existingPets: "現有寵物",
        reason: "申請原因",
        preferenceNotes: "偏好備註",
      },
      optionalTask: "選填工作",
      optionalTaskSubtitle: "建立個案時一併建立第一個協調員跟進工作。",
      createInitialTask: "建立初始跟進工作",
      taskStatus: "工作狀態",
      taskTitle: "工作標題",
      priority: "優先次序",
      dueAt: "到期時間",
      assignedTo: "負責人",
      volunteer: "義工",
      contactChannel: "聯絡渠道",
      taskType: "工作類型",
      remarks: "備註",
      review: "檢查",
      caseStatus: "個案狀態",
      applicant: "申請人",
      initialTask: "初始工作",
      clearAlert: "清除提示",
      noTask: "沒有工作",
      notSelected: "未選擇",
      applicantMissing: "未填寫申請人姓名",
      chooseStatus: "選擇狀態",
      validations: {
        identity: "請搜尋並選擇現有身份，或建立新捐款人。",
        supporterName: "請輸入新捐款人姓名。",
        supporterPhone: "請輸入新捐款人電話。",
        initialStatus: "請選擇初始個案狀態。",
        animalType: "請選擇動物類別。",
        applicantName: "請輸入申請人姓名。",
        applicantPhone: "請輸入申請人電話。",
        taskStatus: "請選擇跟進工作狀態。",
        taskTitle: "請輸入跟進工作標題。",
      },
    },
  },
  en: {
    caseList: {
      title: "Adoption cases",
      subtitle: "Coordinator queue, matching, follow-up, and finalization.",
      searchLabel: "Search cases",
      searchPlaceholder: "Search applicant, phone, or email",
      statusLabel: "Filter by case status",
      statusPlaceholder: "Case status",
      allStatuses: "All statuses",
      animalTypeLabel: "Filter by animal type",
      animalTypePlaceholder: "Animal type",
      openOnly: "Open only",
      openOnlyLabel: "Show open cases only",
      filterError: "Could not load status filters",
      tableTitle: "Cases",
      empty: "No cases found",
      columns: {
        applicant: "Applicant",
        animal: "Requested animal",
        phone: "Phone",
        created: "Created",
        status: "Status",
      },
    },
    intakeInbox: {
      title: "Application inbox",
      subtitle: "Review public adoption applications, photos, and visit follow-ups.",
      openOnly: "Open only",
      openOnlyLabel: "Show unresolved inbox items only",
      loadError: "Could not load inbox",
      empty: "No inbox items match these filters",
      allLanes: "All",
      viewCase: "View case",
      noCase: "No case linked",
      due: "Due",
      created: "Created",
      resolved: "Resolved",
      photos: "Photos",
      rankedAnimals: "Animal preferences",
      visit: "Visit",
      applicant: "Applicant",
      lanes: {
        new_adoption_application: "New public application",
        visit_followup: "Visit follow-up",
        photos_to_review: "Photos to review",
        needs_followup: "Needs follow-up",
      },
      urgency: {
        normal: "Normal",
        high: "High",
        overdue: "Overdue",
      },
    },
    manualIntake: {
      title: "Manual case intake",
      subtitle: "Create adoption cases from phone, WhatsApp, or walk-in requests.",
      createCase: "Create case",
      creating: "Creating...",
      loadCaseStatusesError: "Could not load adoption case statuses",
      loadFollowupStatusesError: "Could not load follow-up task statuses",
      identity: "Identity",
      identitySubtitle:
        "Search existing adopters or supporters before creating a new supporter record.",
      identitySearch: "Search name, phone, email, or address",
      identityPlaceholder: "Type to search existing records",
      createNewSupporter: "Create new supporter",
      searchIdentitiesError: "Could not search identities",
      searchResults: "Search results",
      searching: "Searching...",
      noIdentityMatched: "No existing identity matched this search.",
      currentIdentity: "Current identity",
      newSupporter: "New supporter",
      existingIdentity: "Existing identity",
      adopterProfile: "Adopter profile",
      supporter: "Supporter",
      blacklisted: "Blacklisted",
      fields: {
        supporterName: "Supporter name",
        supporterPhone: "Supporter phone",
        supporterEmail: "Supporter email",
        language: "Language",
        chinese: "繁體中文",
        english: "English",
        adopterEnglishName: "Adopter English name",
        adopterChineseName: "Adopter Chinese name",
        adopterAddress: "Adopter address",
        householdSize: "Household size",
        caseDetails: "Case details",
        caseDetailsSubtitle: "Required fields mirror the public application record.",
        initialStatus: "Initial status",
        animalType: "Animal type",
        applicantName: "Applicant name",
        applicantPhone: "Applicant phone",
        applicantEmail: "Applicant email",
        requestedAnimalId: "Requested animal ID",
        optionalUuid: "Optional UUID",
        housingType: "Housing type",
        familySize: "Family size",
        applicantAddress: "Applicant address",
        existingPets: "Existing pets",
        reason: "Reason",
        preferenceNotes: "Preference notes",
      },
      optionalTask: "Optional task",
      optionalTaskSubtitle: "Create the first coordinator follow-up together with the case.",
      createInitialTask: "Create initial follow-up task",
      taskStatus: "Task status",
      taskTitle: "Task title",
      priority: "Priority",
      dueAt: "Due at",
      assignedTo: "Assigned to",
      volunteer: "Volunteer",
      contactChannel: "Contact channel",
      taskType: "Task type",
      remarks: "Remarks",
      review: "Review",
      caseStatus: "Case status",
      applicant: "Applicant",
      initialTask: "Initial task",
      clearAlert: "Clear alert",
      noTask: "No task",
      notSelected: "Not selected",
      applicantMissing: "Applicant name missing",
      chooseStatus: "Choose status",
      validations: {
        identity: "Search and select an existing identity, or create a new supporter.",
        supporterName: "Enter the new supporter's name.",
        supporterPhone: "Enter the new supporter's phone number.",
        initialStatus: "Choose an initial case status.",
        animalType: "Choose an animal type.",
        applicantName: "Enter the applicant name.",
        applicantPhone: "Enter the applicant phone number.",
        taskStatus: "Choose a follow-up task status.",
        taskTitle: "Enter the follow-up task title.",
      },
    },
  },
});
