import { defineAdminCopy } from "../i18n/copy";
import { formatAdminNumber } from "../i18n/format";

/**
 * Page copy for the other coordinator screens: adopters, reports and statuses.
 */
export const coordinatorPageCopy = defineAdminCopy({
  zh: {
    adopters: {
      title: "領養人",
      subtitle: "領養人檔案、領養紀錄、黑名單狀態及跟進工作量。",
      exportCsv: "匯出 CSV",
      searchLabel: "搜尋領養人",
      searchPlaceholder: "搜尋姓名、電話或電郵",
      blacklistLabel: "按黑名單狀態篩選",
      blacklistPlaceholder: "黑名單狀態",
      openCases: "未完成個案",
      openCasesLabel: "顯示有未完成個案的領養人",
      openTasks: "未完成工作",
      openTasksLabel: "顯示有未完成工作的領養人",
      tableTitle: "領養人檔案",
      empty: "沒有找到領養人",
      blacklisted: "黑名單",
      clear: "正常",
      allBlacklistStates: "所有黑名單狀態",
      notBlacklisted: "非黑名單",
      latestCase: "最新個案",
      columns: {
        nameArea: "姓名及地區",
        contact: "聯絡",
        history: "紀錄",
        latestCase: "最新個案",
        action: "操作",
      },
      badges: {
        openCases: "未完成個案",
        adoptions: "宗領養",
        openTasks: "未完成工作",
        open: "未完成",
        adopted: "已領養",
        tasks: "工作",
      },
    },
    reports: {
      title: "協調員報表",
      subtitle: "每月接收個案摘要及重新產生 CSV 匯出紀錄。",
      loadSummaryError: "無法載入每月摘要",
      loadHistoryError: "無法載入匯出紀錄",
      month: "月份",
      kind: "種類",
      actor: "操作者",
      actorPlaceholder: "按使用者 ID 篩選",
      summaryLabel: "每月協調員摘要",
      exportHistory: "匯出紀錄",
      empty: "沒有符合篩選的匯出紀錄。",
      kindOptions: {
        all: "所有匯出",
        cases: "個案",
        adopters: "領養人",
        "successful-adoptions": "成功領養",
        animals: "動物",
        tasks: "工作",
      },
      metrics: {
        publicIntakeCases: "公開申請",
        manualIntakeCases: "手動建案",
        successfulAdoptions: "成功領養",
        openCases: "未完成個案",
        overdueTasks: "逾期工作",
        exportsRun: "已匯出",
      },
      columns: {
        timestamp: "時間",
        actor: "操作者",
        kind: "種類",
        rows: "列數",
        filters: "篩選",
        sourceRoute: "來源路由",
        action: "操作",
      },
    },
    statuses: {
      title: "協調員狀態",
      subtitle: (statuses: number, categories: number) =>
        `${formatAdminNumber(statuses, "zh")} 個狀態，分布於 ${formatAdminNumber(categories, "zh")} 個分類`,
      newStatus: "新增狀態",
      editStatus: "編輯狀態",
      systemKeyLocked: "系統 key 已鎖定",
      tableEmpty: "沒有狀態",
      loadError: "無法載入狀態",
      deleteConfirm: (zh: string, en: string) => `刪除 ${zh} / ${en}？`,
      noChanges: "沒有需要儲存的變更。",
      flags: {
        active: "啟用",
        inactive: "停用",
        closing: "結束",
        final: "最終",
        system: "系統",
      },
      columns: {
        label: "標籤",
        order: "排序",
        flags: "標記",
        category: "分類",
        actions: "操作",
      },
      fields: {
        category: "分類",
        key: "Key",
        chineseLabel: "中文標籤",
        englishLabel: "English label",
        sortOrder: "排序",
        color: "顏色",
        active: "啟用",
        closing: "結束",
        final: "最終",
        saveStatus: "儲存狀態",
      },
      categories: {
        adoption_case: { label: "領養個案", shortLabel: "個案" },
        animal_lifecycle: { label: "動物流程", shortLabel: "動物" },
        match: { label: "配對", shortLabel: "配對" },
        followup: { label: "跟進", shortLabel: "跟進" },
        final_outcome: { label: "結果", shortLabel: "結果" },
      },
      colors: {
        blue: "藍色",
        amber: "琥珀",
        cyan: "青色",
        purple: "紫色",
        indigo: "靛藍",
        green: "綠色",
        red: "紅色",
        slate: "灰藍",
        coral: "珊瑚",
      },
    },
  },
  en: {
    adopters: {
      title: "Adopters",
      subtitle: "Profiles, adoption history, blacklist status, and follow-up workload.",
      exportCsv: "Export CSV",
      searchLabel: "Search adopters",
      searchPlaceholder: "Search name, phone, or email",
      blacklistLabel: "Filter by blacklist status",
      blacklistPlaceholder: "Blacklist status",
      openCases: "Open cases",
      openCasesLabel: "Show adopters with open cases",
      openTasks: "Open tasks",
      openTasksLabel: "Show adopters with open tasks",
      tableTitle: "Adopter profiles",
      empty: "No adopters found",
      blacklisted: "Blacklisted",
      clear: "Clear",
      allBlacklistStates: "All blacklist states",
      notBlacklisted: "Not blacklisted",
      latestCase: "Latest case",
      columns: {
        nameArea: "Name and area",
        contact: "Contact",
        history: "History",
        latestCase: "Latest case",
        action: "Action",
      },
      badges: {
        openCases: "open cases",
        adoptions: "adoptions",
        openTasks: "open tasks",
        open: "open",
        adopted: "adopted",
        tasks: "tasks",
      },
    },
    reports: {
      title: "Coordinator reports",
      subtitle: "Monthly intake summary and regenerated CSV export history.",
      loadSummaryError: "Could not load monthly summary",
      loadHistoryError: "Could not load export history",
      month: "Month",
      kind: "Kind",
      actor: "Actor",
      actorPlaceholder: "Filter by actor user ID",
      summaryLabel: "Monthly coordinator summary",
      exportHistory: "Export history",
      empty: "No exports match these filters.",
      kindOptions: {
        all: "All exports",
        cases: "Cases",
        adopters: "Adopters",
        "successful-adoptions": "Successful adoptions",
        animals: "Animals",
        tasks: "Tasks",
      },
      metrics: {
        publicIntakeCases: "Public intake",
        manualIntakeCases: "Manual intake",
        successfulAdoptions: "Successful",
        openCases: "Open cases",
        overdueTasks: "Overdue tasks",
        exportsRun: "Exports run",
      },
      columns: {
        timestamp: "Timestamp",
        actor: "Actor",
        kind: "Kind",
        rows: "Rows",
        filters: "Filters",
        sourceRoute: "Source route",
        action: "Action",
      },
    },
    statuses: {
      title: "Coordinator statuses",
      subtitle: (statuses: number, categories: number) =>
        `${formatAdminNumber(statuses, "en")} statuses across ${formatAdminNumber(categories, "en")} categories`,
      newStatus: "New status",
      editStatus: "Edit status",
      systemKeyLocked: "System key locked",
      tableEmpty: "No statuses",
      loadError: "Could not load statuses",
      deleteConfirm: (zh: string, en: string) => `Delete ${zh} / ${en}?`,
      noChanges: "No changes to save.",
      flags: {
        active: "Active",
        inactive: "Inactive",
        closing: "Closing",
        final: "Final",
        system: "System",
      },
      columns: {
        label: "Label",
        order: "Order",
        flags: "Flags",
        category: "Category",
        actions: "Actions",
      },
      fields: {
        category: "Category",
        key: "Key",
        chineseLabel: "Chinese label",
        englishLabel: "English label",
        sortOrder: "Sort order",
        color: "Color",
        active: "Active",
        closing: "Closing",
        final: "Final",
        saveStatus: "Save status",
      },
      categories: {
        adoption_case: { label: "Adoption case", shortLabel: "Case" },
        animal_lifecycle: { label: "Animal lifecycle", shortLabel: "Animal" },
        match: { label: "Match", shortLabel: "Match" },
        followup: { label: "Follow-up", shortLabel: "Follow-up" },
        final_outcome: { label: "Outcome", shortLabel: "Outcome" },
      },
      colors: {
        blue: "Blue",
        amber: "Amber",
        cyan: "Cyan",
        purple: "Purple",
        indigo: "Indigo",
        green: "Green",
        red: "Red",
        slate: "Slate",
        coral: "Coral",
      },
    },
  },
});
