import { sponsorshipServerErrorText } from "../../../lib/sponsorshipAdmin/serverErrors";
import { defineAdminCopy } from "../i18n/copy";
import { formatAdminNumber } from "../i18n/format";

/**
 * Page copy for sponsorship pledge review and its detail drawer.
 */
export const pledgePageCopy = defineAdminCopy({
  zh: {
    pledgeReview: {
      title: "承諾審核",
      detailTitle: "承諾詳情",
      close: "關閉",
      searchLabel: "搜尋支持者姓名、電郵或編號",
      searchPlaceholder: "搜尋支持者姓名、電郵或編號",
      statusFilterLabel: "狀態",
      statusFilterPlaceholder: "狀態",
      allStatuses: "全部狀態",
      perPage: "每頁",
      empty: "沒有承諾",
      totalCount: (count: number) => `共 ${formatAdminNumber(count, "zh")} 項`,
      columns: {
        supporter: "支持者",
        amount: "承諾金額",
        created: "建立日期",
        status: "狀態",
      },
      statuses: {
        pending_payment: "待付款",
        provisional: "待審核",
        active: "已確認",
        needs_followup: "需要跟進",
        cancelled: "已取消",
      },
      paymentMethods: {
        fps: "轉數快 FPS",
        bank_transfer: "銀行轉帳",
        payme: "PayMe",
        paypal: "PayPal",
        give_asia: "Give.asia",
      },
      proofReviewStatuses: {
        pending: "待審核",
        approved: "已通過",
        rejected: "已拒絕",
      },
      proofSources: {
        public: "支持者提交",
        staff: "職員記錄",
      },
      customTier: "自訂",
      createdOn: (date: string) => `建立於 ${date}`,
      preferencesTitle: "動物排序",
      followup: {
        title: "助養跟進分派",
        assigneeLabel: "跟進職員",
        chooseAssignee: "選擇職員",
        assign: "分派跟進",
        currentAssignee: (email: string) => `目前由 ${email} 跟進`,
        unassigned: "尚未分派跟進職員",
        unavailable: "未能載入可分派職員，請稍後重試。",
        saved: "分派已儲存。",
        savedRefreshFailed: "分派已儲存；最新資料未能載入，請重新整理。",
      },
      /** The message for each way an action in the drawer can fail, by the code the drawer keeps. */
      errors: {
        review: "審核失敗",
        // Adding an animal and ending a sponsorship have always shown the review text when the
        // server gave no reason, so Chinese keeps it; English says what went wrong.
        assignAnimal: "審核失敗",
        endAssignment: "審核失敗",
        // The sponsorship API sends this one in zh-HK; the other server reasons are English.
        proofReviewChanged: sponsorshipServerErrorText("proofReviewChanged", "zh"),
        followup: "跟進分派失敗，請重新載入後再試。",
        followupConflict: "跟進資料已有更新，請核對目前職員後再分派。",
        followupUnknown: "未能確認分派結果；請重新整理或重試原有分派。",
        cancel: "取消失敗",
        recordPayment: "記錄付款失敗",
      },
      recordPayment: {
        title: "記錄付款",
        methodLabel: "付款方式",
        referenceLabel: "參考編號",
        amountLabel: "金額 (HKD)",
        dateLabel: "付款日期",
        noteLabel: "備註",
        proofLabel: "付款證明（選填）",
        save: "儲存付款記錄",
      },
      reviewProof: {
        title: "審核付款證明",
        noteLabel: "備註",
        approve: "核實通過",
        reject: "拒絕",
        rejectConsequence: "",
      },
      assignments: {
        title: "已確認助養動物",
        started: "開始日期",
        ended: "結束日期",
        add: "新增動物",
        addPlaceholder: "動物 UUID",
        end: "結束助養關係",
        reasonLabel: "結束原因",
        noteLabel: "備註",
        needsAnimal: "此助養仍在付款，但未有對應動物，請聯絡助養人跟進。",
        reasons: {
          adopted: "已被領養",
          deceased: "已離世",
          ineligible: "已退出助養計劃",
          retired: "紀錄已封存",
          supporter_request: "助養人要求",
          transferred: "轉至其他動物",
          other: "其他",
        },
      },
      proofPreview: {
        noFile: "未附上檔案",
        load: "載入付款證明",
        loading: "載入付款證明中...",
        loadError: (message: string) => `無法載入付款證明：${message}`,
        open: (fileName: string) => `開啟付款證明（${fileName}）`,
      },
      cancel: {
        action: "取消助養",
        confirmConsequence: "",
      },
      proofHistory: {
        title: "付款證明記錄",
        current: "（目前）",
        file: (fileName: string) => `檔案：${fileName}`,
        note: (note: string) => `備註：${note}`,
      },
      recentActivity: "近期活動",
      viewSupporterTimeline: "查看完整支持者時間軸",
    },
  },
  en: {
    pledgeReview: {
      title: "Pledge review",
      detailTitle: "Pledge details",
      close: "Close",
      searchLabel: "Search supporter name, email or reference",
      searchPlaceholder: "Search supporter name, email or reference",
      statusFilterLabel: "Status",
      statusFilterPlaceholder: "Status",
      allStatuses: "All statuses",
      perPage: "Per page",
      empty: "No pledges found",
      totalCount: (count: number) => `${formatAdminNumber(count, "en")} total`,
      columns: {
        supporter: "Supporter",
        amount: "Pledge amount",
        created: "Created",
        status: "Status",
      },
      statuses: {
        pending_payment: "Pending payment",
        provisional: "Pending review",
        active: "Confirmed",
        needs_followup: "Needs follow-up",
        cancelled: "Cancelled",
      },
      paymentMethods: {
        fps: "FPS",
        bank_transfer: "Bank transfer",
        payme: "PayMe",
        paypal: "PayPal",
        give_asia: "Give.asia",
      },
      proofReviewStatuses: {
        pending: "Pending review",
        approved: "Approved",
        rejected: "Rejected",
      },
      proofSources: {
        public: "Submitted by supporter",
        staff: "Recorded by staff",
      },
      customTier: "Custom",
      createdOn: (date: string) => `Created ${date}`,
      preferencesTitle: "Animal ranking",
      followup: {
        title: "Sponsorship follow-up",
        assigneeLabel: "Follow-up staff member",
        chooseAssignee: "Choose staff member",
        assign: "Assign follow-up",
        currentAssignee: (email: string) => `Currently assigned to ${email}`,
        unassigned: "No follow-up staff member assigned",
        unavailable: "Could not load staff choices. Please try again.",
        saved: "Assignment saved.",
        savedRefreshFailed: "Assignment saved; the latest details could not load. Please refresh.",
      },
      errors: {
        review: "Could not review the payment proof. Refresh the page and try again.",
        assignAnimal: "Could not add the animal. Check the animal UUID and try again.",
        endAssignment: "Could not end the sponsorship. Refresh the page and try again.",
        proofReviewChanged: sponsorshipServerErrorText("proofReviewChanged", "en"),
        followup: "Could not assign follow-up. Refresh and try again.",
        followupConflict:
          "Follow-up details changed. Check the current owner before assigning again.",
        followupUnknown:
          "The assignment result could not be confirmed. Refresh or retry the original assignment.",
        cancel: "Could not cancel the sponsorship. Refresh the page and try again.",
        recordPayment: "Could not record the payment. Check the details and try again.",
      },
      recordPayment: {
        title: "Record payment",
        methodLabel: "Payment method",
        referenceLabel: "Reference",
        amountLabel: "Amount (HKD)",
        dateLabel: "Payment date",
        noteLabel: "Note",
        proofLabel: "Payment proof (optional)",
        save: "Save payment record",
      },
      reviewProof: {
        title: "Review payment proof",
        noteLabel: "Note",
        approve: "Approve",
        reject: "Reject",
        rejectConsequence:
          "Rejecting this payment proof moves the sponsorship to follow-up. The supporter is emailed when an address is on file.",
      },
      assignments: {
        title: "Confirmed sponsored animals",
        started: "Started",
        ended: "Ended",
        add: "Add animal",
        addPlaceholder: "Animal UUID",
        end: "End sponsorship",
        reasonLabel: "Reason",
        noteLabel: "Note",
        needsAnimal:
          "This sponsorship is still being paid but backs no animal. Please contact the supporter.",
        reasons: {
          adopted: "Adopted",
          deceased: "Passed away",
          ineligible: "Left the sponsorship programme",
          retired: "Record archived",
          supporter_request: "Supporter asked",
          transferred: "Moved to another animal",
          other: "Other",
        },
      },
      proofPreview: {
        noFile: "No file attached",
        load: "Load payment proof",
        loading: "Loading payment proof...",
        loadError: (message: string) =>
          `Could not load the payment proof (${message}). Select Load payment proof to try again.`,
        open: (fileName: string) => `Open payment proof (${fileName})`,
      },
      cancel: {
        action: "Cancel sponsorship",
        confirmConsequence:
          "Cancelling ends this sponsorship. The supporter is emailed when an address is on file.",
      },
      proofHistory: {
        title: "Payment proof history",
        current: "(current)",
        file: (fileName: string) => `File: ${fileName}`,
        note: (note: string) => `Note: ${note}`,
      },
      recentActivity: "Recent activity",
      viewSupporterTimeline: "View full supporter timeline",
    },
  },
});
