import { defineAdminCopy } from "../i18n/copy";
import { formatAdminNumber, pluralCount } from "../i18n/format";

/**
 * Page copy shared by several admin screens: common labels, animal types, priorities, contact
 * channels and supporter identity modes.
 */
export const sharedPageCopy = defineAdminCopy({
  zh: {
    common: {
      refresh: "重新整理",
      clear: "清除",
      loading: "載入中...",
      rows: "列數",
      records: "筆紀錄",
      total: "總數",
      page: "頁",
      of: "共",
      previous: "上一頁",
      next: "下一頁",
      action: "操作",
      actions: "操作",
      open: "開啟",
      edit: "編輯",
      delete: "刪除",
      deleting: "刪除中",
      save: "儲存",
      saving: "儲存中",
      optional: "選填",
      noChannel: "沒有渠道",
      inactive: "停用",
      exporting: "匯出中...",
      export: "匯出",
      exportCsv: "匯出 CSV",
      supportersCsv: "支持者 CSV",
      donationsCsv: "捐款 CSV",
      downloadAgain: "再次下載",
      downloading: "下載中...",
      downloadFailed: "下載失敗",
      exportFailed: "匯出失敗",
      notSignedIn: "未登入",
      noContact: "沒有聯絡資料",
      searchMatches: (count: number) => `${formatAdminNumber(count, "zh")} 個結果`,
      totalCount: (count: number) => `${formatAdminNumber(count, "zh")} 筆`,
      totalRecords: (count: number) => `${formatAdminNumber(count, "zh")} 筆紀錄`,
      totalSupporters: (count: number) => `共 ${formatAdminNumber(count, "zh")} 位支持者`,
      scheduledOrCompleted: (count: number) => `${formatAdminNumber(count, "zh")} 個已排程或已完成`,
      pageOf: (page: number, totalPages: number) =>
        `第 ${formatAdminNumber(page, "zh")} 頁，共 ${formatAdminNumber(totalPages, "zh")} 頁`,
      rowsCount: (count: number) => `${formatAdminNumber(count, "zh")} 列`,
    },
    animalTypes: {
      all: "所有動物",
      cat: "貓",
      dog: "狗",
      sponsor: "助養動物",
      unknown: "未知",
    },
    priority: {
      all: "所有優先次序",
      low: "低",
      normal: "普通",
      high: "高",
      urgent: "緊急",
    },
    contactChannel: {
      phone: "電話",
      whatsapp: "WhatsApp",
      email: "電郵",
      in_person: "面談",
      internal: "內部",
    },
    identityModes: {
      new_supporter: "新支持者",
      existing_supporter: "現有支持者",
      existing_adopter: "現有領養人",
    },
  },
  en: {
    common: {
      refresh: "Refresh",
      clear: "Clear",
      loading: "Loading...",
      rows: "Rows",
      records: "records",
      total: "total",
      page: "Page",
      of: "of",
      previous: "Previous",
      next: "Next",
      action: "Action",
      actions: "Actions",
      open: "Open",
      edit: "Edit",
      delete: "Delete",
      deleting: "Deleting",
      save: "Save",
      saving: "Saving",
      optional: "Optional",
      noChannel: "No channel",
      inactive: "inactive",
      exporting: "Exporting...",
      export: "Export",
      exportCsv: "Export CSV",
      supportersCsv: "Supporters CSV",
      donationsCsv: "Donations CSV",
      downloadAgain: "Download again",
      downloading: "Downloading...",
      downloadFailed: "Download failed",
      exportFailed: "Export failed",
      notSignedIn: "Not signed in. Sign in again.",
      noContact: "No contact on file",
      searchMatches: (count: number) => pluralCount(count, "match", "matches"),
      totalCount: (count: number) => `${formatAdminNumber(count, "en")} total`,
      totalRecords: (count: number) => pluralCount(count, "record"),
      totalSupporters: (count: number) => pluralCount(count, "supporter"),
      scheduledOrCompleted: (count: number) =>
        `${formatAdminNumber(count, "en")} scheduled or completed`,
      pageOf: (page: number, totalPages: number) =>
        `Page ${formatAdminNumber(page, "en")} of ${formatAdminNumber(totalPages, "en")}`,
      rowsCount: (count: number) => pluralCount(count, "row"),
    },
    animalTypes: {
      all: "All animals",
      cat: "Cats",
      dog: "Dogs",
      sponsor: "Sponsor animals",
      unknown: "Unknown",
    },
    priority: {
      all: "All priorities",
      low: "Low",
      normal: "Normal",
      high: "High",
      urgent: "Urgent",
    },
    contactChannel: {
      phone: "Phone",
      whatsapp: "WhatsApp",
      email: "Email",
      in_person: "In person",
      internal: "Internal",
    },
    identityModes: {
      new_supporter: "New supporter",
      existing_supporter: "Existing supporter",
      existing_adopter: "Existing adopter",
    },
  },
});
