import { defineAdminCopy } from "../i18n/copy";

/**
 * Page copy for coordinator follow-up work: the task centre and the task panel on a case.
 */
export const taskPageCopy = defineAdminCopy({
  zh: {
    taskCenter: {
      title: "協調員工作中心",
      subtitle: "查看、篩選及更新領養個案和動物的跟進工作。",
      searchLabel: "搜尋工作",
      searchPlaceholder: "搜尋標題、結果或備註",
      dueLabel: "按到期日篩選",
      priorityLabel: "按優先次序篩選",
      assignedToLabel: "按負責人篩選",
      assignedToPlaceholder: "負責人",
      openOnly: "只顯示未完成",
      openOnlyLabel: "只顯示未完成工作",
      summaryLabel: "目前頁面的工作摘要",
      loadTasksError: "無法載入協調員工作",
      loadStatusesError: "無法載入工作狀態",
      tasks: "工作",
      empty: "沒有符合篩選的協調員工作",
      dueOptions: {
        all: "所有到期日",
        overdue: "已逾期",
        today: "今天",
        upcoming: "即將到期",
        none: "沒有到期日",
      },
      summary: {
        overdue: "已逾期",
        today: "今天",
        upcoming: "即將到期",
        none: "沒有到期日",
        done: "已完成",
        urgent: "緊急",
      },
    },
    taskPanel: {
      defaultTitle: "跟進工作",
      noFollowups: "未有跟進紀錄",
      addStatusFirst: "請先建立一個啟用中的跟進狀態，才可新增工作。",
      createValidation: "新增工作前，請先填寫標題及跟進狀態。",
      chooseStatus: "選擇狀態",
      saveTask: "儲存工作",
      addTask: "新增工作",
      labels: {
        title: "標題",
        status: "狀態",
        priority: "優先次序",
        channel: "渠道",
        due: "到期",
        scheduled: "已排程",
        completed: "已完成",
        nextStep: "下一步",
        volunteer: "義工",
        outcome: "結果",
        remarks: "備註",
      },
      display: {
        due: "到期",
        scheduled: "已排程",
        completed: "已完成",
        nextStep: "下一步",
        volunteer: "義工",
        channel: "渠道",
        outcome: "結果",
        remarks: "備註",
      },
      placeholders: {
        title: "領養後電話跟進",
        optional: "選填",
        remarks: "選填協調員備註",
      },
    },
  },
  en: {
    taskCenter: {
      title: "Coordinator task centre",
      subtitle: "View, filter and update follow-up work across adoption cases and animals.",
      searchLabel: "Search tasks",
      searchPlaceholder: "Search title, outcome or remarks",
      dueLabel: "Filter by due date",
      priorityLabel: "Filter by priority",
      assignedToLabel: "Filter by assignee",
      assignedToPlaceholder: "Assigned to",
      openOnly: "Open only",
      openOnlyLabel: "Show open tasks only",
      summaryLabel: "Current page task summary",
      loadTasksError: "Could not load coordinator tasks",
      loadStatusesError: "Could not load task statuses",
      tasks: "Tasks",
      empty: "No coordinator tasks match these filters",
      dueOptions: {
        all: "All due dates",
        overdue: "Overdue",
        today: "Today",
        upcoming: "Upcoming",
        none: "No due date",
      },
      summary: {
        overdue: "Overdue",
        today: "Today",
        upcoming: "Upcoming",
        none: "No due date",
        done: "Done",
        urgent: "Urgent",
      },
    },
    taskPanel: {
      defaultTitle: "Follow-ups",
      noFollowups: "No follow-ups recorded",
      addStatusFirst: "Create an active follow-up status before adding tasks.",
      createValidation: "Add a title and follow-up status before creating a task.",
      chooseStatus: "Choose status",
      saveTask: "Save task",
      addTask: "Add task",
      labels: {
        title: "Title",
        status: "Status",
        priority: "Priority",
        channel: "Channel",
        due: "Due",
        scheduled: "Scheduled",
        completed: "Completed",
        nextStep: "Next step",
        volunteer: "Volunteer",
        outcome: "Outcome",
        remarks: "Note",
      },
      display: {
        due: "Due",
        scheduled: "Scheduled",
        completed: "Completed",
        nextStep: "Next step",
        volunteer: "Volunteer",
        channel: "Channel",
        outcome: "Outcome",
        remarks: "Note",
      },
      placeholders: {
        title: "Post-adoption call",
        optional: "Optional",
        remarks: "Optional coordinator note",
      },
    },
  },
});
