import type { SchemaRequirement } from "./releaseSchema";

// Snapshot of public table/function declarations after the production ledger 20260914164558.
// Regenerate only after reviewing migration SQL and source call sites.
export const releaseManifest: SchemaRequirement[] = [
  {
    kind: "table",
    schema: "public",
    name: "volunteer_profile_review_assignment",
    feature: "volunteer-bulk",
    required: true,
    columns: {
      profile_id: "uuid",
      reviewer_user_id: "uuid",
      version: "bigint",
      updated_by: "uuid",
      updated_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "volunteer_review_bulk_operation",
    feature: "volunteer-bulk",
    required: true,
    columns: {
      id: "uuid",
      actor_user_id: "uuid",
      reviewer_user_id: "uuid",
      filter_hash: "text",
      created_at: "timestamptz",
      expires_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "volunteer_review_bulk_item",
    feature: "volunteer-bulk",
    required: true,
    columns: {
      operation_id: "uuid",
      profile_id: "uuid",
      ordinal: "integer",
      expected_profile_revision: "bigint",
      expected_assignment_version: "bigint",
      before_reviewer: "uuid",
      after_reviewer: "uuid",
      status: "text",
      reason_code: "text",
      applied_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "function",
    schema: "public",
    name: "get_volunteer_review_bulk_operation",
    feature: "volunteer-bulk",
    required: true,
    arguments: "p_actor uuid, p_operation uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "create_volunteer_review_bulk_preview",
    feature: "volunteer-bulk",
    required: true,
    arguments: "p_actor uuid, p_ids uuid[], p_reviewer uuid, p_filter_hash text",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "apply_volunteer_review_bulk_item",
    feature: "volunteer-bulk",
    required: true,
    arguments: "p_actor uuid, p_operation uuid, p_profile uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "table",
    schema: "public",
    name: "crm_tag_bulk_operation",
    feature: "crm-bulk",
    required: true,
    columns: {
      id: "uuid",
      actor_user_id: "uuid",
      filter_hash: "text",
      tag: "text",
      created_at: "timestamptz",
      expires_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "crm_tag_bulk_item",
    feature: "crm-bulk",
    required: true,
    columns: {
      operation_id: "uuid",
      supporter_id: "uuid",
      ordinal: "integer",
      expected_version: "bigint",
      before_tags: "text[]",
      after_tags: "text[]",
      status: "text",
      reason_code: "text",
      applied_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "function",
    schema: "public",
    name: "get_crm_tag_bulk_operation",
    feature: "crm-bulk",
    required: true,
    arguments: "p_actor uuid, p_operation uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "create_crm_tag_bulk_preview",
    feature: "crm-bulk",
    required: true,
    arguments: "p_actor uuid, p_ids uuid[], p_tag text, p_filter_hash text",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "apply_crm_tag_bulk_item",
    feature: "crm-bulk",
    required: true,
    arguments: "p_actor uuid, p_operation uuid, p_supporter uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "table",
    schema: "public",
    name: "recipient_notification_draft_duplicate_archive",
    feature: "release",
    required: true,
    columns: { kept_id: "uuid", archived_at: "timestamptz" },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "adoption_upload_intent",
    feature: "release",
    required: true,
    columns: {
      application_id: "uuid",
      photo_paths: "text[]",
      status_token_hash: "text",
      created_at: "timestamptz",
      expires_at: "timestamptz",
      submitted_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "sponsorship_proof_upload_intent",
    feature: "sponsorship",
    required: true,
    columns: {
      pledge_id: "uuid",
      storage_path: "text",
      created_at: "timestamptz",
      expires_at: "timestamptz",
      submitted_at: "timestamptz",
      cleanup_claimed_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "internship_attachment_upload_intent",
    feature: "internships",
    required: true,
    columns: {
      storage_path: "text",
      application_id: "uuid",
      actor: "uuid",
      created_at: "timestamptz",
      expires_at: "timestamptz",
      attached_at: "timestamptz",
      cleanup_claimed_at: "timestamptz",
      cleaned_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "sponsorship_staff_proof_upload_intent",
    feature: "sponsorship",
    required: true,
    columns: {
      storage_path: "text",
      pledge_id: "uuid",
      created_at: "timestamptz",
      expires_at: "timestamptz",
      attached_at: "timestamptz",
      cleanup_claimed_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "adoption_instruction_pages",
    feature: "adoption-cms",
    required: true,
    columns: {
      page_key: "text",
      published_revision_id: "uuid",
      draft_revision_id: "uuid",
      version: "integer",
      created_at: "timestamptz",
      updated_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "adoption_instruction_revisions",
    feature: "adoption-cms",
    required: true,
    columns: {
      id: "uuid",
      page_key: "text",
      revision_number: "integer",
      state: "text",
      content: "jsonb",
      source_revision_id: "uuid",
      version: "integer",
      created_by: "uuid",
      updated_by: "uuid",
      published_by: "uuid",
      published_at: "timestamptz",
      archived_by: "uuid",
      archived_at: "timestamptz",
      created_at: "timestamptz",
      updated_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "adoption_instruction_publish_requests",
    feature: "adoption-cms",
    required: true,
    columns: {
      actor_admin_id: "uuid",
      idempotency_key: "text",
      page_key: "text",
      revision_id: "uuid",
      revision_version: "integer",
      result: "jsonb",
      created_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "animal_draft_image_upload_intent",
    feature: "animal-media",
    required: true,
    columns: {
      storage_path: "text",
      animal_id: "uuid",
      created_at: "timestamptz",
      expires_at: "timestamptz",
      attached_at: "timestamptz",
      cleanup_claimed_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "animal_publication_media_copy",
    feature: "animal-media",
    required: true,
    columns: {
      public_path: "text",
      publication_version_id: "uuid",
      animal_id: "uuid",
      source_path: "text",
      public_url: "text",
      created_at: "timestamptz",
      copied_at: "timestamptz",
      copy_claimed_at: "timestamptz",
      repair_status: "text",
      repair_attempts: "integer",
      next_retry_at: "timestamptz",
      last_error_code: "text",
      lease_token: "uuid",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "table",
    schema: "public",
    name: "animal_publication_publish_receipt",
    feature: "finance",
    required: true,
    columns: {
      preview_id: "uuid",
      animal_id: "uuid",
      actor_id: "uuid",
      version_id: "uuid",
      committed_at: "timestamptz",
    },
    rls: true,
    grants: { service_role: ["SELECT"] },
  },
  {
    kind: "function",
    schema: "public",
    name: "read_content_admin_summaries",
    feature: "content",
    required: true,
    arguments: "p_filters jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "read_published_content_snapshots",
    feature: "release",
    required: true,
    arguments: "p_filters jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "cms_promotion_command",
    feature: "release",
    required: true,
    arguments: "p_actor uuid, p_command jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mutate_admin_content_with_audit",
    feature: "content",
    required: true,
    arguments: "p_actor_user_id uuid, p_entity text, p_operation text, p_id uuid, p_payload jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "update_adoption_fee_content_with_audit",
    feature: "adoption-cms",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_id uuid, p_expected_version integer, p_item_name text, p_price_hkd text",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "reorder_adoption_fees_with_audit",
    feature: "adoption-cms",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_first_id uuid, p_second_id uuid, p_first_version integer, p_second_version integer",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mutate_dog_friendly_estate_with_audit",
    feature: "adoption-cms",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_command text, p_id uuid, p_expected_version integer, p_payload jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mutate_crm_supporter_with_audit",
    feature: "crm",
    required: true,
    arguments:
      "p_operation text, p_supporter_id uuid, p_input jsonb, p_roles jsonb, p_actor_user_id uuid, p_at timestamptz, p_detail jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "replace_supporter_roles_atomic",
    feature: "crm",
    required: true,
    arguments: "p_supporter_id uuid, p_roles jsonb",
    returns: "void",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "append_crm_consents_with_audit",
    feature: "crm",
    required: true,
    arguments:
      "p_rows jsonb, p_actor_user_id uuid, p_supporter_id uuid, p_at timestamptz, p_detail jsonb",
    returns: "void",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "create_volunteer_registration_idempotent",
    feature: "volunteer",
    required: true,
    arguments:
      "p_activity_id uuid, p_supporter_id uuid, p_registration_type text, p_participant_count integer, p_contact_name text, p_contact_email text, p_contact_phone text, p_language text, p_organization_name text, p_declared_age integer, p_youngest_age integer, p_guardian_name text, p_guardian_phone text, p_notes text, p_status_token_hash text, p_status_token_expires_at timestamptz, p_consent_email_requested boolean, p_consent_whatsapp_requested boolean",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "clone_volunteer_activity_with_audit",
    feature: "volunteer",
    required: true,
    arguments: "p_source_activity_id uuid, p_actor_user_id uuid, p_starts_at timestamptz",
    returns: "uuid",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mutate_adoption_coordinator_with_audit",
    feature: "release",
    required: true,
    arguments: "p_actor_user_id uuid, p_entity text, p_operation text, p_id uuid, p_payload jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "update_admin_user_with_audit",
    feature: "admin",
    required: true,
    arguments: "p_actor_user_id uuid, p_target_id uuid, p_role text, p_status text",
    returns: "public.admin_user",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "invite_admin_user_with_audit",
    feature: "admin",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_auth_user_id uuid, p_email text, p_role text, p_sent_at timestamptz",
    returns: "public.admin_user",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "resend_admin_invite_with_audit",
    feature: "admin",
    required: true,
    arguments: "p_actor_user_id uuid, p_target_id uuid, p_sent_at timestamptz",
    returns: "public.admin_user",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "activate_admin_invite_with_audit",
    feature: "admin",
    required: true,
    arguments: "p_auth_user_id uuid",
    returns: "public.admin_user",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "set_animal_archived_with_audit",
    feature: "animal-media",
    required: true,
    arguments: "p_actor_user_id uuid, p_animal_id uuid, p_archived boolean",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "fail_pending_provider_payment",
    feature: "finance",
    required: true,
    arguments: "p_payment_id uuid, p_donation_id uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "refund_provider_payment_atomically",
    feature: "finance",
    required: true,
    arguments: "p_payment_id uuid, p_donation_id uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "update_group_enquiry_with_audit",
    feature: "group-enquiries",
    required: true,
    arguments:
      "p_enquiry_id uuid, p_actor_user_id uuid, p_expected_updated_at timestamptz, p_patch jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_sponsorship_proof_upload_submitted",
    feature: "sponsorship",
    required: true,
    arguments: "",
    returns: "trigger",
    executeRoles: [],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_expired_sponsorship_proof_uploads",
    feature: "sponsorship",
    required: true,
    arguments: "p_cutoff timestamptz, p_limit integer",
    returns: "table (pledge_id uuid, storage_path text, claimed_at timestamptz)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_internship_attachment_uploaded",
    feature: "internships",
    required: true,
    arguments: "",
    returns: "trigger",
    executeRoles: [],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_expired_internship_attachment_uploads",
    feature: "internships",
    required: true,
    arguments: "p_cutoff timestamptz, p_limit integer",
    returns: "table (storage_path text, claimed_at timestamptz)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "void_receipt_with_audit",
    feature: "finance",
    required: true,
    arguments: "p_receipt_id uuid, p_actor uuid, p_supporter_id uuid",
    returns: "table (receipt_id uuid, pdf_url text)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "void_donation_receipts_with_audit",
    feature: "finance",
    required: true,
    arguments: "p_donation_id uuid, p_reason text",
    returns: "table (receipt_id uuid, pdf_url text)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "issue_receipt_with_audit",
    feature: "finance",
    required: true,
    arguments:
      "p_donation_id uuid, p_supporter_id uuid, p_amount_cents integer, p_tax_year integer, p_issued_at timestamptz, p_actor uuid",
    returns:
      "table ( receipt_no text, receipt_id uuid, pdf_url text, tax_year integer, issued_at timestamptz, already_existed boolean )",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "reserve_staff_sponsorship_proof_upload",
    feature: "sponsorship",
    required: true,
    arguments: "p_pledge_id uuid, p_storage_path text",
    returns: "void",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_staff_sponsorship_proof_attached",
    feature: "sponsorship",
    required: true,
    arguments: "",
    returns: "trigger",
    executeRoles: [],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_expired_staff_sponsorship_proof_uploads",
    feature: "sponsorship",
    required: true,
    arguments: "p_cutoff timestamptz, p_limit integer",
    returns: "table (pledge_id uuid, storage_path text, claimed_at timestamptz)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "search_manual_case_identity",
    feature: "release",
    required: true,
    arguments: "p_query text, p_page integer, p_page_size integer",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_volunteer_operation_outbox",
    feature: "volunteer",
    required: true,
    arguments: "p_limit integer, p_lease_until timestamptz",
    returns: "setof public.volunteer_operation_outbox",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "change_adoption_case_status",
    feature: "release",
    required: true,
    arguments:
      "p_case_id uuid, p_status_id uuid, p_actor_user_id uuid, p_note text, p_closed_at timestamptz",
    returns: "void",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "create_manual_adoption_case",
    feature: "release",
    required: true,
    arguments: "p_actor_user_id uuid, p_identity jsonb, p_case jsonb, p_initial_task jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "cleanup_expired_adoption_application",
    feature: "release",
    required: true,
    arguments: "p_application_id uuid",
    returns: "text",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "create_public_sponsorship_pledge",
    feature: "sponsorship",
    required: true,
    arguments:
      "p_pledge_id uuid, p_pledge jsonb, p_preferences jsonb, p_proof jsonb, p_token jsonb",
    returns: "void",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "ensure_adoption_instruction_draft",
    feature: "adoption-cms",
    required: true,
    arguments: "p_expected_page_version integer, p_actor_user_id uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "update_adoption_instruction_draft",
    feature: "adoption-cms",
    required: true,
    arguments: "p_expected_version integer, p_content jsonb, p_actor_user_id uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "publish_adoption_instruction_page",
    feature: "adoption-cms",
    required: true,
    arguments: "p_expected_version integer, p_actor_user_id uuid, p_idempotency_key text",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "restore_adoption_instruction_revision",
    feature: "adoption-cms",
    required: true,
    arguments: "p_source_revision_id uuid, p_expected_page_version integer, p_actor_user_id uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "archive_adoption_instruction_draft",
    feature: "adoption-cms",
    required: true,
    arguments: "p_expected_version integer, p_actor_user_id uuid",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "reserve_animal_draft_image_upload",
    feature: "animal-media",
    required: true,
    arguments: "p_animal_id uuid, p_storage_path text",
    returns: "void",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_animal_draft_image_attached",
    feature: "animal-media",
    required: true,
    arguments: "",
    returns: "trigger",
    executeRoles: [],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_expired_animal_draft_image_uploads",
    feature: "animal-media",
    required: true,
    arguments: "p_cutoff timestamptz, p_limit integer",
    returns: "table (animal_id uuid, storage_path text, claimed_at timestamptz)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "queue_animal_publication_media_copy",
    feature: "animal-media",
    required: true,
    arguments: "",
    returns: "trigger",
    executeRoles: [],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_due_animal_publication_media_copies",
    feature: "animal-media",
    required: true,
    arguments: "p_cutoff timestamptz, p_limit integer",
    returns:
      "table (source_path text, public_path text, claimed_at timestamptz, lease_token uuid, attempts integer)",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_animal_publication_media_copied",
    feature: "animal-media",
    required: true,
    arguments: "p_public_path text, p_claimed_at timestamptz",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "publish_animal_publication_once",
    feature: "finance",
    required: true,
    arguments: "p_actor uuid, p_command jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "prepare_content_public_assets",
    feature: "content",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_content_id uuid, p_revision_id uuid, p_expected_version integer, p_idempotency_key text",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "claim_due_content_public_assets",
    feature: "content",
    required: true,
    arguments: "p_cutoff timestamptz, p_limit integer",
    returns: "setof public.content_public_asset",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_claimed_content_public_asset_ready",
    feature: "content",
    required: true,
    arguments: "p_asset_id uuid, p_claimed_at timestamptz",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "set_content_publication_metadata",
    feature: "content",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_content_id uuid, p_expected_version integer, p_values jsonb",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_repaired_animal_publication_media",
    feature: "media-repair",
    required: true,
    arguments: "p_public_path text, p_lease_token uuid",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "mark_repaired_content_public_asset",
    feature: "media-repair",
    required: true,
    arguments: "p_asset_id uuid, p_lease_token uuid",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "fail_animal_publication_media_copy",
    feature: "media-repair",
    required: true,
    arguments:
      "p_public_path text, p_lease_token uuid, p_next_retry_at timestamptz, p_error_code text",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "fail_content_public_asset_copy",
    feature: "media-repair",
    required: true,
    arguments:
      "p_asset_id uuid, p_lease_token uuid, p_next_retry_at timestamptz, p_error_code text",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "get_media_repair_backlog",
    feature: "media-repair",
    required: true,
    arguments: "p_actor_user_id uuid, p_limit integer",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "retry_failed_media_repair",
    feature: "media-repair",
    required: true,
    arguments:
      "p_actor_user_id uuid, p_kind text, p_item_id text, p_reason text, p_cause_corrected boolean",
    returns: "boolean",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "set_supporter_marketing_email",
    feature: "supporter-portal",
    required: true,
    arguments: "p_auth_user_id uuid, p_verified_email text, p_status text",
    returns: "jsonb",
    executeRoles: ["service_role"],
  },
  {
    kind: "function",
    schema: "public",
    name: "public_animal_listing_page",
    feature: "public-animals",
    required: true,
    arguments: "p_filters jsonb",
    returns: "jsonb",
    executeRoles: ["anon", "authenticated", "service_role"],
  },
  {
    kind: "column",
    schema: "public",
    table: "adoption_fees",
    name: "version",
    feature: "adoption-cms",
    required: true,
    type: "integer",
  },
  {
    kind: "column",
    schema: "public",
    table: "dog_friendly_estates",
    name: "version",
    feature: "adoption-cms",
    required: true,
    type: "integer",
  },
  {
    kind: "column",
    schema: "public",
    table: "donation",
    name: "idempotency_key",
    feature: "finance",
    required: true,
    type: "uuid",
  },
  {
    kind: "column",
    schema: "public",
    table: "donation",
    name: "idempotency_fingerprint",
    feature: "finance",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "payment",
    name: "idempotency_key",
    feature: "finance",
    required: true,
    type: "uuid",
  },
  {
    kind: "column",
    schema: "public",
    table: "payment",
    name: "checkout_url",
    feature: "finance",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "payment",
    name: "checkout_attempted_at",
    feature: "finance",
    required: true,
    type: "timestamptz",
  },
  {
    kind: "column",
    schema: "public",
    table: "public_status_token",
    name: "submission_fingerprint",
    feature: "submissions",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_item",
    name: "content_class",
    feature: "content",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_item",
    name: "source_reference",
    feature: "content",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_item",
    name: "content_owner",
    feature: "content",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_item",
    name: "effective_from",
    feature: "content",
    required: true,
    type: "timestamptz",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_item",
    name: "effective_until",
    feature: "content",
    required: true,
    type: "timestamptz",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_public_asset",
    name: "repair_status",
    feature: "media-repair",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_public_asset",
    name: "repair_attempts",
    feature: "media-repair",
    required: true,
    type: "integer",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_public_asset",
    name: "next_retry_at",
    feature: "media-repair",
    required: true,
    type: "timestamptz",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_public_asset",
    name: "last_error_code",
    feature: "media-repair",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_public_asset",
    name: "lease_token",
    feature: "media-repair",
    required: true,
    type: "uuid",
  },
  {
    kind: "column",
    schema: "public",
    table: "animals",
    name: "public_age_band",
    feature: "public-animals",
    required: true,
    type: "text",
  },
  {
    kind: "column",
    schema: "public",
    table: "content_public_asset",
    name: "copy_claimed_at",
    feature: "content",
    required: true,
    type: "timestamptz",
  },
];
