/** Failure-first metadata rejection reproduction; all writes are owned-clone rollbacks. */
import {readFile,writeFile} from "node:fs/promises";
import {randomUUID} from "node:crypto";
import {captureProductionSchema,createProductionClone,snapshot,hash,localSourceState,assertSafeFixtureTables} from "../../../../supabase/rls-tests/helpers/productionSchemaClone";
if(process.env.R01_CRM_ALLOW_LOCAL_FIXTURES!=="1"||process.argv[2]!=="red")throw new Error("Fix1 actual RED opt-in required");
const out="docs/evidence/audit-remediation-20260927/r01-forward/task-6-fix-1-receipts",forward="supabase/migrations/20261001213914_r01_crm_atomic_forward.sql",base="7f7a280f0126cf3e7066fd50fbd2dbc5c8609297";
const oldBinding=JSON.parse(await readFile("docs/evidence/audit-remediation-20260927/r01-forward/task-6-source-binding.json","utf8"));
const paths=[...Object.keys(oldBinding.finalHttpAndGateSourceMap),"docs/evidence/audit-remediation-20260927/r01-forward/task-6-generate.ts","docs/evidence/audit-remediation-20260927/r01-forward/task-6-fix-1-red.ts"];
const blobs=async()=>Object.fromEntries(await Promise.all(paths.map(async p=>[p,{sha256:hash(await readFile(p,"utf8")),canonicalSha256:hash((await readFile(p,"utf8")).replaceAll("\r\n","\n"))}])));
const frozen=await blobs(),text=await readFile(forward,"utf8");if(hash(text)!=="b3ef1a69e4d92362611ede79ba775b5b28904e4acaff166550859e9b57844bc2"||hash(await readFile(out+"/red-executed-forward.sql","utf8"))!==hash(text))throw new Error("Exact original7f SQL required");
const modernUrl="postgresql://postgres:postgres@127.0.0.1:57322/postgres",modernBefore=await localSourceState(modernUrl),capture=await captureProductionSchema(),clone=await createProductionClone(capture),db=clone.sql;
const receipt:Record<string,unknown>={mode:"Fix1 actual metadata acceptance RED",sourceCommit:base,startedAt:new Date().toISOString(),testedExecutableBlobs:frozen,clone:clone.name,zeroApplicationTables:clone.tableCount,schemaParity:true,sourceCatalogHash:hash(capture.catalog),task1Applied:false,productionActions:"schema/catalog read only; no actor/data/DDL"};
const rowState=async()=>{const rows=[];for(const t of await db`select n.nspname||'.'||c.relname name from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p') union all select 'auth.users' order by 1`){const [r]=await db.unsafe(`select count(*)::text count,md5(coalesce(string_agg(to_jsonb(t)::text,E'\\n' order by to_jsonb(t)::text),'')) hash from ${t.name} t`);rows.push([t.name,r]);}return hash(rows);};
const extra=async()=>({auth:await db`select c.relacl::text acl,(select jsonb_agg(jsonb_build_object('name',a.attname,'acl',a.attacl::text) order by a.attnum) from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped) columns from pg_class c where c.oid='auth.users'::regclass`,defaults:await db`select to_jsonb(d) value from pg_default_acl d order by d.defaclrole,d.defaclnamespace,d.defaclobjtype`,native:await db`select to_jsonb(t) trigger,(select jsonb_agg(to_jsonb(d) order by d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid,d.deptype) from pg_depend d where d.classid='pg_trigger'::regclass and d.objid=t.oid) dependencies from pg_trigger t join pg_constraint c on c.oid=t.tgconstraint where c.conrelid in ('public.supporter'::regclass,'public.supporter_role'::regclass,'public.consent'::regclass,'public.admin_user'::regclass) order by t.oid`,ledger:await db`select md5(coalesce(string_agg(to_jsonb(t)::text,E'\n' order by to_jsonb(t)::text),'')) hash from supabase_migrations.schema_migrations t`});
const helperProfiles=async()=>db`select p.oid::regprocedure::text signature,pg_get_userbyid(p.proowner) owner,md5(pg_get_functiondef(p.oid)) definitionMd5,(select jsonb_agg(jsonb_build_object('grantor',pg_get_userbyid(a.grantor),'grantee',case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end,'privilege',a.privilege_type,'grantable',a.is_grantable) order by a.grantor,a.grantee,a.privilege_type) from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a) effectiveAcl from pg_proc p where p.oid in('private.bump_supporter_edit_version()'::regprocedure,'private.bump_supporter_edit_version_from_role()'::regprocedure) order by p.proname`;
try{
 await assertSafeFixtureTables(db,["auth.users","admin_user","supporter","supporter_role","consent","audit_log"]);
 for(const [f,sha] of [["20261001134252_r01_adoption_upload_forward.sql","ca4879d9c93d413941ccc5a13c17d4eba1f70b293169665583e4b23973d1a5f3"],["20261001154743_r01_animal_preference_record_fields.sql","28a93d8679a222f89d193af055285c24e86df06f227a7c527df26829957e9867"],["20261001150925_r01_sponsorship_submission_forward.sql","ca11bb5f0ce73523c7f5734e4d032307665c2357f0fecaf15f8fc593394f857c"],["20261001175310_r01_internship_upload_forward.sql","e64124a1a1d0609b77dae4f41ff82d9166fd857f5d22a6934d761af8f80d4f41"],["20261001193722_r01_animal_draft_archive_forward.sql","2e63db57af4071932da88d7fee29d66b0f8c5fb37e7a29428380b872450fe4ca"]]){const s=await readFile("supabase/migrations/"+f,"utf8");if(hash(s)!==sha)throw new Error("Accepted dependency changed");await db.begin(async tx=>{await tx`set local role postgres`;await tx.unsafe(s);});}
 const actor=randomUUID(),supporter=randomUUID();await db.begin(async tx=>{await tx`set local role postgres`;await tx`insert into auth.users(id,email,email_confirmed_at) values(${actor}::uuid,${actor+"@example.invalid"},now())`;await tx`insert into public.admin_user(auth_user_id,email,role,status) values(${actor}::uuid,${actor+"@example.invalid"},'admin','active')`;await tx`insert into public.supporter(id,name,email) values(${supporter}::uuid,'Fix1 retained',${supporter+"@example.invalid"})`;await tx`insert into public.supporter_role(supporter_id,role) values(${supporter}::uuid,'donor')`;await tx`insert into public.consent(supporter_id,channel,status,source,"timestamp") values(${supporter}::uuid,'email','opt_out','synthetic',now())`;await tx`insert into public.audit_log(actor_user_id,action,entity,entity_id,"timestamp",detail) values(${actor}::uuid,'fix1.preserved','supporter',${supporter},now(),'{}'::jsonb)`;});
 const before=hash(await snapshot(db)),rows=await rowState(),facets=hash(await extra());receipt.completeBaseline={catalog:before,rows,authDefaultsNativeLedger:facets};receipt.helperProfiles=await helperProfiles();receipt.ownerFixtureAuthority=await db`select rolname,rolsuper from pg_roles where rolname in('postgres','supabase_admin') order by rolname`;
 const preserved=async()=>hash(await snapshot(db))===before&&await rowState()===rows&&hash(await extra())===facets;
 const baselineRollback=new Error("Fix1 accepted baseline rollback");let accepted=false;try{await db.begin(async tx=>{await tx`set local role postgres`;await tx.unsafe(text);accepted=true;throw baselineRollback;});}catch(e){if(e!==baselineRollback)throw e;}receipt.normalBaselineAccepted=accepted;receipt.normalBaselineRollbackPreserved=await preserved();if(!accepted||!receipt.normalBaselineRollbackPreserved)throw new Error("No valid baseline for actual RED");
 const cases:({name:string;sql?:string;sig?:string;last?:string;replacement?:string})[]=[];
 for(const name of ["bump_supporter_edit_version","bump_supporter_edit_version_from_role"]){cases.push({name:name+" owner",sql:`alter function private.${name}() owner to supabase_admin`},{name:name+" extra ACL recipient",sql:`set local role postgres;grant execute on function private.${name}() to dashboard_user`},{name:name+" owner EXECUTE grant option",sql:`set local role postgres;grant execute on function private.${name}() to postgres with grant option`});}
 cases.push({name:"role helper missing historical PUBLIC",sql:"set local role postgres;revoke execute on function private.bump_supporter_edit_version_from_role() from public"});
 for(const [sig,last,replacement] of [["public.mutate_crm_supporter_with_audit(text,uuid,jsonb,jsonb,uuid,timestamptz,jsonb)","p_detail jsonb)","p_detail jsonb DEFAULT '{}'::jsonb)"],["public.replace_supporter_roles_atomic(uuid,jsonb)","p_roles jsonb)","p_roles jsonb DEFAULT '[]'::jsonb)"],["public.append_crm_consents_with_audit(jsonb,uuid,uuid,timestamptz,jsonb)","p_detail jsonb)","p_detail jsonb DEFAULT '{}'::jsonb)"],["public.mutate_crm_supporter_if_version_with_audit(uuid,bigint,jsonb,jsonb,uuid,timestamptz,jsonb)","p_detail jsonb)","p_detail jsonb DEFAULT '{}'::jsonb)"],["private.require_crm_supporter_actor(uuid)","p_actor uuid)","p_actor uuid DEFAULT NULL::uuid)"]])cases.push({name:sig+" argument default",sig,last,replacement});
 const results=[];let acceptance=0;
 for(const c of cases){let status="success",setupComplete=false,fixtureProfile:unknown;const rollback=new Error("Fix1 actual accepted drift rollback");try{await db.begin(async tx=>{if(c.sig){await tx`set local role postgres`;await tx.unsafe(text);const [definition]=await tx`select pg_get_functiondef(${c.sig}::regprocedure) value`;if(!definition.value.includes(c.last!))throw new Error("Exact default fixture argument absent");await tx.unsafe(definition.value.replace(c.last!,c.replacement!));fixtureProfile=await tx`select pg_get_function_identity_arguments(p.oid) args,p.pronargdefaults,p.proargdefaults::text defaults,md5(p.prosrc) bodyMd5 from pg_proc p where p.oid=${c.sig}::regprocedure`;}else{await tx.unsafe(c.sql!);fixtureProfile=await helperProfiles();}setupComplete=true;await tx`set local role postgres`;await tx.unsafe(text);throw rollback;});}catch(e){status=e===rollback?"success":((e as {errno?:string}).errno??(e as Error).message);}const keep=await preserved();results.push({case:c.name,status,setupComplete,fixtureProfile,preserved:keep,expected:"55000",actualDefect:status==="success"});console.log(JSON.stringify({case:c.name,status,setupComplete,preserved:keep}));if(!keep||!setupComplete)throw new Error("Fixture setup/preservation failed: "+c.name+" "+status);if(status==="success")acceptance++;else if(status!=="55000")throw new Error("Unexpected fixture/migration result: "+status);}
 receipt.cases=results;receipt.acceptedDriftCount=acceptance;receipt.expectedRefusalCount=cases.length;receipt.result=acceptance?"ACTUAL RED: original7f SQL accepts unreviewed metadata":"No actual RED";if(acceptance!==cases.length)throw new Error("Expected all reviewed acceptance gaps reproduced");process.exitCode=1;
}catch(e){receipt.failure={message:(e as Error).message,errno:(e as {errno?:string}).errno};throw e;}finally{await clone.close();receipt.templatePreserved=clone.templatePreserved;receipt.modernPreserved=await localSourceState(modernUrl)===modernBefore;receipt.frozenInputsPreserved=hash(await blobs())===hash(frozen);receipt.cleanup="normal newly owned clone drop";receipt.completedAt=new Date().toISOString();await writeFile(out+"/red.json",JSON.stringify(receipt,null,2)+"\n");console.log(JSON.stringify({acceptedDriftCount:receipt.acceptedDriftCount,failure:receipt.failure,templatePreserved:receipt.templatePreserved,modernPreserved:receipt.modernPreserved,frozenInputsPreserved:receipt.frozenInputsPreserved}));}
