import { z } from "zod";

/**
 * Animal photo upload rules.
 *
 * Pure: no Supabase import, so the path and validation rules can be tested
 * without a database or a storage service.
 *
 * The defect this exists to close: AnimalForm uploaded every photo to the fixed
 * object path `${animalId}.jpg` with `{ upsert: true }`, *before* writing the
 * database row, and its failure branch returned without touching storage. The
 * previous photograph was therefore overwritten in place the instant a new file
 * was chosen -- so a save that then failed for any reason left the animal with
 * no recoverable original, and a successful replacement destroyed the prior
 * version too. The public URL never changed either, so caches kept serving the
 * old bytes from an address whose content had silently been replaced.
 *
 * These are irreplaceable rescue photographs. The contract is that every upload
 * lands on a NEW immutable path and nothing ever overwrites a public object.
 */

export const ANIMAL_IMAGE_BUCKET = "animal-images";

/** Mirrors the bucket's allowed_mime_types (migration 20260911130000). */
export const ANIMAL_IMAGE_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"] as const;

/** Mirrors the bucket's file_size_limit (8 MiB). */
export const ANIMAL_IMAGE_MAX_BYTES = 8 * 1024 * 1024;

export const animalPhotoDescriptorSchema = z.object({
  fileName: z.string().trim().min(1).max(200),
  mimeType: z.enum(ANIMAL_IMAGE_MIME_TYPES),
  sizeBytes: z.number().int().positive().max(ANIMAL_IMAGE_MAX_BYTES),
});

export type AnimalPhotoDescriptor = z.infer<typeof animalPhotoDescriptorSchema>;

/**
 * Sanitizes a user-supplied file name into a safe Storage path segment.
 *
 * Mirrors `safeFileName` in lib/publicUploads/signedUpload.server.ts. It is
 * duplicated rather than imported because that module carries the `.server.ts`
 * suffix and this one is reachable from the browser bundle; the same split
 * already exists for `contentMediaUpload.ts`.
 */
export function safeAnimalFileName(fileName: string, fallback = "photo.jpg"): string {
  let baseName = fileName.split(/[\\/]/).pop()?.trim() || fallback;
  if (/^\.+$/.test(baseName)) baseName = fallback;
  return baseName.replace(/[^A-Za-z0-9._-]/g, "_");
}

/**
 * Builds the immutable object path for one upload.
 *
 * `version` must be unique per upload. It is generated by the caller rather
 * than derived from a clock here, so the path carries no dependence on server
 * time and two uploads in the same millisecond cannot collide.
 *
 * Keeping the animal id as the first segment means every version of one
 * animal's photographs stays grouped, which is what makes a later reference
 * check and delayed cleanup tractable.
 */
export function animalPhotoPath(input: {
  animalId: string;
  version: string;
  fileName: string;
}): string {
  return `${input.animalId}/${input.version}/${safeAnimalFileName(input.fileName)}`;
}
