import { localisePolicyReason } from "../../../lib/volunteers/policy/messages";
import { defineAdminCopy } from "../i18n/copy";

/** Copy for the advanced policy fields: places, registration windows, roles, quotas, limits and late release. */
export const policyAdvancedCopy = defineAdminCopy({
  zh: {
    /** The four states of a limit, besides a fixed number. */
    limit: { value: "指定數量", unlimited: "不限", inherit: "沿用", unresolved: "未決定" },
    credentials: {
      all: "全部資格 AND",
      any: "任何資格 OR",
      add: "新增資格名稱",
    },
    window: {
      hours_before: "活動前小時",
      calendar_days_before: "香港日曆日前",
      unrestricted: "不限制",
      disabled: "停用",
      inherit: "沿用",
      unresolved: "未決定",
    },
    flag: { true: "是", false: "否", inherit: "沿用", unresolved: "未決定" },
    /** The display name a new role starts with. */
    /** The label "Add role" stores. `policyDefaults.ts` reads this half whatever the admin reads. */
    newRole: "新職務",
    capacity: {
      title: "完整名額設定",
      volunteers: "義工名額",
      visitors: "訪客名額",
      sharedTotal: "共用總名額",
      groupInSharedTotal: "團體計入共用總數",
      groupSizeMode: "團體人數模式",
      groupSizeOptions: { value: "指定範圍", inherit: "沿用", unresolved: "未決定" },
      groupMinimum: "團體最少人數",
      groupMaximum: "團體最多人數",
      roleCounting: "領隊計算方式",
      roleCountingOptions: {
        leader_separate: "領隊另計",
        leader_in_assistants: "領隊包括在助手",
        inherit: "沿用",
        unresolved: "未決定",
      },
    },
    booking: {
      title: "報名及取消窗口",
      windows: {
        individual_open: "個人開放",
        individual_close: "個人截止",
        group_open: "團體開放",
        group_close: "團體截止",
        cancellation_close: "取消截止",
      },
      scenario: "團體情景",
      scenarioOptions: {
        none: "不適用",
        confirmed_group: "有確認團體",
        no_confirmed_group: "沒有確認團體",
      },
      templateLabels: {
        with_group: "有團體時採用的已發布模板",
        without_group: "無團體時採用的已發布模板",
      },
      undecided: "未決定",
      templateNote: "確認團體時按活動日期讀取此模板的已發布版本；未完成或未發布的模板不能套用。",
      freeze: "團體名額凍結",
      freezeOptions: {
        at_group_close: "團體截止時",
        at_session_start: "活動開始時",
        inherit: "沿用",
        unresolved: "未決定",
      },
      lateChange: "遲來團體變更",
      lateChangeOptions: {
        revalidate: "重新驗證",
        manual_review: "人手審核",
        inherit: "沿用",
        unresolved: "未決定",
      },
      waitlistLimit: "候補上限",
      autoApprove: "自動批准",
      allowWaitlist: "容許候補",
    },
    roles: {
      title: "職務名額",
      add: "新增職務",
      key: "識別碼",
      label: "顯示名稱",
      minimum: "最低人數",
      reserved: "保留名額",
      maximum: "最高人數",
      tiers: "可用級別",
      credentials: "職務資格",
      remove: "刪除職務",
    },
    quotas: {
      title: "級別配額",
      add: "新增配額",
      key: "識別碼",
      tiers: "級別",
      maximum: "上限",
      weekdays: "適用星期",
      resolveWeekdays: "解析星期設定",
      remove: "刪除配額",
    },
    daily: {
      title: "每日限制",
      add: "新增限制",
      key: "識別碼",
      tiers: "級別",
      maximum: "上限",
      scope: "範圍",
      scopeOptions: { shelter_day: "同一舍全日", all_shelters_day: "所有場地全日" },
      countMode: "計算方式",
      countOptions: {
        distinct_people: "不同人士",
        attendances: "出席人次",
        inherit: "沿用",
        unresolved: "未決定",
      },
      includeGroupVisitors: "包括團體訪客",
      remove: "刪除限制",
    },
    release: {
      title: "遲段補位規則",
      add: "新增規則",
      unresolved: "未解析：",
      /** A stored reason, as the screen shows it. */
      reasonText: (stored: string) => localisePolicyReason(stored, "zh"),
      /** What separates the reason from the button that removes the rule. */
      afterReason: "",
      remove: "移除",
      key: "識別碼",
      semantics: "釋放方式",
      semanticsOptions: {
        notSet: "待設定",
        dynamic: "動態：條件改變即重新計算",
        once: "一次：觸發後不收回釋放",
      },
      priority: "優先次序",
      withinHours: "活動前小時",
      operator: "門檻比較",
      operatorOptions: { lt: "少於", lte: "不多於" },
      threshold: "門檻",
      action: "動作",
      actionOptions: { release_reserved: "釋放職務保留位", relax_quota: "放寬配額" },
      pool: "保留池",
      quantity: "釋放數量",
      quota: "配額",
      /** A quota in the list of quotas a rule can relax: its identifier, as staff typed it. */
      quotaOption: (_kind: "tier" | "daily", key: string) => key,
      quotaScope: "配額作用範圍",
      quotaScopeOptions: {
        session: "單場",
        shelter_day: "此場地全日",
        all_shelters_day: "跨場地全日",
      },
      anchor: "每日補位時間基準（須明選）",
      anchorOptions: {
        unresolved: "未決定",
        first_session: "同一範圍當日首場開始時間",
        last_session: "同一範圍當日末場開始時間",
      },
      anchorNote: "熟手門檻按同一範圍全日已確認人數計算；所有場次共用當日配額。",
      newMaximum: "新上限",
      receivingTiers: "可接收級別",
      credentials: "資格",
      removeRule: "刪除規則",
    },
    source: "政策來源",
  },
  en: {
    limit: {
      value: "Fixed number",
      unlimited: "Unlimited",
      inherit: "Inherit",
      unresolved: "Undecided",
    },
    credentials: {
      all: "All qualifications (AND)",
      any: "Any qualification (OR)",
      add: "Add a qualification name",
    },
    window: {
      hours_before: "Hours before the session",
      calendar_days_before: "Hong Kong calendar days before",
      unrestricted: "No restriction",
      disabled: "Disabled",
      inherit: "Inherit",
      unresolved: "Undecided",
    },
    flag: { true: "Yes", false: "No", inherit: "Inherit", unresolved: "Undecided" },
    /** Never stored (a policy is data that every language reads); the halves keep one shape. */
    newRole: "New role",
    capacity: {
      title: "Full places settings",
      volunteers: "Volunteer places",
      visitors: "Visitor places",
      sharedTotal: "Shared total places",
      groupInSharedTotal: "Groups count towards the shared total",
      groupSizeMode: "Group size mode",
      groupSizeOptions: { value: "Fixed range", inherit: "Inherit", unresolved: "Undecided" },
      groupMinimum: "Group minimum",
      groupMaximum: "Group maximum",
      roleCounting: "How leaders are counted",
      roleCountingOptions: {
        leader_separate: "Leader counted separately",
        leader_in_assistants: "Leader counted within the assistants",
        inherit: "Inherit",
        unresolved: "Undecided",
      },
    },
    booking: {
      title: "Registration and cancellation windows",
      windows: {
        individual_open: "Individual opening",
        individual_close: "Individual closing",
        group_open: "Group opening",
        group_close: "Group closing",
        cancellation_close: "Cancellation closing",
      },
      scenario: "Group situation",
      scenarioOptions: {
        none: "Not applicable",
        confirmed_group: "Confirmed group",
        no_confirmed_group: "No confirmed group",
      },
      templateLabels: {
        with_group: "Published template to use when there is a group",
        without_group: "Published template to use when there is no group",
      },
      undecided: "Undecided",
      templateNote:
        "When a group is confirmed, the published version of this template for the session date is used. A template that is unfinished or not published cannot be applied.",
      freeze: "Group size freeze",
      freezeOptions: {
        at_group_close: "At group closing",
        at_session_start: "At session start",
        inherit: "Inherit",
        unresolved: "Undecided",
      },
      lateChange: "Late group change",
      lateChangeOptions: {
        revalidate: "Revalidate",
        manual_review: "Manual review",
        inherit: "Inherit",
        unresolved: "Undecided",
      },
      waitlistLimit: "Waitlist limit",
      autoApprove: "Auto-approve",
      allowWaitlist: "Allow waitlist",
    },
    roles: {
      title: "Volunteer role places",
      add: "Add role",
      key: "Identifier",
      label: "Display name",
      minimum: "Minimum people",
      reserved: "Reserved places",
      maximum: "Maximum people",
      tiers: "Allowed tiers",
      credentials: "Role qualifications",
      remove: "Delete role",
    },
    quotas: {
      title: "Tier quotas",
      add: "Add quota",
      key: "Identifier",
      tiers: "Tiers",
      maximum: "Maximum",
      weekdays: "Weekdays it applies to",
      resolveWeekdays: "Set the weekdays",
      remove: "Delete quota",
    },
    daily: {
      title: "Daily limits",
      add: "Add limit",
      key: "Identifier",
      tiers: "Tiers",
      maximum: "Maximum",
      scope: "Scope",
      scopeOptions: {
        shelter_day: "Whole day, same venue",
        all_shelters_day: "Whole day, all venues",
      },
      countMode: "Counting method",
      countOptions: {
        distinct_people: "Different people",
        attendances: "Attendances",
        inherit: "Inherit",
        unresolved: "Undecided",
      },
      includeGroupVisitors: "Include group visitors",
      remove: "Delete limit",
    },
    release: {
      title: "Late release rules",
      add: "Add rule",
      unresolved: "Unresolved: ",
      reasonText: (stored: string) => localisePolicyReason(stored, "en"),
      afterReason: " ",
      remove: "Remove",
      key: "Identifier",
      semantics: "Release mode",
      semanticsOptions: {
        notSet: "Not set yet",
        dynamic: "Dynamic: recalculated when the condition changes",
        once: "One-off: once triggered, the release is not taken back",
      },
      priority: "Priority",
      withinHours: "Hours before the session",
      operator: "Threshold comparison",
      operatorOptions: { lt: "Fewer than", lte: "No more than" },
      threshold: "Threshold",
      action: "Action",
      actionOptions: {
        release_reserved: "Release reserved role places",
        relax_quota: "Relax a quota",
      },
      pool: "Role to release from",
      quantity: "Number to release",
      quota: "Quota",
      quotaOption: (kind: "tier" | "daily", key: string) =>
        `${kind === "tier" ? "Tier quota" : "Daily limit"}: ${key}`,
      quotaScope: "Quota scope",
      quotaScopeOptions: {
        session: "Single session",
        shelter_day: "Whole day at this venue",
        all_shelters_day: "Whole day across venues",
      },
      anchor: "Daily time basis (must be chosen)",
      anchorOptions: {
        unresolved: "Undecided",
        first_session: "Start of the first session that day in the same scope",
        last_session: "Start of the last session that day in the same scope",
      },
      anchorNote:
        "The threshold for experienced volunteers uses the people confirmed for the whole day in the same scope. All sessions share the day's quota.",
      newMaximum: "New maximum",
      receivingTiers: "Tiers that can receive",
      credentials: "Qualifications",
      removeRule: "Delete rule",
    },
    source: "Policy source",
  },
});
