import { defineAdminCopy } from "../i18n/copy";
import { formatAdminNumber, pluralCount } from "../i18n/format";

/**
 * Copy for a registration's detail page (`VolunteerRegistrationDetail`) and the volunteers and
 * activities management page (`VolunteerManagement`). The buttons that change a registration are
 * labelled with a status in Chinese ("已批准"), as they have always been, and with a verb in English
 * ("Approve").
 */
export const volunteerRegistrationCopy = defineAdminCopy({
  zh: {
    /** The button that moves a registration to a status. */
    transitions: {
      pending: "待審批",
      approved: "已批准",
      waitlisted: "候補中",
      rejected: "已拒絕",
      cancelled: "已取消",
    },
    /** The verb on the reject confirmation (existing wording: pageCopy/pledgeCopy.ts reject). */
    rejectVerb: "拒絕",
    /** The button that records an attendance status. */
    attendanceActions: {
      not_marked: "未記錄",
      attended: "已出席",
      completed: "已完成",
      no_show: "缺席",
    },
    nothingToDo: "無需處理",
    confirmReject: (name: string) => `確定拒絕 ${name} 的報名？`,
    detail: {
      viewProfile: "查看義工個人詳情",
      profileNotLinked: "身份未連結：前往舊報名身份核對",
      notFound: "找不到義工報名。",
      back: "返回義工管理",
      attendance: (label: string) => `出席：${label}`,
      activity: "活動",
      date: "日期",
      participants: "人數",
      type: "類型",
      group: "團體",
      age: "年齡",
      responsibleAdult: "負責成人",
      volunteerHours: "義工時數",
      notes: "備註",
      placesLeft: "剩餘名額",
      none: "-",
      correct: "更正出席事實（保留原紀錄）",
      correctionReason: "更正原因",
    },
    management: {
      title: "義工與活動管理",
      intro: "建立活動、審批報名，並記錄出席。",
      refresh: "重新整理",
      addActivity: "新增活動",
      stats: {
        pending: "本頁活動待審批人數",
        upcoming: "本頁即將舉行的活動",
        shown: "目前顯示的報名",
      },
      form: {
        title: "活動名稱",
        type: "活動類型",
        startsAt: "開始時間",
        endsAt: "結束時間",
        optional: "可留空",
        location: "地點",
        capacity: "名額",
        capacityHint: "可批准的總人數",
        minAge: "最低年齡",
        minAgeHint: "個人報名下限",
        settings: "報名設定",
        autoApprove: "自動審批",
        allowGroups: "接受團體",
        create: "建立活動",
        creating: "建立中…",
        cancel: "取消",
        failed: "建立失敗，請檢查輸入內容後再試。",
      },
      activities: {
        title: "活動",
        searchPlaceholder: "搜尋活動名稱或地點",
        searchLabel: "搜尋活動",
        empty: "尚未建立任何活動。按「新增活動」開始。",
        pagerLabel: "活動",
        columns: {
          activity: "活動",
          date: "日期",
          places: "名額",
          status: "狀態",
          actions: "操作",
        },
        until: (end: string) => `至 ${end}`,
        pendingAndWaitlisted: (pending: number, waitlisted: number) =>
          `待審 ${pending} · 候補 ${waitlisted}`,
        showing: "顯示中",
        viewRegistrations: "查看報名",
        closeRegistration: "關閉報名",
        publish: "發布",
        duplicate: "複製",
      },
      registrations: {
        title: "報名",
        statusFilter: "按狀態篩選",
        allStatuses: "全部狀態",
        attendanceFilter: "按出席狀況篩選",
        allAttendance: "全部出席狀況",
        searchPlaceholder: "搜尋姓名、電郵或電話",
        searchLabel: "搜尋報名人",
        pagerLabel: "報名",
        columns: {
          registrant: "報名人",
          activity: "報名活動",
          people: "人數 / 形式",
          status: "狀態",
          actions: "操作",
        },
        organisation: (name: string) => `機構：${name}`,
        activityNotLoaded: "活動資料未載入",
        peopleCount: (count: number) => `${count} 人`,
        youngest: (age: number) => `最小 ${age} 歲`,
        guardianConsent: "需家長同意",
        attendance: (label: string) => `出席：${label}`,
        registeredOn: (date: string) => `${date} 報名`,
        markCompleted: "標記完成",
        confirmReject: (name: string) => `確定拒絕 ${name} 的報名？對方會收到通知。`,
        cardPeople: "人數 / 形式",
        cardPeopleValue: (count: number, type: string) => `${count} 人 · ${type}`,
        cardAttendance: "出席",
        cardOrganisation: "機構",
        cardGuardian: "家長同意",
        guardianValue: (name: string, phone: string | null) => `${name} · ${phone ?? "未提供電話"}`,
        filterBannerBefore: "只顯示「",
        filterBannerAfter: (date: string) => `」（${date}）的報名`,
        clearFilter: "清除篩選",
        emptyForActivity: (title: string) => `「${title}」目前沒有符合條件的報名。`,
        empty: "沒有符合條件的報名。試試放寬篩選條件。",
      },
    },
  },
  en: {
    transitions: {
      pending: "Mark pending",
      approved: "Approve",
      waitlisted: "Add to waitlist",
      rejected: "Reject",
      cancelled: "Mark cancelled",
    },
    rejectVerb: "Reject",
    attendanceActions: {
      not_marked: "Mark not recorded",
      attended: "Mark attended",
      completed: "Mark completed",
      no_show: "Mark no-show",
    },
    nothingToDo: "Nothing to do",
    confirmReject: (name: string) => `Reject the registration of ${name}?`,
    detail: {
      viewProfile: "View volunteer details",
      profileNotLinked: "Profile not linked: match this old registration to a profile",
      notFound:
        "Volunteer registration not found. Go back to volunteer management and choose another.",
      back: "Back to volunteer management",
      attendance: (label: string) => `Attendance: ${label}`,
      activity: "Activity",
      date: "Date",
      participants: "Participants",
      type: "Type",
      group: "Group",
      age: "Age",
      responsibleAdult: "Responsible adult",
      volunteerHours: "Volunteer hours",
      notes: "Notes",
      placesLeft: "Places left",
      none: "-",
      correct: "Correct the attendance record (the original record is kept)",
      correctionReason: "Reason for the correction",
    },
    management: {
      title: "Volunteers and activities",
      intro: "Create activities, approve registrations and record attendance.",
      refresh: "Refresh",
      addActivity: "Add activity",
      stats: {
        pending: "People awaiting approval in this page's activities",
        upcoming: "Upcoming activities on this page",
        shown: "Registrations shown",
      },
      form: {
        title: "Activity name",
        type: "Activity type",
        startsAt: "Start time",
        endsAt: "End time",
        optional: "Optional",
        location: "Location",
        capacity: "Places",
        capacityHint: "Total number of people who can be approved",
        minAge: "Minimum age",
        minAgeHint: "Lower limit for individual registrations",
        settings: "Registration settings",
        autoApprove: "Approve automatically",
        allowGroups: "Accept groups",
        create: "Create activity",
        creating: "Creating…",
        cancel: "Cancel",
        failed: "Could not create the activity. Check the details and try again.",
      },
      activities: {
        title: "Activities",
        searchPlaceholder: "Search by activity name or location",
        searchLabel: "Search activities",
        empty: "No activities yet. Choose Add activity to start.",
        pagerLabel: "Activities",
        columns: {
          activity: "Activity",
          date: "Date",
          places: "Places",
          status: "Status",
          actions: "Actions",
        },
        until: (end: string) => `to ${end}`,
        pendingAndWaitlisted: (pending: number, waitlisted: number) =>
          `Pending ${formatAdminNumber(pending, "en")} · Waitlisted ${formatAdminNumber(waitlisted, "en")}`,
        showing: "Showing",
        viewRegistrations: "View registrations",
        closeRegistration: "Close registration",
        publish: "Publish",
        duplicate: "Duplicate",
      },
      registrations: {
        title: "Registrations",
        statusFilter: "Filter by status",
        allStatuses: "All statuses",
        attendanceFilter: "Filter by attendance",
        allAttendance: "All attendance statuses",
        searchPlaceholder: "Search by name, email or phone",
        searchLabel: "Search registrants",
        pagerLabel: "Registrations",
        columns: {
          registrant: "Registrant",
          activity: "Activity registered for",
          people: "People / type",
          status: "Status",
          actions: "Actions",
        },
        organisation: (name: string) => `Organisation: ${name}`,
        activityNotLoaded: "Activity details not loaded",
        peopleCount: (count: number) => pluralCount(count, "person", "people"),
        youngest: (age: number) => `Youngest ${formatAdminNumber(age, "en")} years old`,
        guardianConsent: "Guardian consent needed",
        attendance: (label: string) => `Attendance: ${label}`,
        registeredOn: (date: string) => `Registered on ${date}`,
        markCompleted: "Mark completed",
        confirmReject: (name: string) =>
          `Reject the registration of ${name}? They will be notified.`,
        cardPeople: "People / type",
        cardPeopleValue: (count: number, type: string) =>
          `${pluralCount(count, "person", "people")} · ${type}`,
        cardAttendance: "Attendance",
        cardOrganisation: "Organisation",
        cardGuardian: "Guardian consent",
        guardianValue: (name: string, phone: string | null) =>
          `${name} · ${phone ?? "no phone provided"}`,
        filterBannerBefore: "Showing only registrations for ",
        filterBannerAfter: (date: string) => ` (${date})`,
        clearFilter: "Clear filter",
        emptyForActivity: (title: string) => `No registrations match for ${title}.`,
        empty: "No registrations match. Try loosening the filters.",
      },
    },
  },
});
