import { defineAdminCopy } from "../i18n/copy";
import { formatAdminNumber, pluralCount } from "../i18n/format";

/** Copy for the adopter detail screen. */
export const adopterDetailCopy = defineAdminCopy({
  zh: {
    backToAdopters: "返回領養人",
    notFound: "找不到領養人檔案",
    refresh: "重新整理",
    latestCase: "最新個案",
    blacklisted: "黑名單",
    clear: "正常",
    optedIn: "已同意",
    optedOut: "已拒絕",
    noCaseHistory: "沒有個案紀錄",
    noSuccessfulAdoptions: "沒有成功領養紀錄",
    loadFollowupStatusesError: (message: string) => `無法載入跟進狀態: ${message}`,
    followupStatusHint: "現有跟進工作如下。新增或編輯工作可能需要狀態設定。",
    adopterFollowups: "領養人跟進工作",
    linkedCases: (count: number) => `${formatAdminNumber(count, "zh")} 個相關個案`,
    finalizedAdoptions: (count: number) => `${formatAdminNumber(count, "zh")} 個已完成領養`,
    sections: {
      profile: "檔案摘要",
      activity: "活動",
      household: "家庭資料",
      caseHistory: "個案紀錄",
      successfulAdoptions: "成功領養",
    },
    labels: {
      applicant: "申請人",
      requestedAnimal: "申請動物",
      dates: "日期",
      status: "狀態",
      action: "操作",
      openCase: "開啟個案",
      caseNumber: "個案編號",
      animal: "動物",
      fee: "費用",
      approval: "批核",
      pickup: "接領",
      created: "建立",
      closed: "結束",
      displayName: "顯示名稱",
      chineseName: "中文名",
      englishName: "英文名",
      phone: "電話",
      email: "電郵",
      supporterId: "捐款人 ID",
      livingArea: "居住地區",
      blacklistStatus: "黑名單狀態",
      emailConsent: "電郵同意",
      whatsappConsent: "WhatsApp 同意",
      latestCase: "最新個案",
      blacklistReason: "黑名單原因",
      openCases: "未完成個案",
      successfulAdoptions: "成功領養",
      openFollowups: "未完成跟進",
      gender: "性別",
      birthday: "生日",
      occupation: "職業",
      facebook: "Facebook",
      householdSize: "家庭人數",
      monthlyHouseholdIncome: "家庭月入",
      floorArea: "單位面積",
      address: "地址",
    },
  },
  en: {
    backToAdopters: "Back to adopters",
    notFound: "Adopter profile not found. Go back to the adopters list and choose another one.",
    refresh: "Refresh",
    latestCase: "Latest case",
    blacklisted: "Blacklisted",
    clear: "Clear",
    optedIn: "Opted in",
    optedOut: "Opted out",
    noCaseHistory: "No case history",
    noSuccessfulAdoptions: "No successful adoptions recorded",
    loadFollowupStatusesError: (message: string) =>
      `Could not load follow-up statuses (${message}). Refresh the page to try again.`,
    followupStatusHint:
      "Existing follow-ups are shown below. Creating or editing a task needs these statuses, so check the status settings.",
    adopterFollowups: "Adopter follow-ups",
    linkedCases: (count: number) => pluralCount(count, "linked case"),
    finalizedAdoptions: (count: number) => pluralCount(count, "finalised adoption"),
    sections: {
      profile: "Profile summary",
      activity: "Activity",
      household: "Household details",
      caseHistory: "Case history",
      successfulAdoptions: "Successful adoptions",
    },
    labels: {
      applicant: "Applicant",
      requestedAnimal: "Requested animal",
      dates: "Dates",
      status: "Status",
      action: "Action",
      openCase: "Open case",
      caseNumber: "Case number",
      animal: "Animal",
      fee: "Fee",
      approval: "Approval",
      pickup: "Pickup",
      created: "Created",
      closed: "Closed",
      displayName: "Display name",
      chineseName: "Chinese name",
      englishName: "English name",
      phone: "Phone",
      email: "Email",
      supporterId: "Supporter ID",
      livingArea: "Living area",
      blacklistStatus: "Blacklist status",
      emailConsent: "Email consent",
      whatsappConsent: "WhatsApp consent",
      latestCase: "Latest case",
      blacklistReason: "Blacklist reason",
      openCases: "Open cases",
      successfulAdoptions: "Successful adoptions",
      openFollowups: "Open follow-ups",
      gender: "Gender",
      birthday: "Birthday",
      occupation: "Occupation",
      facebook: "Facebook",
      householdSize: "Household size",
      monthlyHouseholdIncome: "Monthly household income",
      floorArea: "Floor area",
      address: "Address",
    },
  },
});
