import { defineAdminCopy } from "../i18n/copy";
import { pluralCount } from "../i18n/format";
import { localizedText } from "../i18n/localizedText";

/**
 * Copy for the animal pipeline screen.
 *
 * The pipeline was built in English, so most of its Chinese column is the English text the
 * screen has always shown, kept word for word so that the Chinese admin does not change.
 * Only the paging, the empty state and the unsaved-changes prompt were ever in Chinese.
 * The English column is the reviewed English admin copy.
 */
export const animalPipelineCopy = defineAdminCopy({
  zh: {
    title: "Animal pipeline",
    subtitle: "Internal lifecycle, placement, support pool, and medical readiness.",
    refresh: "Refresh",
    searchLabel: "Search animal pipeline",
    searchPlaceholder: "Search name, code, cage, position",
    filters: {
      statusLabel: "Filter by lifecycle status",
      typeLabel: "Filter by animal type",
      adoptableLabel: "Filter by adoptable flag",
      supportPoolLabel: "Filter by support pool flag",
      positionLabel: "Filter by current position",
      allPositions: "All positions",
      noPosition: "No position",
    },
    statusOptions: {
      all: "All statuses",
      available: "Available",
      fostered: "Fostered",
      adopted: "Adopted",
    },
    typeOptions: { all: "All types", cat: "Cats", dog: "Dogs", sponsor: "Sponsor" },
    adoptableOptions: {
      all: "Any adoptable flag",
      adoptable: "Adoptable",
      not_adoptable: "Not adoptable",
    },
    supportPoolOptions: {
      all: "Any support pool flag",
      inside: "Inside support pool",
      outside: "Outside support pool",
    },
    unknownOptions: { unknown: "Unknown", yes: "Yes", no: "No" },
    columns: {
      animal: "Animal",
      lifecycle: "Lifecycle",
      flags: "Flags",
      position: "Position",
      arrival: "Arrival",
      profile: "Profile",
    },
    updateLifecycle: (name: string) => `Update ${name} lifecycle`,
    animalSubline: (nameEn: string, type: string, age: string) => `${nameEn} / ${type} / ${age}`,
    flags: {
      adoptable: "Adoptable",
      notAdoptable: "Not adoptable",
      supportPool: "Support pool",
      chip: (value: boolean | null) => `Chip ${value === null ? "-" : value ? "Y" : "N"}`,
      neutered: (value: boolean | null) => `Desex ${value === null ? "-" : value ? "Y" : "N"}`,
    },
    cage: (cage: string) => `Cage ${cage}`,
    edit: "Edit",
    editProfile: "Edit profile",
    counts: {
      shown: (count: number) => `${count} shown`,
      matching: (count: number) => `${count} matching total`,
      adoptable: (count: number) => `${count} adoptable on page`,
      supportPool: (count: number) => `${count} in support pool on page`,
    },
    groupBy: { status: "Status", position: "Position" },
    empty: "沒有符合篩選條件的動物。",
    animalCount: (count: number) => `${count} animals`,
    page: (page: number, pageCount: number) => `第 ${page} 頁，共 ${pageCount} 頁`,
    rowsPerPage: "Rows per page",
    previous: "上一頁",
    next: "下一頁",
    discardConfirm: "尚未儲存的變更將會遺失，確定關閉？",
    unknownPosition: "Unknown position",
    unknownSource: "Unknown source",
    sourceOption: (nameZh: string, nameEn: string | null) =>
      `${nameZh}${nameEn ? ` / ${nameEn}` : ""}`,
    dialog: {
      title: (name: string | null) => `Internal profile${name ? `: ${name}` : ""}`,
      description: "Placement, intake, medical, and coordinator-only notes.",
      internalCode: "Internal code",
      internalCodePlaceholder: "CAT-001",
      arrivalDate: "Arrival date",
      arrivalSource: "Arrival source",
      noSourcesConfigured: "No sources configured",
      noSource: "No source",
      noSourcesHint: "No arrival sources are configured.",
      currentPosition: "Current position",
      noPositionsConfigured: "No positions configured",
      noPositionsHint: "No animal positions are configured.",
      positionOption: (name: string, type: string) => `${name} (${type})`,
      cage: "Cage",
      cagePlaceholder: "A-12",
      microchip: "Microchip",
      microchipStatus: "Microchip status",
      chipRemarks: "Chip remarks",
      neutered: "Desexed",
      neuteredStatus: "Desexed status",
      neuteredDate: "Desexed date",
      neuteredRemarks: "Desex remarks",
      adoptable: "Adoptable",
      adoptableHint: "Controls internal readiness filters.",
      supportPool: "Support pool",
      supportPoolHint: "Marks animals needing internal support.",
      supportPoolSwitch: "Inside support pool",
      adoptedDate: "Adopted date",
      deceasedDate: "Deceased date",
      internalRemarks: "Internal remarks",
      cancel: "Cancel",
      saving: "Saving",
      save: "Save profile",
      tasksTitle: "Animal tasks",
      tasksSubtitle: "Open coordinator work for this animal",
    },
  },
  en: {
    title: "Animal pipeline",
    subtitle: "Internal lifecycle, placement, support pool and medical readiness.",
    refresh: "Refresh",
    searchLabel: "Search animal pipeline",
    searchPlaceholder: "Search name, code, cage or position",
    filters: {
      statusLabel: "Filter by lifecycle status",
      typeLabel: "Filter by animal type",
      adoptableLabel: "Filter by adoptable flag",
      supportPoolLabel: "Filter by support pool flag",
      positionLabel: "Filter by current position",
      allPositions: "All positions",
      noPosition: "No position",
    },
    statusOptions: {
      all: "All statuses",
      available: "Available",
      fostered: "Fostered",
      adopted: "Adopted",
    },
    typeOptions: { all: "All types", cat: "Cats", dog: "Dogs", sponsor: "Sponsor" },
    adoptableOptions: {
      all: "Any adoptable flag",
      adoptable: "Adoptable",
      not_adoptable: "Not adoptable",
    },
    supportPoolOptions: {
      all: "Any support pool flag",
      inside: "Inside support pool",
      outside: "Outside support pool",
    },
    unknownOptions: { unknown: "Unknown", yes: "Yes", no: "No" },
    columns: {
      animal: "Animal",
      lifecycle: "Lifecycle",
      flags: "Flags",
      position: "Position",
      arrival: "Arrival",
      profile: "Profile",
    },
    updateLifecycle: (name: string) => `Update lifecycle for ${name}`,
    animalSubline: (_nameEn: string, type: string, age: string) => `${type} / ${age}`,
    flags: {
      adoptable: "Adoptable",
      notAdoptable: "Not adoptable",
      supportPool: "Support pool",
      chip: (value: boolean | null) =>
        `Microchip: ${value === null ? "unknown" : value ? "yes" : "no"}`,
      neutered: (value: boolean | null) =>
        `Neutered: ${value === null ? "unknown" : value ? "yes" : "no"}`,
    },
    cage: (cage: string) => `Cage ${cage}`,
    edit: "Edit",
    editProfile: "Edit profile",
    counts: {
      shown: (count: number) => `${count} shown`,
      matching: (count: number) => `${count} matching in total`,
      adoptable: (count: number) => `${count} adoptable on this page`,
      supportPool: (count: number) => `${count} in the support pool on this page`,
    },
    groupBy: { status: "Status", position: "Position" },
    empty: "No animals match these filters.",
    animalCount: (count: number) => pluralCount(count, "animal"),
    page: (page: number, pageCount: number) => `Page ${page} of ${pageCount}`,
    rowsPerPage: "Rows per page",
    previous: "Previous",
    next: "Next",
    discardConfirm: "Your unsaved changes will be lost. Close the profile anyway?",
    unknownPosition: "Unknown position",
    unknownSource: "Unknown source",
    sourceOption: (nameZh: string, nameEn: string | null) => localizedText(nameZh, nameEn, "en"),
    dialog: {
      title: (name: string | null) => `Internal profile${name ? `: ${name}` : ""}`,
      description: "Placement, intake, medical and coordinator-only notes.",
      internalCode: "Internal code",
      internalCodePlaceholder: "CAT-001",
      arrivalDate: "Arrival date",
      arrivalSource: "Arrival source",
      noSourcesConfigured: "No sources configured",
      noSource: "No source",
      noSourcesHint: "No arrival sources are configured.",
      currentPosition: "Current position",
      noPositionsConfigured: "No positions configured",
      noPositionsHint: "No animal positions are configured.",
      positionOption: (name: string, type: string) => `${name} (${type})`,
      cage: "Cage",
      cagePlaceholder: "A-12",
      microchip: "Microchip",
      microchipStatus: "Microchip status",
      chipRemarks: "Microchip remarks",
      neutered: "Neutered",
      neuteredStatus: "Neutered status",
      neuteredDate: "Neutered date",
      neuteredRemarks: "Neutering remarks",
      adoptable: "Adoptable",
      adoptableHint: "Controls the internal readiness filters.",
      supportPool: "Support pool",
      supportPoolHint: "Marks animals that need internal support.",
      supportPoolSwitch: "Inside support pool",
      adoptedDate: "Adopted date",
      deceasedDate: "Deceased date",
      internalRemarks: "Internal remarks",
      cancel: "Cancel",
      saving: "Saving...",
      save: "Save profile",
      tasksTitle: "Animal tasks",
      tasksSubtitle: "Open coordinator work for this animal",
    },
  },
});
