import { defineAdminCopy } from "../i18n/copy";

/** Copy for the adoption case detail screen. */
export const caseDetailCopy = defineAdminCopy({
  zh: {
    backToCases: "返回個案",
    notFound: "找不到個案",
    refresh: "重新整理",
    statusesError: (message: string) => `無法載入狀態: ${message}`,
    noDataCaptured: "沒有紀錄資料",
    yes: "是",
    no: "否",
    notFinalized: "未完成",
    auditSummary: "審核摘要",
    auditSubtitle: "根據目前個案資料整理",
    sections: {
      applicant: "申請人",
      publicSubmission: "公開申請",
      rankedAnimalPreferences: "動物偏好排序",
      visitPreferences: "探訪偏好",
      questionnaire: "問卷資料",
      photos: "申請相片",
      statusLink: "狀態連結",
      assessmentPreferences: "評估及偏好",
      statusControls: "狀態控制",
    },
    labels: {
      currentStatus: "目前狀態",
      created: "建立日期",
      closed: "結束日期",
      matches: "配對",
      approvedMatches: "已批核配對",
      followups: "跟進工作",
      finalized: "完成狀態",
      adoptionFee: "領養費",
      name: "姓名",
      phone: "電話",
      email: "電郵",
      address: "地址",
      supporterId: "捐款人 ID",
      adopterProfileId: "領養人檔案 ID",
      requestedAnimal: "申請動物",
      animalType: "動物類別",
      housingType: "住所類別",
      familySize: "家庭人數",
      existingPets: "現有寵物",
      submitted: "提交日期",
      reason: "申請原因",
      assessment: "評估",
      preferences: "偏好",
      caseStatus: "個案狀態",
      note: "備註",
      rank: "排序",
      animal: "動物",
      type: "類別",
      dateRange: "日期範圍",
      timeWindows: "可選時段",
      language: "語言",
      preferredContactMethod: "偏好聯絡方式",
      termsVersion: "條款版本",
      fileName: "檔案",
      mimeType: "格式",
      size: "大小",
      uploaded: "上載時間",
      expiresAt: "到期",
      revokedAt: "撤銷",
      lastViewedAt: "最後查看",
    },
    questionnaireGroups: {
      contact: "聯絡",
      home: "家居",
      readiness: "準備",
    },
    photoCategories: {
      home: "家居",
      window: "窗戶",
      living: "生活空間",
    },
    contactMethods: {
      phone: "電話",
      whatsapp: "WhatsApp",
      email: "電郵",
    },
    noPublicDetail: "未有公開申請詳細資料",
    noVisitPreference: "未有探訪偏好",
    noPhotos: "未有相片",
    noStatusToken: "未有狀態連結紀錄",
    activeStatusLink: "有效",
    revokedStatusLink: "已撤銷",
    openPhoto: "開啟相片",
    openingPhoto: "開啟中...",
    photoOpenFailed: (message: string) => `無法開啟相片: ${message}`,
    chooseStatus: "選擇狀態",
    optionalStatusNote: "選填狀態備註",
    saveStatus: "儲存狀態",
  },
  en: {
    backToCases: "Back to cases",
    notFound: "Case not found. Go back to the cases list and choose another case.",
    refresh: "Refresh",
    statusesError: (message: string) =>
      `Could not load statuses (${message}). Refresh the page to try again.`,
    noDataCaptured: "No data captured",
    yes: "Yes",
    no: "No",
    notFinalized: "Not finalised",
    auditSummary: "Review summary",
    auditSubtitle: "Summary from current case data",
    sections: {
      applicant: "Applicant",
      publicSubmission: "Public submission",
      rankedAnimalPreferences: "Ranked animal preferences",
      visitPreferences: "Visit preferences",
      questionnaire: "Questionnaire",
      photos: "Application photos",
      statusLink: "Status link",
      assessmentPreferences: "Assessment and preferences",
      statusControls: "Status controls",
    },
    labels: {
      currentStatus: "Current status",
      created: "Created",
      closed: "Closed",
      matches: "Matches",
      approvedMatches: "Approved matches",
      followups: "Follow-ups",
      finalized: "Finalised",
      adoptionFee: "Adoption fee",
      name: "Name",
      phone: "Phone",
      email: "Email",
      address: "Address",
      supporterId: "Supporter ID",
      adopterProfileId: "Adopter profile ID",
      requestedAnimal: "Requested animal",
      animalType: "Animal type",
      housingType: "Housing type",
      familySize: "Family size",
      existingPets: "Existing pets",
      submitted: "Submitted",
      reason: "Reason",
      assessment: "Assessment",
      preferences: "Preferences",
      caseStatus: "Case status",
      note: "Note",
      rank: "Rank",
      animal: "Animal",
      type: "Type",
      dateRange: "Date range",
      timeWindows: "Time windows",
      language: "Language",
      preferredContactMethod: "Preferred contact",
      termsVersion: "Terms version",
      fileName: "File",
      mimeType: "Format",
      size: "Size",
      uploaded: "Uploaded",
      expiresAt: "Expires",
      revokedAt: "Revoked",
      lastViewedAt: "Last viewed",
    },
    questionnaireGroups: {
      contact: "Contact",
      home: "Home",
      readiness: "Readiness",
    },
    photoCategories: {
      home: "Home",
      window: "Window",
      living: "Living space",
    },
    contactMethods: {
      phone: "Phone",
      whatsapp: "WhatsApp",
      email: "Email",
    },
    noPublicDetail: "No public application detail captured",
    noVisitPreference: "No visit preference captured",
    noPhotos: "No photos uploaded",
    noStatusToken: "No status link recorded",
    activeStatusLink: "Active",
    revokedStatusLink: "Revoked",
    openPhoto: "Open photo",
    openingPhoto: "Opening...",
    photoOpenFailed: (message: string) => `Could not open the photo (${message}). Try again.`,
    chooseStatus: "Choose status",
    optionalStatusNote: "Optional status note",
    saveStatus: "Save status",
  },
});
