/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as SponsorsIdRouteImport } from './routes/sponsors_.$id'
import { Route as ReportAuditRouteImport } from './routes/report/audit'
import { Route as ReportAdoptionRouteImport } from './routes/report/adoption'
import { Route as ApiDonationsRouteImport } from './routes/api/donations'
import { Route as AnimalsDogRouteImport } from './routes/animals/dog'
import { Route as AnimalsCatRouteImport } from './routes/animals/cat'
import { Route as AdoptionInstructionsRouteImport } from './routes/adoption/instructions'
import { Route as AdoptionApplyRouteImport } from './routes/adoption/apply'
import { Route as AdminSupportersRouteImport } from './routes/admin/supporters'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AboutTnrRouteImport } from './routes/about/tnr'
import { Route as AboutTeamRouteImport } from './routes/about/team'
import { Route as AboutPrivacyRouteImport } from './routes/about/privacy'
import { Route as AboutCccpRouteImport } from './routes/about/cccp'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksPaypalRouteImport } from './routes/api/webhooks/paypal'
import { Route as ApiAdminSupportersRouteImport } from './routes/api/admin/supporters'
import { Route as ApiAdminReceiptsRouteImport } from './routes/api/admin/receipts'
import { Route as ApiAdminPaymentsRouteImport } from './routes/api/admin/payments'
import { Route as AnimalsDogIdRouteImport } from './routes/animals/dog_.$id'
import { Route as AnimalsCatIdRouteImport } from './routes/animals/cat_.$id'
import { Route as AdminSupportersIdRouteImport } from './routes/admin/supporters/$id'
import { Route as AdminAnimalsNewRouteImport } from './routes/admin/animals/new'
import { Route as ApiAdminSupportersIdRouteImport } from './routes/api/admin/supporters/$id'
import { Route as ApiAdminExportsSupportersDotcsvRouteImport } from './routes/api/admin/exports/supporters[.]csv'
import { Route as ApiAdminExportsDonationsDotcsvRouteImport } from './routes/api/admin/exports/donations[.]csv'
import { Route as ApiAdminDonationsManualRouteImport } from './routes/api/admin/donations/manual'
import { Route as AdminAnimalsIdEditRouteImport } from './routes/admin/animals/$id.edit'
import { Route as ApiAdminSupportersIdConsentsRouteImport } from './routes/api/admin/supporters/$id/consents'
import { Route as ApiAdminReceiptsIdVoidRouteImport } from './routes/api/admin/receipts/$id/void'
import { Route as ApiAdminPaymentsIdReconcileRouteImport } from './routes/api/admin/payments/$id/reconcile'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIdRoute = SponsorsIdRouteImport.update({
  id: '/sponsors_/$id',
  path: '/sponsors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAuditRoute = ReportAuditRouteImport.update({
  id: '/report/audit',
  path: '/report/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAdoptionRoute = ReportAdoptionRouteImport.update({
  id: '/report/adoption',
  path: '/report/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsRoute = ApiDonationsRouteImport.update({
  id: '/api/donations',
  path: '/api/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsDogRoute = AnimalsDogRouteImport.update({
  id: '/animals/dog',
  path: '/animals/dog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsCatRoute = AnimalsCatRouteImport.update({
  id: '/animals/cat',
  path: '/animals/cat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionInstructionsRoute = AdoptionInstructionsRouteImport.update({
  id: '/adoption/instructions',
  path: '/adoption/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionApplyRoute = AdoptionApplyRouteImport.update({
  id: '/adoption/apply',
  path: '/adoption/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportersRoute = AdminSupportersRouteImport.update({
  id: '/admin/supporters',
  path: '/admin/supporters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTnrRoute = AboutTnrRouteImport.update({
  id: '/about/tnr',
  path: '/about/tnr',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPrivacyRoute = AboutPrivacyRouteImport.update({
  id: '/about/privacy',
  path: '/about/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCccpRoute = AboutCccpRouteImport.update({
  id: '/about/cccp',
  path: '/about/cccp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaypalRoute = ApiWebhooksPaypalRouteImport.update({
  id: '/api/webhooks/paypal',
  path: '/api/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSupportersRoute = ApiAdminSupportersRouteImport.update({
  id: '/api/admin/supporters',
  path: '/api/admin/supporters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReceiptsRoute = ApiAdminReceiptsRouteImport.update({
  id: '/api/admin/receipts',
  path: '/api/admin/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsRoute = ApiAdminPaymentsRouteImport.update({
  id: '/api/admin/payments',
  path: '/api/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsDogIdRoute = AnimalsDogIdRouteImport.update({
  id: '/animals/dog_/$id',
  path: '/animals/dog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsCatIdRoute = AnimalsCatIdRouteImport.update({
  id: '/animals/cat_/$id',
  path: '/animals/cat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportersIdRoute = AdminSupportersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSupportersRoute,
} as any)
const AdminAnimalsNewRoute = AdminAnimalsNewRouteImport.update({
  id: '/admin/animals/new',
  path: '/admin/animals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSupportersIdRoute = ApiAdminSupportersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminSupportersRoute,
} as any)
const ApiAdminExportsSupportersDotcsvRoute =
  ApiAdminExportsSupportersDotcsvRouteImport.update({
    id: '/api/admin/exports/supporters.csv',
    path: '/api/admin/exports/supporters.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminExportsDonationsDotcsvRoute =
  ApiAdminExportsDonationsDotcsvRouteImport.update({
    id: '/api/admin/exports/donations.csv',
    path: '/api/admin/exports/donations.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDonationsManualRoute = ApiAdminDonationsManualRouteImport.update({
  id: '/api/admin/donations/manual',
  path: '/api/admin/donations/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnimalsIdEditRoute = AdminAnimalsIdEditRouteImport.update({
  id: '/admin/animals/$id/edit',
  path: '/admin/animals/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSupportersIdConsentsRoute =
  ApiAdminSupportersIdConsentsRouteImport.update({
    id: '/consents',
    path: '/consents',
    getParentRoute: () => ApiAdminSupportersIdRoute,
  } as any)
const ApiAdminReceiptsIdVoidRoute = ApiAdminReceiptsIdVoidRouteImport.update({
  id: '/$id/void',
  path: '/$id/void',
  getParentRoute: () => ApiAdminReceiptsRoute,
} as any)
const ApiAdminPaymentsIdReconcileRoute =
  ApiAdminPaymentsIdReconcileRouteImport.update({
    id: '/$id/reconcile',
    path: '/$id/reconcile',
    getParentRoute: () => ApiAdminPaymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/sponsors': typeof SponsorsRoute
  '/volunteer': typeof VolunteerRoute
  '/about/cccp': typeof AboutCccpRoute
  '/about/privacy': typeof AboutPrivacyRoute
  '/about/team': typeof AboutTeamRoute
  '/about/tnr': typeof AboutTnrRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/supporters': typeof AdminSupportersRouteWithChildren
  '/adoption/apply': typeof AdoptionApplyRoute
  '/adoption/instructions': typeof AdoptionInstructionsRoute
  '/animals/cat': typeof AnimalsCatRoute
  '/animals/dog': typeof AnimalsDogRoute
  '/api/donations': typeof ApiDonationsRoute
  '/report/adoption': typeof ReportAdoptionRoute
  '/report/audit': typeof ReportAuditRoute
  '/sponsors/$id': typeof SponsorsIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/animals/new': typeof AdminAnimalsNewRoute
  '/admin/supporters/$id': typeof AdminSupportersIdRoute
  '/animals/cat/$id': typeof AnimalsCatIdRoute
  '/animals/dog/$id': typeof AnimalsDogIdRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRouteWithChildren
  '/api/admin/receipts': typeof ApiAdminReceiptsRouteWithChildren
  '/api/admin/supporters': typeof ApiAdminSupportersRouteWithChildren
  '/api/webhooks/paypal': typeof ApiWebhooksPaypalRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/animals/$id/edit': typeof AdminAnimalsIdEditRoute
  '/api/admin/donations/manual': typeof ApiAdminDonationsManualRoute
  '/api/admin/exports/donations.csv': typeof ApiAdminExportsDonationsDotcsvRoute
  '/api/admin/exports/supporters.csv': typeof ApiAdminExportsSupportersDotcsvRoute
  '/api/admin/supporters/$id': typeof ApiAdminSupportersIdRouteWithChildren
  '/api/admin/payments/$id/reconcile': typeof ApiAdminPaymentsIdReconcileRoute
  '/api/admin/receipts/$id/void': typeof ApiAdminReceiptsIdVoidRoute
  '/api/admin/supporters/$id/consents': typeof ApiAdminSupportersIdConsentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/sponsors': typeof SponsorsRoute
  '/volunteer': typeof VolunteerRoute
  '/about/cccp': typeof AboutCccpRoute
  '/about/privacy': typeof AboutPrivacyRoute
  '/about/team': typeof AboutTeamRoute
  '/about/tnr': typeof AboutTnrRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/supporters': typeof AdminSupportersRouteWithChildren
  '/adoption/apply': typeof AdoptionApplyRoute
  '/adoption/instructions': typeof AdoptionInstructionsRoute
  '/animals/cat': typeof AnimalsCatRoute
  '/animals/dog': typeof AnimalsDogRoute
  '/api/donations': typeof ApiDonationsRoute
  '/report/adoption': typeof ReportAdoptionRoute
  '/report/audit': typeof ReportAuditRoute
  '/sponsors/$id': typeof SponsorsIdRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/animals/new': typeof AdminAnimalsNewRoute
  '/admin/supporters/$id': typeof AdminSupportersIdRoute
  '/animals/cat/$id': typeof AnimalsCatIdRoute
  '/animals/dog/$id': typeof AnimalsDogIdRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRouteWithChildren
  '/api/admin/receipts': typeof ApiAdminReceiptsRouteWithChildren
  '/api/admin/supporters': typeof ApiAdminSupportersRouteWithChildren
  '/api/webhooks/paypal': typeof ApiWebhooksPaypalRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/animals/$id/edit': typeof AdminAnimalsIdEditRoute
  '/api/admin/donations/manual': typeof ApiAdminDonationsManualRoute
  '/api/admin/exports/donations.csv': typeof ApiAdminExportsDonationsDotcsvRoute
  '/api/admin/exports/supporters.csv': typeof ApiAdminExportsSupportersDotcsvRoute
  '/api/admin/supporters/$id': typeof ApiAdminSupportersIdRouteWithChildren
  '/api/admin/payments/$id/reconcile': typeof ApiAdminPaymentsIdReconcileRoute
  '/api/admin/receipts/$id/void': typeof ApiAdminReceiptsIdVoidRoute
  '/api/admin/supporters/$id/consents': typeof ApiAdminSupportersIdConsentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/sponsors': typeof SponsorsRoute
  '/volunteer': typeof VolunteerRoute
  '/about/cccp': typeof AboutCccpRoute
  '/about/privacy': typeof AboutPrivacyRoute
  '/about/team': typeof AboutTeamRoute
  '/about/tnr': typeof AboutTnrRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/supporters': typeof AdminSupportersRouteWithChildren
  '/adoption/apply': typeof AdoptionApplyRoute
  '/adoption/instructions': typeof AdoptionInstructionsRoute
  '/animals/cat': typeof AnimalsCatRoute
  '/animals/dog': typeof AnimalsDogRoute
  '/api/donations': typeof ApiDonationsRoute
  '/report/adoption': typeof ReportAdoptionRoute
  '/report/audit': typeof ReportAuditRoute
  '/sponsors_/$id': typeof SponsorsIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/animals/new': typeof AdminAnimalsNewRoute
  '/admin/supporters/$id': typeof AdminSupportersIdRoute
  '/animals/cat_/$id': typeof AnimalsCatIdRoute
  '/animals/dog_/$id': typeof AnimalsDogIdRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRouteWithChildren
  '/api/admin/receipts': typeof ApiAdminReceiptsRouteWithChildren
  '/api/admin/supporters': typeof ApiAdminSupportersRouteWithChildren
  '/api/webhooks/paypal': typeof ApiWebhooksPaypalRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/animals/$id/edit': typeof AdminAnimalsIdEditRoute
  '/api/admin/donations/manual': typeof ApiAdminDonationsManualRoute
  '/api/admin/exports/donations.csv': typeof ApiAdminExportsDonationsDotcsvRoute
  '/api/admin/exports/supporters.csv': typeof ApiAdminExportsSupportersDotcsvRoute
  '/api/admin/supporters/$id': typeof ApiAdminSupportersIdRouteWithChildren
  '/api/admin/payments/$id/reconcile': typeof ApiAdminPaymentsIdReconcileRoute
  '/api/admin/receipts/$id/void': typeof ApiAdminReceiptsIdVoidRoute
  '/api/admin/supporters/$id/consents': typeof ApiAdminSupportersIdConsentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donate'
    | '/sponsors'
    | '/volunteer'
    | '/about/cccp'
    | '/about/privacy'
    | '/about/team'
    | '/about/tnr'
    | '/admin/login'
    | '/admin/supporters'
    | '/adoption/apply'
    | '/adoption/instructions'
    | '/animals/cat'
    | '/animals/dog'
    | '/api/donations'
    | '/report/adoption'
    | '/report/audit'
    | '/sponsors/$id'
    | '/about/'
    | '/admin/'
    | '/admin/animals/new'
    | '/admin/supporters/$id'
    | '/animals/cat/$id'
    | '/animals/dog/$id'
    | '/api/admin/payments'
    | '/api/admin/receipts'
    | '/api/admin/supporters'
    | '/api/webhooks/paypal'
    | '/api/webhooks/stripe'
    | '/admin/animals/$id/edit'
    | '/api/admin/donations/manual'
    | '/api/admin/exports/donations.csv'
    | '/api/admin/exports/supporters.csv'
    | '/api/admin/supporters/$id'
    | '/api/admin/payments/$id/reconcile'
    | '/api/admin/receipts/$id/void'
    | '/api/admin/supporters/$id/consents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate'
    | '/sponsors'
    | '/volunteer'
    | '/about/cccp'
    | '/about/privacy'
    | '/about/team'
    | '/about/tnr'
    | '/admin/login'
    | '/admin/supporters'
    | '/adoption/apply'
    | '/adoption/instructions'
    | '/animals/cat'
    | '/animals/dog'
    | '/api/donations'
    | '/report/adoption'
    | '/report/audit'
    | '/sponsors/$id'
    | '/about'
    | '/admin'
    | '/admin/animals/new'
    | '/admin/supporters/$id'
    | '/animals/cat/$id'
    | '/animals/dog/$id'
    | '/api/admin/payments'
    | '/api/admin/receipts'
    | '/api/admin/supporters'
    | '/api/webhooks/paypal'
    | '/api/webhooks/stripe'
    | '/admin/animals/$id/edit'
    | '/api/admin/donations/manual'
    | '/api/admin/exports/donations.csv'
    | '/api/admin/exports/supporters.csv'
    | '/api/admin/supporters/$id'
    | '/api/admin/payments/$id/reconcile'
    | '/api/admin/receipts/$id/void'
    | '/api/admin/supporters/$id/consents'
  id:
    | '__root__'
    | '/'
    | '/donate'
    | '/sponsors'
    | '/volunteer'
    | '/about/cccp'
    | '/about/privacy'
    | '/about/team'
    | '/about/tnr'
    | '/admin/login'
    | '/admin/supporters'
    | '/adoption/apply'
    | '/adoption/instructions'
    | '/animals/cat'
    | '/animals/dog'
    | '/api/donations'
    | '/report/adoption'
    | '/report/audit'
    | '/sponsors_/$id'
    | '/about/'
    | '/admin/'
    | '/admin/animals/new'
    | '/admin/supporters/$id'
    | '/animals/cat_/$id'
    | '/animals/dog_/$id'
    | '/api/admin/payments'
    | '/api/admin/receipts'
    | '/api/admin/supporters'
    | '/api/webhooks/paypal'
    | '/api/webhooks/stripe'
    | '/admin/animals/$id/edit'
    | '/api/admin/donations/manual'
    | '/api/admin/exports/donations.csv'
    | '/api/admin/exports/supporters.csv'
    | '/api/admin/supporters/$id'
    | '/api/admin/payments/$id/reconcile'
    | '/api/admin/receipts/$id/void'
    | '/api/admin/supporters/$id/consents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateRoute: typeof DonateRoute
  SponsorsRoute: typeof SponsorsRoute
  VolunteerRoute: typeof VolunteerRoute
  AboutCccpRoute: typeof AboutCccpRoute
  AboutPrivacyRoute: typeof AboutPrivacyRoute
  AboutTeamRoute: typeof AboutTeamRoute
  AboutTnrRoute: typeof AboutTnrRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSupportersRoute: typeof AdminSupportersRouteWithChildren
  AdoptionApplyRoute: typeof AdoptionApplyRoute
  AdoptionInstructionsRoute: typeof AdoptionInstructionsRoute
  AnimalsCatRoute: typeof AnimalsCatRoute
  AnimalsDogRoute: typeof AnimalsDogRoute
  ApiDonationsRoute: typeof ApiDonationsRoute
  ReportAdoptionRoute: typeof ReportAdoptionRoute
  ReportAuditRoute: typeof ReportAuditRoute
  SponsorsIdRoute: typeof SponsorsIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnimalsNewRoute: typeof AdminAnimalsNewRoute
  AnimalsCatIdRoute: typeof AnimalsCatIdRoute
  AnimalsDogIdRoute: typeof AnimalsDogIdRoute
  ApiAdminPaymentsRoute: typeof ApiAdminPaymentsRouteWithChildren
  ApiAdminReceiptsRoute: typeof ApiAdminReceiptsRouteWithChildren
  ApiAdminSupportersRoute: typeof ApiAdminSupportersRouteWithChildren
  ApiWebhooksPaypalRoute: typeof ApiWebhooksPaypalRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  AdminAnimalsIdEditRoute: typeof AdminAnimalsIdEditRoute
  ApiAdminDonationsManualRoute: typeof ApiAdminDonationsManualRoute
  ApiAdminExportsDonationsDotcsvRoute: typeof ApiAdminExportsDonationsDotcsvRoute
  ApiAdminExportsSupportersDotcsvRoute: typeof ApiAdminExportsSupportersDotcsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors_/$id': {
      id: '/sponsors_/$id'
      path: '/sponsors/$id'
      fullPath: '/sponsors/$id'
      preLoaderRoute: typeof SponsorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/audit': {
      id: '/report/audit'
      path: '/report/audit'
      fullPath: '/report/audit'
      preLoaderRoute: typeof ReportAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/adoption': {
      id: '/report/adoption'
      path: '/report/adoption'
      fullPath: '/report/adoption'
      preLoaderRoute: typeof ReportAdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations': {
      id: '/api/donations'
      path: '/api/donations'
      fullPath: '/api/donations'
      preLoaderRoute: typeof ApiDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/dog': {
      id: '/animals/dog'
      path: '/animals/dog'
      fullPath: '/animals/dog'
      preLoaderRoute: typeof AnimalsDogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/cat': {
      id: '/animals/cat'
      path: '/animals/cat'
      fullPath: '/animals/cat'
      preLoaderRoute: typeof AnimalsCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption/instructions': {
      id: '/adoption/instructions'
      path: '/adoption/instructions'
      fullPath: '/adoption/instructions'
      preLoaderRoute: typeof AdoptionInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption/apply': {
      id: '/adoption/apply'
      path: '/adoption/apply'
      fullPath: '/adoption/apply'
      preLoaderRoute: typeof AdoptionApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/supporters': {
      id: '/admin/supporters'
      path: '/admin/supporters'
      fullPath: '/admin/supporters'
      preLoaderRoute: typeof AdminSupportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/tnr': {
      id: '/about/tnr'
      path: '/about/tnr'
      fullPath: '/about/tnr'
      preLoaderRoute: typeof AboutTnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/privacy': {
      id: '/about/privacy'
      path: '/about/privacy'
      fullPath: '/about/privacy'
      preLoaderRoute: typeof AboutPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/cccp': {
      id: '/about/cccp'
      path: '/about/cccp'
      fullPath: '/about/cccp'
      preLoaderRoute: typeof AboutCccpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paypal': {
      id: '/api/webhooks/paypal'
      path: '/api/webhooks/paypal'
      fullPath: '/api/webhooks/paypal'
      preLoaderRoute: typeof ApiWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/supporters': {
      id: '/api/admin/supporters'
      path: '/api/admin/supporters'
      fullPath: '/api/admin/supporters'
      preLoaderRoute: typeof ApiAdminSupportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/receipts': {
      id: '/api/admin/receipts'
      path: '/api/admin/receipts'
      fullPath: '/api/admin/receipts'
      preLoaderRoute: typeof ApiAdminReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments': {
      id: '/api/admin/payments'
      path: '/api/admin/payments'
      fullPath: '/api/admin/payments'
      preLoaderRoute: typeof ApiAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/dog_/$id': {
      id: '/animals/dog_/$id'
      path: '/animals/dog/$id'
      fullPath: '/animals/dog/$id'
      preLoaderRoute: typeof AnimalsDogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/cat_/$id': {
      id: '/animals/cat_/$id'
      path: '/animals/cat/$id'
      fullPath: '/animals/cat/$id'
      preLoaderRoute: typeof AnimalsCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/supporters/$id': {
      id: '/admin/supporters/$id'
      path: '/$id'
      fullPath: '/admin/supporters/$id'
      preLoaderRoute: typeof AdminSupportersIdRouteImport
      parentRoute: typeof AdminSupportersRoute
    }
    '/admin/animals/new': {
      id: '/admin/animals/new'
      path: '/admin/animals/new'
      fullPath: '/admin/animals/new'
      preLoaderRoute: typeof AdminAnimalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/supporters/$id': {
      id: '/api/admin/supporters/$id'
      path: '/$id'
      fullPath: '/api/admin/supporters/$id'
      preLoaderRoute: typeof ApiAdminSupportersIdRouteImport
      parentRoute: typeof ApiAdminSupportersRoute
    }
    '/api/admin/exports/supporters.csv': {
      id: '/api/admin/exports/supporters.csv'
      path: '/api/admin/exports/supporters.csv'
      fullPath: '/api/admin/exports/supporters.csv'
      preLoaderRoute: typeof ApiAdminExportsSupportersDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/exports/donations.csv': {
      id: '/api/admin/exports/donations.csv'
      path: '/api/admin/exports/donations.csv'
      fullPath: '/api/admin/exports/donations.csv'
      preLoaderRoute: typeof ApiAdminExportsDonationsDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/donations/manual': {
      id: '/api/admin/donations/manual'
      path: '/api/admin/donations/manual'
      fullPath: '/api/admin/donations/manual'
      preLoaderRoute: typeof ApiAdminDonationsManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/animals/$id/edit': {
      id: '/admin/animals/$id/edit'
      path: '/admin/animals/$id/edit'
      fullPath: '/admin/animals/$id/edit'
      preLoaderRoute: typeof AdminAnimalsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/supporters/$id/consents': {
      id: '/api/admin/supporters/$id/consents'
      path: '/consents'
      fullPath: '/api/admin/supporters/$id/consents'
      preLoaderRoute: typeof ApiAdminSupportersIdConsentsRouteImport
      parentRoute: typeof ApiAdminSupportersIdRoute
    }
    '/api/admin/receipts/$id/void': {
      id: '/api/admin/receipts/$id/void'
      path: '/$id/void'
      fullPath: '/api/admin/receipts/$id/void'
      preLoaderRoute: typeof ApiAdminReceiptsIdVoidRouteImport
      parentRoute: typeof ApiAdminReceiptsRoute
    }
    '/api/admin/payments/$id/reconcile': {
      id: '/api/admin/payments/$id/reconcile'
      path: '/$id/reconcile'
      fullPath: '/api/admin/payments/$id/reconcile'
      preLoaderRoute: typeof ApiAdminPaymentsIdReconcileRouteImport
      parentRoute: typeof ApiAdminPaymentsRoute
    }
  }
}

interface AdminSupportersRouteChildren {
  AdminSupportersIdRoute: typeof AdminSupportersIdRoute
}

const AdminSupportersRouteChildren: AdminSupportersRouteChildren = {
  AdminSupportersIdRoute: AdminSupportersIdRoute,
}

const AdminSupportersRouteWithChildren = AdminSupportersRoute._addFileChildren(
  AdminSupportersRouteChildren,
)

interface ApiAdminPaymentsRouteChildren {
  ApiAdminPaymentsIdReconcileRoute: typeof ApiAdminPaymentsIdReconcileRoute
}

const ApiAdminPaymentsRouteChildren: ApiAdminPaymentsRouteChildren = {
  ApiAdminPaymentsIdReconcileRoute: ApiAdminPaymentsIdReconcileRoute,
}

const ApiAdminPaymentsRouteWithChildren =
  ApiAdminPaymentsRoute._addFileChildren(ApiAdminPaymentsRouteChildren)

interface ApiAdminReceiptsRouteChildren {
  ApiAdminReceiptsIdVoidRoute: typeof ApiAdminReceiptsIdVoidRoute
}

const ApiAdminReceiptsRouteChildren: ApiAdminReceiptsRouteChildren = {
  ApiAdminReceiptsIdVoidRoute: ApiAdminReceiptsIdVoidRoute,
}

const ApiAdminReceiptsRouteWithChildren =
  ApiAdminReceiptsRoute._addFileChildren(ApiAdminReceiptsRouteChildren)

interface ApiAdminSupportersIdRouteChildren {
  ApiAdminSupportersIdConsentsRoute: typeof ApiAdminSupportersIdConsentsRoute
}

const ApiAdminSupportersIdRouteChildren: ApiAdminSupportersIdRouteChildren = {
  ApiAdminSupportersIdConsentsRoute: ApiAdminSupportersIdConsentsRoute,
}

const ApiAdminSupportersIdRouteWithChildren =
  ApiAdminSupportersIdRoute._addFileChildren(ApiAdminSupportersIdRouteChildren)

interface ApiAdminSupportersRouteChildren {
  ApiAdminSupportersIdRoute: typeof ApiAdminSupportersIdRouteWithChildren
}

const ApiAdminSupportersRouteChildren: ApiAdminSupportersRouteChildren = {
  ApiAdminSupportersIdRoute: ApiAdminSupportersIdRouteWithChildren,
}

const ApiAdminSupportersRouteWithChildren =
  ApiAdminSupportersRoute._addFileChildren(ApiAdminSupportersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateRoute: DonateRoute,
  SponsorsRoute: SponsorsRoute,
  VolunteerRoute: VolunteerRoute,
  AboutCccpRoute: AboutCccpRoute,
  AboutPrivacyRoute: AboutPrivacyRoute,
  AboutTeamRoute: AboutTeamRoute,
  AboutTnrRoute: AboutTnrRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSupportersRoute: AdminSupportersRouteWithChildren,
  AdoptionApplyRoute: AdoptionApplyRoute,
  AdoptionInstructionsRoute: AdoptionInstructionsRoute,
  AnimalsCatRoute: AnimalsCatRoute,
  AnimalsDogRoute: AnimalsDogRoute,
  ApiDonationsRoute: ApiDonationsRoute,
  ReportAdoptionRoute: ReportAdoptionRoute,
  ReportAuditRoute: ReportAuditRoute,
  SponsorsIdRoute: SponsorsIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnimalsNewRoute: AdminAnimalsNewRoute,
  AnimalsCatIdRoute: AnimalsCatIdRoute,
  AnimalsDogIdRoute: AnimalsDogIdRoute,
  ApiAdminPaymentsRoute: ApiAdminPaymentsRouteWithChildren,
  ApiAdminReceiptsRoute: ApiAdminReceiptsRouteWithChildren,
  ApiAdminSupportersRoute: ApiAdminSupportersRouteWithChildren,
  ApiWebhooksPaypalRoute: ApiWebhooksPaypalRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  AdminAnimalsIdEditRoute: AdminAnimalsIdEditRoute,
  ApiAdminDonationsManualRoute: ApiAdminDonationsManualRoute,
  ApiAdminExportsDonationsDotcsvRoute: ApiAdminExportsDonationsDotcsvRoute,
  ApiAdminExportsSupportersDotcsvRoute: ApiAdminExportsSupportersDotcsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
