-- Harden the donation receipt lifecycle against duplicate issuance and against
-- burning IRD sequence numbers on partial failures.
--
-- Two problems this fixes:
--   1. Receipt numbers were allocated by `private.allocate_receipt_number`
--      (its own committed transaction) BEFORE the PDF/storage/row insert. Any
--      failure consumed a sequence number with no row, and a retry allocated a
--      fresh number -> non-contiguous tax-receipt sequence + multiple numbers
--      per donation.
--   2. Duplicate issuance was guarded only by a read-then-insert check in
--      application code with no DB-level uniqueness, so concurrent webhook /
--      admin issuance could mint two valid receipts for one donation.
--
-- Fix: a single atomic RPC that allocates the number AND inserts the receipt
-- row in one transaction, is idempotent per donation, and is backed by a unique
-- partial index. The PDF is generated by the caller AFTER the row commits, so a
-- PDF/storage failure never wastes a number (the row already owns it and a retry
-- reuses it).

-- One issued receipt per donation. donation_ids is always a single-element array
-- in current code paths, so the first element identifies the donation. Voided
-- receipts are excluded so a donation can legitimately be re-receipted after a
-- void.
--
-- NOTE: if any duplicate issued receipts already exist in the target database
-- this index creation will fail; resolve those duplicates first.
create unique index if not exists receipt_one_issued_per_donation
  on public.receipt ((donation_ids[1]))
  where status = 'issued';

-- Defined in `public` (not `private`) so the service-role client can call it
-- over PostgREST via client.rpc("issue_receipt", ...) — the same pattern as the
-- working change_adoption_case_status / finalize_successful_adoption RPCs. The
-- `private` schema is not exposed to PostgREST and service_role lacks USAGE on
-- it, so a private RPC is unreachable from the app. The SECURITY DEFINER body
-- still reaches private.allocate_receipt_number because the function owner has
-- USAGE on private.
create or replace function public.issue_receipt(
  p_donation_id uuid,
  p_supporter_id uuid,
  p_amount_cents integer,
  p_tax_year integer,
  p_issued_at timestamptz
)
returns table (
  receipt_no text,
  receipt_id uuid,
  pdf_url text,
  tax_year integer,
  issued_at timestamptz,
  already_existed boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing public.receipt;
  v_receipt_no text;
  v_receipt_id uuid;
begin
  -- Idempotent: an issued receipt already exists for this donation.
  select * into v_existing
  from public.receipt r
  where r.status = 'issued'
    and r.donation_ids[1] = p_donation_id
  limit 1;

  if found then
    receipt_no := v_existing.receipt_no;
    receipt_id := v_existing.id;
    pdf_url := v_existing.pdf_url;
    tax_year := v_existing.tax_year;
    issued_at := v_existing.issued_at;
    already_existed := true;
    return next;
    return;
  end if;

  -- Allocate the number and insert the row in the same (sub)transaction. If the
  -- insert hits the unique index because a concurrent caller won the race, the
  -- exception block rolls back this allocation (no wasted number) and we return
  -- the winner's row.
  v_receipt_no := private.allocate_receipt_number(p_tax_year);

  insert into public.receipt (
    supporter_id,
    receipt_no,
    donation_ids,
    total_amount_cents,
    tax_year,
    issued_at,
    status
  ) values (
    p_supporter_id,
    v_receipt_no,
    array[p_donation_id],
    p_amount_cents,
    p_tax_year,
    p_issued_at,
    'issued'
  )
  returning id into v_receipt_id;

  receipt_no := v_receipt_no;
  receipt_id := v_receipt_id;
  pdf_url := null;
  tax_year := p_tax_year;
  issued_at := p_issued_at;
  already_existed := false;
  return next;
exception
  when unique_violation then
    select * into v_existing
    from public.receipt r
    where r.status = 'issued'
      and r.donation_ids[1] = p_donation_id
    limit 1;

    -- The conflicting row must have existed to raise the violation, but it could
    -- have been voided in the tiny window before this recovery read. Re-raise so
    -- the caller retries cleanly rather than receiving a NULL-filled row.
    if not found then
      raise;
    end if;

    receipt_no := v_existing.receipt_no;
    receipt_id := v_existing.id;
    pdf_url := v_existing.pdf_url;
    tax_year := v_existing.tax_year;
    issued_at := v_existing.issued_at;
    already_existed := true;
    return next;
end;
$$;

revoke all on function public.issue_receipt(uuid, uuid, integer, integer, timestamptz) from public;
grant execute on function public.issue_receipt(uuid, uuid, integer, integer, timestamptz) to service_role;
